### ISSUE TITLE
Issue in Windows Update 22H2

### ISSUE THREAD

**Issue by anurag01a** [TranslucentTB/TranslucentTB#659] opened 2022-10-05 14:12 UTC
Hello Team!

TranslucentTB is not operating correctly with the latest Windows 22H2 upgrade. A thin white line is showing on the taskbar in the desktop as a result of the blur or clear option of the taskbar not functioning properly.

Update, please!

**Comment by sylveon** [comment] 2022-10-05 14:15
Duplicate of #425

**Closed as not planned by sylveon** 2022-10-05 14:15 UTC
