### ISSUE TITLE
Translucent works, but line.

### ISSUE THREAD

**Issue by juntulis** [TranslucentTB/TranslucentTB#654] opened 2022-09-29 14:35 UTC
Is there a way to remove this line?
![Untitled](https://user-images.githubusercontent.com/113700121/193060547-0cd31c84-8679-404d-84ce-bfa3605939fb.png)

**Comment by DanielQu9** [comment] 2022-09-29 16:40
Had the same problem when I updated to 22H2
![image](https://user-images.githubusercontent.com/52659640/193089511-50db8d8b-057b-4f94-92a5-be178b55d65e.png)

**Comment by sylveon** [comment] 2022-09-29 20:42
Duplicate of #425

**Closed as not planned** 2022-09-29 20:42 UTC
