### ISSUE TITLE
not working in windows 11 latest update

### ISSUE THREAD

**Issue by sahilbhatiwal** [TranslucentTB/TranslucentTB#573] opened 2022-03-26 07:40 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by bad0s1** [comment] 2022-03-26 07:52
Not working for me also.
![image](https://user-images.githubusercontent.com/48060869/160230270-e50b7d4a-791d-4613-bc5c-b3a01b6ea34c.png)

This solution didn't help #537

**Comment by GZTimeWalker** [comment] 2022-03-26 08:06
The same problem happened to me.

**Comment by sylveon** [comment] 2022-03-26 08:42
Duplicate of #537

**Closed as completed by sylveon** 2022-03-26 08:42 UTC
