### ISSUE TITLE
Allow for blacklisting certain window classes with dynamic mode

### ISSUE THREAD

**Issue by charlesmilette** [TranslucentTB/TranslucentTB#38] opened 2017-01-30 19:13 UTC
Some programs, such as DeskScapes break the feature.

**Comment by olliethepikachu** [comment] 2017-03-17 06:09
Would this be done through a config file?

**Comment by olliethepikachu** [comment] 2017-03-17 06:10
Also if so, would you be blacklisting process names?

**Comment by ethanhs** [comment] 2017-03-17 06:31
I think a config file would be a good idea, yes.

**Comment by charlesmilette** [comment] 2017-03-17 11:21
I blacklisted by window class name in my test implementation. It allows for more precise control

**Comment by olliethepikachu** [comment] 2017-03-17 14:40
How about both? Not everyone has the patience or knowledge to find window class names.





On Fri, Mar 17, 2017 at 7:21 PM +0800, "Charles Milette" <notifications@github.com> wrote:












I blacklisted by window class name in my test implementation. It allows for more precise control

**Comment by charlesmilette** [comment] 2017-03-17 15:09
Good idea, we could have 3 lists:
- Window title contains
- Exe name
- Window class name

**Comment by ethanhs** [comment] 2017-03-17 19:20
I think the best idea would be essentially a csv file, with each column being optional.

**Comment by olliethepikachu** [comment] 2017-03-18 00:12
Is there any reason we couldn't use a JSON file? Perhaps make the config completely JSON? It's more human-readable, and we could use arrays to store the strings for the three filters.





On Sat, Mar 18, 2017 at 3:20 AM +0800, "Ethan" <notifications@github.com> wrote:












I think the best idea would be essentially a csv file, with each column being optional.

**Comment by ethanhs** [comment] 2017-03-18 00:41
JSON is really annoying to parse, so I dont think that is a good idea.

**Comment by olliethepikachu** [comment] 2017-03-18 00:45
But at the same time CSVs are difficult to read from a human perspective.





On Sat, Mar 18, 2017 at 8:41 AM +0800, "Ethan" <notifications@github.com> wrote:












JSON is really annoying to parse, so I dont think that is a good idea.

**Comment by ethanhs** [comment] 2017-03-18 01:23
I mean, not really. Commas are clearly separating data and since we'd only have 3 columns, it shouldn't be too complicated. Furthermore, most people would be able to edit it in Excel or Libre/OpenOffice. Or do it in docs and download as a csv.

**Comment by denosawr** [comment] 2017-05-02 09:55
Set as a V3 milestone, as this needs to be implemented - it affects large applications such as MS Outlook.

**Comment by ethanhs** [comment] 2017-05-02 10:12
Ah, then that is concerning. Anyone want to take this?

**Comment by denosawr** [comment] 2017-05-02 10:14
It shouldn't be too difficult, right? I've only got the weekends, though, so if you have time before feel free to work on it.

**Comment by denosawr** [comment] 2017-05-02 10:15
Actually, never mind, just realised that I have almost no time over the weekend due to personal commitments. Sorry!

**Comment by ethanhs** [comment] 2017-05-17 07:44
@charlesmilette how beta is your test implementation? Could it be shipped with V3?

**Comment by charlesmilette** [comment] 2017-05-17 11:49
My test implementation was the PR I done before. So, no.

**Comment by ethanhs** [comment] 2017-05-17 17:39
ah yes, okay. well, I suppose  I'll start on it.

**Comment by Mibo5354** [comment] 2017-05-19 07:07
This feature would go great with my rainmeter setup. 😃

**Comment by denosawr** [comment] 2017-05-21 01:46
@Mibo5354 Does Rainmeter break TTB in a reproducable way?

**Comment by denosawr** [comment] 2017-06-03 05:56
Committed a (hopefully) working implementation to 3cc6436. It is yet to be properly tested and merged to `develop` yet though.

**Comment by denosawr** [comment] 2017-06-03 06:05
Fixed an idiotic mistake in c396301. The previous commit won't work, but this one _should_.

**Closed** 2017-06-04 16:49 UTC
Labels: enhancement
