### ISSUE TITLE
[Bug]: Doesn't work on latest Windows 11 update

### ISSUE THREAD

**Issue by ish222** [TranslucentTB/TranslucentTB#753] opened 2023-03-03 20:28 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Updated Windows to 22H2 build 22621.1344 and this program stopped functioning. Restarting program, windows and changing settings does nothing.

### Expected results

Translucent taskbar

### Actual results

Normal Windows taskbar

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Relevant log output

```shell
[2023-03-03 20:27:35.000] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-03 20:27:35.001] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-03-03 20:27:35.001] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x100fa [] [Shell_TrayWnd] [explorer.exe]
[2023-03-03 20:27:35.001] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-03 20:27:35.001] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-03 20:27:35.001] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10003:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x1013c [] [Shell_SecondaryTrayWnd] [explorer.exe]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x10140 [] [WorkerW] [explorer.exe]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:708] 			0x207b0 [New Issue · TranslucentTB/TranslucentTB - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0xa051a [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-03-03 20:27:35.009] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by sylveon** [comment] 2023-03-03 20:35
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-03 20:35 UTC
Labels: bug
