### ISSUE TITLE
TranslucentTB not working

### ISSUE THREAD

**Issue by Redsnow6210** [TranslucentTB/TranslucentTB#576] opened 2022-03-27 03:54 UTC
I updated my Windows 11 to the latest insider preview and the app stopped working after that.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎25-‎03-‎2022
OS build	22581.100
Experience	Windows Feature Experience Pack 1000.22581.100.0

These are the details of the latest update.

Please help.

**Comment by sylveon** [comment] 2022-03-27 03:55
Duplicate of #537

**Closed as completed by sylveon** 2022-03-27 03:55 UTC
