### ISSUE TITLE
while clicking start menu the screen is going from translucent to black 

### ISSUE THREAD

**Issue by beastslayer-6310** [TranslucentTB/TranslucentTB#416] opened 2021-09-02 05:21 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment] 2021-09-02 05:38
Duplicate of #411 #415

**Closed as completed by sylveon** 2021-09-02 05:38 UTC
