### ISSUE TITLE
Problem running two programs in split screen

### ISSUE THREAD

**Issue by JAGBv1** [TranslucentTB/TranslucentTB#319] opened 2020-07-03 22:06 UTC
Configuration:
- Regular: Blur
- Maximised window: Opaque (Accent Color: Black)

PC:
- OS: Win 10 Pro 1903 x64
- Version: TranslucentBT 8.0 (from Microsoft Store)

Problem:
When running ONE program at full screen, if it correctly changes the taskbar to black. The problem is running two applications in half screen, it doesn't change to the color of the taskbar...it stays in blur.

**Comment by sylveon** [comment] 2020-07-03 22:11
This is normal behavior. Snapped windows aren't maximised windows.

**Comment by sylveon** [comment] 2020-07-03 22:14
I'm looking at introducing a feature where if the screen is fully covered by multiple windows it'll behave as if there's a maximised window, which would resolve this issue.

**Comment by JAGBv1** [comment] 2020-07-06 15:24
Thank you for the explanation @sylveon 

And by the way, that feature you mentioned would be very helpful. As you say, this is different from "maximized window", so it would be a new category, the sixth :)

**Comment by antonioacg** [comment] 2020-10-20 13:17
Would like to see that too!

**Comment by ThatCarrot** [comment] 2021-09-24 18:04
Has this feature been implemented?

**Comment by sylveon** [comment] 2021-09-26 05:42
Not in the end. Windows 11 undocumented APIs might help here, so I held off from the hard way for now.

**Comment by sylveon** [comment] 2023-07-09 20:07
Duplicate of #116

**Closed as not planned by sylveon** 2023-07-09 20:07 UTC
