### ISSUE TITLE
[Bug]: not working 

### ISSUE THREAD

**Issue by kokill6060** [TranslucentTB/TranslucentTB#777] opened 2023-03-09 15:46 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

i am using this app and it working good but now some 3 days befour i see the taskbar is not clear mean it not working . I try to uninstall and reinstall i reset all setting but still same thing 

### Expected results

i am using this app and it working good but now some 3 days befour i see the taskbar is not clear mean it not working . I try to uninstall and reinstall i reset all setting but still same thing 

### Actual results

i am using this app and it working good but now some 3 days befour i see the taskbar is not clear mean it not working . I try to uninstall and reinstall i reset all setting but still same thing 

### Windows version

Windows 11 RTM (build 22000)

### Other details

yo

### Relevant log output

```shell
yo
```

**Comment by carcheky** [comment] 2023-03-09 23:07
The same thing happens to me, a couple of days ago I had a Windows update, I am in version 22621.1344, I suspect that it may be the cause, the accent colors change them, but it does not make them transparent.

**Comment by sylveon** [comment] 2023-03-09 23:17
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-09 23:17 UTC
Labels: bug
