### ISSUE TITLE
[Bug]: Taskbar transparency effect invalid after Windows 11 update KB5023706

### ISSUE THREAD

**Issue by hjnnjh** [TranslucentTB/TranslucentTB#829] opened 2023-04-13 16:13 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install Windows 11 update KB5023706, then open TranslucentTB.

### Expected results

Hope this problem can be solved as soon as possible.

### Actual results

 Taskbar transparency effect invalid.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-04-13 16:13
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-13 16:13 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:29
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

**Comment by hjnnjh** [comment] 2023-05-03 09:34
@WantedTab Thanks for your advice. I temporally disabled the TranslucentTB and I'm just waiting for the update. Do not need this fix urgently.
