### ISSUE TITLE
TB isn't working in windows 11 22H2

### ISSUE THREAD

**Issue by Rimon551** [TranslucentTB/TranslucentTB#570] opened 2022-03-25 09:21 UTC
My computer is running windows 11 22H2 version, and for a few days now, TB isn't working (The 'clear' option isn't working).
![Screenshot_7](https://user-images.githubusercontent.com/61230038/160092211-a97f4d07-f052-4e73-9965-d37c3ed8a525.png)

**Comment by andeivanovue** [comment] 2022-03-25 11:30
+1

**Comment by JjIiNnXx** [comment] 2022-03-25 11:59
+1

**Comment by JjIiNnXx** [comment] 2022-03-25 12:09
please fix it，I can't live without it😭😭😭😭

**Comment by Asayaka** [comment] 2022-03-25 12:28
This is happening in Windows Insider Ver 22579 until now, And its happening to me too. Translucent TB doesnt working

**Comment by sylveon** [comment] 2022-03-25 12:31
Duplicate of #537

**Closed as completed by sylveon** 2022-03-25 12:31 UTC

**Comment by xyzuser12** [comment] 2022-03-28 10:43
I also had the same issue, is it because of the build itself, or is it coming from the software? Thanks.

**Comment by sylveon** [comment] 2022-03-28 17:11
It's because of changes in the windows Insider build

**Comment by xyzuser12** [comment] 2022-03-30 07:36
> 

Thanks for the info!
