### ISSUE TITLE
[Bug]: TranslucentTB stopped working after windows 11 update

### ISSUE THREAD

**Issue by Pillow-Fan** [TranslucentTB/TranslucentTB#856] opened 2023-05-25 19:15 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update the laptop via Windows Updater

### Expected results

TranslucentTB auto-starts and the taskbar becomes transparent

### Actual results

The app opens but the taskbar is not modified

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

The problem persist even after uninstalling the app

**Comment by sylveon** [comment] 2023-05-25 20:54
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-25 20:54 UTC
Labels: bug
