### ISSUE TITLE
Dynamics windows not working

### ISSUE THREAD

**Issue by wobolew** [TranslucentTB/TranslucentTB#111] opened 2017-10-21 07:37 UTC
Hi, 
I have a problem with dynamics windows, I don't see any diffrence when it's on or off. 
Maybe I'm wrong but this should make my task bar transparent when there is no open windows and normal (or blur) when I open something.
I have windows 10 with fall creators update.
Any thoughts?

Thx for the help :)

**Comment by sylveon** [comment] 2017-10-21 13:53
Duplicate of #84 

Try killing ApplicationFrameHost from the task manager, or uncomment the corresponding line in the exclude file.

**Closed by sylveon** 2017-10-21 13:53 UTC

**Comment by wobolew** [comment] 2017-10-22 20:57
Thank you and sorry for the duplicate I missed it
