### ISSUE TITLE
Doesn't seem to work anymore after installing Windows 11 Update

### ISSUE THREAD

**Issue by Noctiamor** [TranslucentTB/TranslucentTB#556] opened 2022-03-18 04:24 UTC
I'm on the Dev branch of the Windows 11 Insider Preview Builds, and after upgrading to build 22H2 (OS Build 22572.201), Experience Pack 1000.22572.201.0, nothing seems to work anymore. I have uninstalled and reinstalled, reset dynamic state, reset to default settings and the taskbar remains the default solid brush colour. I wasn't sure if anything in the Windows update changed something critical, as some previous issues with the taskbar have been fixed with this update.

**Comment by sylveon** [comment] 2022-03-18 05:03
Duplicate of #537

**Closed as completed by sylveon** 2022-03-18 05:03 UTC
