### ISSUE TITLE
TranslucentTB Does not function with the new taskbar system in Windows 11 build 22581

### ISSUE THREAD

**Issue by ItzELECTR0** [TranslucentTB/TranslucentTB#581] opened 2022-03-28 16:08 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5.0.0 (From Microsoft Store)

 - Steps to reproduce:
   1. Turn on your computer (In WIndows 11 Build 22581).
   2. Run TranslucentTB.

 - Expected results: The taskbar turns transparent.

 - What actually happens: The taskbar does not change at all despite the changes made in the TranslucentTB settings.

 - Other: I tried both the Github and Microsoft store versions, same results, but it did work in build 22579, before the taskbar system update.

**Comment by sylveon** [comment] 2022-03-28 17:12
Duplicate of #537

**Closed as completed by sylveon** 2022-03-28 17:12 UTC
