### ISSUE TITLE
[Bug]: Taskbar isn't turning translucent

### ISSUE THREAD

**Issue by PastryCoder** [TranslucentTB/TranslucentTB#860] opened 2023-05-31 11:58 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I've only installed the app along with rounded tb for compatibility. I have changed the settings so that the taskbar is transparent even with battery saver, full screened etc.

### Expected results

The taskbar to turn transparent 

### Actual results

Windows default taskbar

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I've installed Translucent TB and rounded tb from the Microsoft Store, and I am unable to make my taskbar transparent. I've tried restarting my computer, and uninstalling and reinstalling the app. I've changed the color settings to turn on Transparency effects. Rounded TB works fine, but Translucent TB isn't working as expected

**Comment by perigozin** [comment] 2023-05-31 12:42
To the author: people will keep asking why it doesn't work anymore, maybe you should put in the README that it only works with older versions of Windows 11.

**Comment by sylveon** [comment] 2023-05-31 15:11
Duplicate of #537

**Comment by sylveon** [comment] 2023-05-31 15:12
@bololodev #537 is pinned on top of the issues list, and the template asks people to check for a duplicate, and issues still happen. A  change to the readme probably wouldn't do much.

**Closed as not planned by sylveon** 2023-05-31 15:11 UTC
Labels: bug

**Comment by PastryCoder** [comment] 2023-06-01 05:16
Thank you for the help !
