### ISSUE TITLE
[Bug]: Translucenttb fails after updating KB5023706 patch for Windows 11

### ISSUE THREAD

**Issue by FogGlass** [TranslucentTB/TranslucentTB#795] opened 2023-03-23 08:42 UTC
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After updating the update pushed by Microsoft on March 2023.03, all effects of translucenttb have expired.

https://user-images.githubusercontent.com/114748804/227148561-dd76c138-1cee-491e-b2ac-47f627622417.mp4

### Expected results

Thought there was a conflict with other software, but it wasn't.

### Actual results

I tried to find the cause and solve this problem, I currently found the reason (the reason is that Microsoft closed the original taskbar transparent bar interface after updating the patch for KB5023706 on March 17, 2023, resulting in the current software could not be passed to the taskbar and the software function failed), requested the author to update, hope my feedback will be helpful to you, and look forward to getting your reply

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Sandor84CT** [comment] 2023-03-23 09:06
Same bug.
Windows 11 Pro
22H2
22621.1413

**Comment by Elaina69** [comment] 2023-03-23 09:50
same bug with build 25300.1000

**Comment by torajghaffari** [comment] 2023-03-23 11:37
Same bug
---------------------------
Edition: Windows 11 Pro
Version: 22H2
OS Build: 22621.1413

**Comment by DaRKeN58** [comment] 2023-03-23 12:16
Same bug
Edition: Windows 11 Pro
Version: 22H2
OS Build: 22621.1413

**Comment by ImVanillaHehe** [comment] 2023-03-23 13:08
Sane bug
Edition: Win 11 Pro
Version: 22H2
OS Build: 22621.1413

**Comment by xHaMMaDy** [comment] 2023-03-23 13:28
same bug
Edition: Win 11 Pro
Version: 22H2
OS Build: 22621.1413

**Comment by sylveon** [comment] 2023-03-23 14:14
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-23 14:14 UTC
Labels: bug

**Comment by TheFurryDevil** [comment] 2023-03-23 14:34
I highly recommend uninstalling KB5023706, it causes many issues. For me it made every program in general take about 60 seconds to start, which is a massive issue imho. If you noticed your PC being slow recently, this update is likely the cause.
After uninstalling, everything on my PC starts pretty much instantly again lol

**Comment by khizarrshahidd** [comment] 2023-03-23 18:06
> I highly recommend uninstalling KB5023706, it causes many issues. For me it made every program in general take about 60 seconds to start, which is a massive issue imho. If you noticed your PC being slow recently, this update is likely the cause. After uninstalling, everything on my PC starts pretty much instantly again lol

Nope, the problem is something else. I uninstalled this update following your advice and restarted PC, the app still refuses to function, tried all the functions, neither of them work except opaque.

**Comment by FogGlass** [comment] 2023-03-24 05:39
> 我强烈建议卸载KB5023706，它会导致许多问题。对我来说，它使每个程序通常需要大约 60 秒才能启动，恕我直言，这是一个大问题。如果您最近注意到您的电脑运行缓慢，则此更新可能是原因。卸载后，我 PC 上的所有内容几乎立即再次开始，哈哈

I'd better wait for the TranslucentTB update, my computer doesn't feel much at the moment, the status bar animation of KB5023706 patch update I like it, the status bar is a little uncomfortable not transparent.

**Comment by FogGlass** [comment] 2023-03-24 05:43
> > 我强烈建议卸载KB5023706，它会导致许多问题。对我来说，它使每个程序通常需要大约 60 秒才能启动，恕我直言，这是一个大问题。如果您最近注意到您的电脑运行缓慢，则此更新可能是原因。卸载后，我 PC 上的所有内容几乎立即再次开始，哈哈
> 
> 不，问题是别的。我按照您的建议卸载了此更新并重新启动了PC，该应用程序仍然拒绝运行，尝试了所有功能，除了不透明之外，它们都不起作用。

Well... What patch KB5023706 has found so far is an update to the status bar animation

**Comment by FogGlass** [comment] 2023-03-24 05:47
> 我强烈建议卸载KB5023706，它会导致许多问题。对我来说，它使每个程序通常需要大约 60 秒才能启动，恕我直言，这是一个大问题。如果您最近注意到您的电脑运行缓慢，则此更新可能是原因。卸载后，我 PC 上的所有内容几乎立即再次开始，哈哈

In fact, you can modify the registry by using software to change the status bar back to the way it was before
