### ISSUE TITLE
[Bug]: Not working in Windows 11 22H2 22621.1343

### ISSUE THREAD

**Issue by JohyC** [TranslucentTB/TranslucentTB#731] opened 2023-02-24 01:50 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

update to Windows 11 22H2 22621.1343

### Expected results

got transparent menu !

### Actual results

not working! nothing to change ....

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Relevant log output

```shell
[2023-02-24 01:42:41.519] [debug] [taskbarattributeworker.cpp:1133] Resetting worker state
[2023-02-24 01:42:41.552] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x4f0684 [CentOS 7 上编译安装 Podman 3.4.4 - 掘金 - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-02-24 01:42:41.564] [debug] [taskbarattributeworker.cpp:566] Inserting maximised window 0x4f0684 [CentOS 7 上编译安装 Podman 3.4.4 - 掘金 - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe] to monitor 0x10001
[2023-02-24 01:42:41.565] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x203d6 [Issues · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe] to monitor 0x10001
[2023-02-24 01:42:41.565] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x27084a [设置] [ApplicationFrameWindow] [ApplicationFrameHost.exe] to monitor 0x10001
[2023-02-24 01:42:41.565] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x50710 [微信] [WeChatMainWndForPC] [WeChat.exe] to monitor 0x10001
[2023-02-24 01:42:44.874] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x201f2 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-24 01:42:45.383] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5706b6 [系统托盘溢出窗口。] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-02-24 01:42:46.592] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x1c0966 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-24 01:42:48.891] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0xf09a4 [记事本] [Notepad] [Notepad.exe]
[2023-02-24 01:43:45.204] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10298 [] [ForegroundStaging] [explorer.exe]
[2023-02-24 01:43:45.229] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x1091e [任务切换] [XamlExplorerHostIslandWindow] [explorer.exe]
[2023-02-24 01:43:46.463] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x102ee [] [ForegroundStaging] [explorer.exe]
[2023-02-24 01:43:46.487] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x203d6 [Issues · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe]
[2023-02-24 01:43:46.489] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x1091e [任务切换] [XamlExplorerHostIslandWindow] [explorer.exe]
[2023-02-24 01:44:00.722] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2008c [PowerToys.PowerLauncher] [HwndWrapper[PowerToys.PowerLauncher;;1841e017-9624-41b4-9b1b-611c3a06c3cd]] [PowerToys.PowerLauncher.exe]
[2023-02-24 01:44:02.080] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x203d6 [Issues · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe]
[2023-02-24 01:44:02.972] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0xa0b76 [Clash for Windows] [Chrome_WidgetWin_1] [Clash for Windows.exe]
[2023-02-24 01:44:02.978] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0xa0b76 [Clash for Windows] [Chrome_WidgetWin_1] [Clash for Windows.exe] to monitor 0x10001
[2023-02-24 01:44:06.079] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x203d6 [Issues · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe]
[2023-02-24 01:44:14.961] [debug] [taskbarattributeworker.cpp:574] Removing normal window 0x203d6 [New Issue · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe] from monitor 0x10001
[2023-02-24 01:44:14.961] [debug] [taskbarattributeworker.cpp:566] Inserting maximised window 0x203d6 [New Issue · TranslucentTB/TranslucentTB 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe] to monitor 0x10001
[2023-02-24 01:44:17.815] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10298 [] [ForegroundStaging] [explorer.exe]
[2023-02-24 01:44:17.896] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x1091e [任务切换] [XamlExplorerHostIslandWindow] [explorer.exe]
```

**Comment by sylveon** [comment] 2023-02-24 02:11
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-24 02:11 UTC
Labels: bug
