### ISSUE TITLE
Windows 11 no blur option

### ISSUE THREAD

**Issue by daveo76** [TranslucentTB/TranslucentTB#533] opened 2022-02-20 03:42 UTC
Running Windows 11 21H2 Build 22000.527. I have no blur option. So it makes no difference with this running. Windows 11 already has transparent option. It the same for all. I was wanting the blur option
![TranslucentTB](https://user-images.githubusercontent.com/7221776/154827464-9371602f-9105-4f83-9bac-ef4567a4f937.jpg)

**Comment by sylveon** [comment] 2022-02-23 00:09
Duplicate of #405

**Closed as completed by sylveon** 2022-02-23 00:09 UTC
