### ISSUE TITLE
it doesn't work on win11 build 22572.201

### ISSUE THREAD

**Issue by littlewolffy** [TranslucentTB/TranslucentTB#555] opened 2022-03-17 07:37 UTC

**Comment by littlewolffy** [comment] 2022-03-17 07:54
![nimg ws 126](https://user-images.githubusercontent.com/101792533/158761625-4c977db7-62f2-42b0-a9ee-545455c5f2b5.jpg)
Microsoft did some tablet-optimized changes to taskbar, which makes TranslucentTB broken.
Enter "vivetool delconfig 26008830 2" via vivetool to bring back the old taskbar and you'll find TranslucentTB works again.

**Comment by RealGungan** [comment] 2022-03-17 07:54
I can confirm it

**Comment by Pentacene-cyou** [comment] 2022-03-17 15:49
Aye.

**Comment by sylveon** [comment] 2022-03-17 15:54
Duplicate of #537

**Closed as completed by sylveon** 2022-03-17 15:54 UTC
