### ISSUE TITLE
Dynamic Windowed Shows Blur on Main Monitor and Clear on Second Monitor While On Desktop

### ISSUE THREAD

**Issue by Byte11** [TranslucentTB/TranslucentTB#103] opened 2017-09-12 21:00 UTC
Sometime the dynamic windowed option shows blur on my main monitor and clear on my second monitor while both are on the desktop. This really ruins the dynamic windowed mode, which I think is a fantastic feature.

**Comment by sylveon** [comment] 2017-09-13 01:23
Duplicate of #78

**Closed by sylveon** 2017-09-13 01:23 UTC
