### ISSUE TITLE
[Bug]: Doesn't seem to change anything for me

### ISSUE THREAD

**Issue by KyodaiKen** [TranslucentTB/TranslucentTB#735] opened 2023-02-28 19:13 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install TransculentTB from the fresh Microsoft Store
Start it
Press continue

### Expected results

Taskbar becomes transculent.

### Actual results

Nothing changes, not even when changing around the settings. Only slight change happens when selecting "Opaque", it changes back to normal when selecting anything else.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

IMPORTANT INFO: Just installed the new Windows Update KB5022913
Exact Windows 11 build: 22621.1344
Windows Feature Experience Pack 1000.22639.1000.0

### Relevant log output

```shell
[2023-02-28 19:09:10.997] [debug] [taskbarattributeworker.cpp:1133] Resetting worker state
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0xd05e2 [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe] to monitor 0x10001
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x14c04ec [New Issue · TranslucentTB/TranslucentTB — Mozilla Firefox] [MozillaWindowClass] [firefox.exe] to monitor 0x10001
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x5054a [Character_Sheet_-_Bianca_Overhaul.png (PNG Image, 7577 × 3500 pixels) — Scaled (25%) — Mozilla Firefox] [MozillaWindowClass] [firefox.exe] to monitor 0x10001
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x30462 [Settings] [ApplicationFrameWindow] [ApplicationFrameHost.exe] to monitor 0x10001
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x10434 [#💬techtalk | Rawiioli - Discord] [Chrome_WidgetWin_1] [Discord.exe] to monitor 0x10003
[2023-02-28 19:09:11.015] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x706ae [Apps] [CabinetWClass] [explorer.exe] to monitor 0x10001
[2023-02-28 19:09:14.098] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:14.257] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:19.155] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:19.272] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:22.445] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:22.548] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:30.726] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:30.842] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:36.734] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:36.859] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:40.486] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:40.585] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:43.857] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:43.974] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:53.693] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30038 [] [Shell_TrayWnd] [explorer.exe]
[2023-02-28 19:09:53.791] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x210534 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-28 19:09:56.981] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x30794 [Visual Studio Code] [Chrome_WidgetWin_1] [Code.exe] to monitor 0x10001
[2023-02-28 19:09:56.983] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x30794 [Visual Studio Code] [Chrome_WidgetWin_1] [Code.exe]
```

**Comment by Kevnkkm** [comment] 2023-02-28 19:54
Exactly the same behaviour for me, I also just installed the latest update KB5022913

**Comment by sylveon** [comment] 2023-02-28 19:56
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-28 19:56 UTC
Labels: bug
