### ISSUE TITLE
[Bug]: Win11 22621.1413 Update made the clear and blur taskbar broke

### ISSUE THREAD

**Issue by xamnoterxz** [TranslucentTB/TranslucentTB#798] opened 2023-03-24 20:58 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

So i tried installing the app but to do it many people use 3rd party apps but when i tried it it gave me a compatibility error so i couldnt be able to install the app

### Expected results

i was expecting to open normal

### Actual results

The blur and clear taskbar didnt work

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

i use a good laptop so its not in software or hardware

**Comment by sylveon** [comment] 2023-03-24 21:00
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-24 21:00 UTC
Labels: bug
