### ISSUE TITLE
[Bug]:Windows Insider Priview  Version(22523) Invalidity

### ISSUE THREAD

**Issue by J-Ziheng** [TranslucentTB/TranslucentTB#742] opened 2023-03-01 18:07 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

- The app is satisfacted, but Windows 11 beta version 22623 is invalid and cannot be transparent. 

- Speculating that it may be a registry problem that controls the transparency of the taskbar, hoping that the author can fix the update. 

- Thanks again！

### Expected results

- Expect the software to adapt ！

- Many people are looking forward to the adaptation of the software. 

### Actual results

The app is satisfacted, but Windows 11 beta version 22523 is invalid and cannot be transparent. 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by Tech127x** [comment] 2023-03-01 18:44
Confirmed on 262938.  Please update asap!  Thank you!!

**Comment by sylveon** [comment] 2023-03-01 19:09
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-01 19:09 UTC
Labels: bug
