### ISSUE TITLE
Multi monitor exception

### ISSUE THREAD

**Issue by testjie** [TranslucentTB/TranslucentTB#221] opened 2018-11-27 11:02 UTC
Display exception when i switch to single monitor /double monitor 

1. when single monitor 。
![image](https://user-images.githubusercontent.com/23480729/49077365-0b08f800-f276-11e8-96a5-399b4645bf9b.png)

2. switch to double monitor , not work.
![image](https://user-images.githubusercontent.com/23480729/49077668-db0e2480-f276-11e8-8a8c-f0a2e29c0f95.png)

System Version：Win10 1809 
Software Version：
![image](https://user-images.githubusercontent.com/23480729/49077883-6b4c6980-f277-11e8-8bd1-0a63752ceb6b.png)

**Comment by beringtom** [comment] 2018-12-17 23:32
Confirm this issue, switching to another monitor using the Projector menu, requires a restart of TB to make it work.

**Comment by sylveon** [comment] 2018-12-19 18:46
Duplicate of #209

**Closed by sylveon** 2018-12-19 18:46 UTC
