### ISSUE TITLE
This app automatically change the taskbar to Opaque in power saving mode.

### ISSUE THREAD

**Issue by tylvn** [TranslucentTB/TranslucentTB#494] opened 2021-11-26 07:12 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Open power saving mode.
   2. Automatically adjusts the taskbar to Opaque.

 - Expected results: Nothing was happened.

 - Actual results: This app automatically adjusts the taskbar to Opaque.

 - Other: This app automatically adjusts the taskbar to Opaque in power saving mode, which causes me to be unable to use my computer in power saving mode.
<img width="1080" alt="TranslucentTB在节电模式的颜色Opaque" src="https://user-images.githubusercontent.com/95011132/143542048-b8fc13dd-5d69-4ac0-9adb-dae93652ac91.png">

**Comment by 5idereal** [comment] 2021-11-26 08:35
Duplicate of #459

**Comment by sylveon** [comment] 2021-11-26 15:16
Yeah, this is a bug I recently fixed. Next update will solve this. In the meanwhile, you can customize what it looks like power saving mode by using the tray icon.

**Closed as completed by sylveon** 2021-11-26 15:16 UTC
