### ISSUE TITLE
[Bug]: After installing Windows 11 22H2 Moment 2 update (version 22621.1344) TranslucentTB is no longer working

### ISSUE THREAD

**Issue by jeansagi** [TranslucentTB/TranslucentTB#744] opened 2023-03-02 00:13 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install Windows 11 22H2 Moment 2 update (version 22621.1344)

### Expected results

TranslucentTB should works as it usual

### Actual results

TranslucentTB no longer works.

The interface is launched and the icon trays works as usual.

But no matter what setting I choose or change the taskbar doesn't change.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

TranslucentTB no longer works.

The interface is launched, and the icon trays work as usual.

But no matter what setting I choose or change the taskbar does not change.

### Relevant log output

```shell
Windows 11 Pro version:

22H2 Moment 2 update (version 22621.1344)
Windows Feature Experience Pack 1000.22639.1000.0
OS language: Spanish - Mexico
```

**Comment by sylveon** [comment] 2023-03-02 00:19
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-02 00:19 UTC
Labels: bug
