### ISSUE TITLE
[Bug]:  TranslucentTB can't work on build 22623

### ISSUE THREAD

**Issue by Re-hd** [TranslucentTB/TranslucentTB#732] opened 2023-02-24 09:41 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

在Windows1122623版本上，TranslucentTB无法工作。
我知道可以通过降级到旧版任务栏来解决这个问题，但它与Windows11的风格完全不符，看着很膈应。
希望开发者告诉我这个问题能否解决。如果能，那什么时候能发更新？
谢谢。
操作系统版本 22623.1325
TranslucentTB does not work on Windows 1122623.
I know I can fix this by downgrading to an older version of the taskbar, but it doesn't match the style of Windows 11 at all, and it looks diabolical.
I hope the developer will tell me if this problem can be solved. If so, when will the update be released?
Thanks.
windows version 22623.1325

### Expected results

TranslucentTB正常工作。

### Actual results

无法工作，没有出现预期效果。

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by Gianlucas94** [comment] 2023-02-25 06:21
Is not working for me also. 
Build 22621.1343

**Comment by sylveon** [comment] 2023-02-25 08:13
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-25 08:13 UTC
Labels: bug
