### ISSUE TITLE
[Bug]: Clear mode not working after windows 11 update KB5022913 build 22621.1344

### ISSUE THREAD

**Issue by Akhil378** [TranslucentTB/TranslucentTB#756] opened 2023-03-04 09:42 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. Have installed the 2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913).

### Expected results

- Expected to see an clear style on the taskbar.

### Actual results

- The default windows taskbar style is present

![image](https://user-images.githubusercontent.com/69599947/222890468-dd87279d-64f6-4dfd-a9d2-0624b2e6fc1d.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

- I updated windows 11 this morning, the translucentTb was working as expected till then.
- The following updates were installed KB5022913. 
- Microsoft seems to have made changes to the taskbar, new animations and style, this might be what is causing the translucentTB styles not to have an effect.
- Steps I tried were to reinstall the app, didn't fix the issue.
- I tried other style modes as well and they also seem to be not working as expected. 
- **Re-tested after uninstalling the KB5022913 update and the app works as expected.**

**Comment by Miho1254** [comment] 2023-03-04 10:06
i have same issue with 22621.1344

**Comment by sylveon** [comment] 2023-03-04 10:07
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-04 10:07 UTC
Labels: bug
