### ISSUE TITLE
[Bug]: TranslucentTB Not Working After 03/2022 Update Windows 11

### ISSUE THREAD

**Issue by Reinokewt** [TranslucentTB/TranslucentTB#759] opened 2023-03-05 07:36 UTC
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After install new cumulative update 03/2022 on windows 11.transtb won`t work anymore.I try restart,reinstall and still not work.App still run but transparent effects never working
![image](https://user-images.githubusercontent.com/112705545/222948093-e24082ea-b406-452a-a2b6-79f9e0ab8024.png)

### Expected results

taskbar not transparent on any modes like clear or acrylic

### Actual results

traskbar need transparent like this  (picture take before update)
![Screenshot 2023-03-05 121422](https://user-images.githubusercontent.com/112705545/222948187-17a60481-636e-4084-8b44-6929e08270a0.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by wuyudelan** [comment] 2023-03-05 07:56
Got the same problem. 
Maybe because adding the search bar in this version.
22621.1344
Windows Feature Experience Pack 1000.22639.1000.0

**Comment by sylveon** [comment] 2023-03-05 08:26
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-05 08:26 UTC
Labels: bug
