### ISSUE TITLE
Win11 bug

### ISSUE THREAD

**Issue by Gronyan** [TranslucentTB/TranslucentTB#583] opened 2022-03-29 13:02 UTC
The Windows 11 taskbar has obscure horizontal line，please modif
![屏幕截图 2022-03-29 205910](https://user-images.githubusercontent.com/70813470/160617105-2cb477e1-4679-4422-b66c-ff72ec10899d.png)
y

**Comment by sylveon** [comment] 2022-03-29 16:39
Duplicate of #425

**Closed as completed by sylveon** 2022-03-29 16:39 UTC
