### ISSUE TITLE
TranslucentTB never opens at Clear

### ISSUE THREAD

**Issue by wapanap** [TranslucentTB/TranslucentTB#85] opened 2017-07-18 08:16 UTC
I set up Translucent to start with Windows at Clear. It always opens at Blur.

**Comment by ethanhs** [comment] 2017-07-18 15:40
Hi! sorry you are experiencing issues. How are you setting it to start clear?

**Comment by ChriscomIT** [comment] 2017-07-18 21:05
Hi same for me. Setting it via .cgf file. But whatever you set it will always be blurred after a reboot. When started after already booted it will be correctly set to clear.

**Comment by denosawr** [comment] 2017-07-19 00:07
I think this is a duplicate of #79. Feel free to reopen, if this is not.

**Closed by denosawr** 2017-07-19 00:07 UTC

**Comment by ChriscomIT** [comment] 2017-07-19 00:34
Yep, thanks for the hint.

**Comment by wapanap** [comment] 2017-07-19 17:16
I am setting it to start clear by ticking on the Clear memory item having started TranslucentTB and then hoping on a subsequent reboot it will start up again set to Clear, but it is always blurred. Is there any other way?

**Comment by wapanap** [comment] 2017-07-19 17:26
You say this is closed #85, but I have read this thread and am non the wiser as to what  I should do to set up TranslucentTB to always start Clear. I have noticed that if I set it to Clear, then exit TransslucentTB, then restart TranslucentTB without rebooting, it does open Clear. But on closing down the machine and then rebooting it opens Blurred again.

**Comment by charlesmilette** [comment] 2017-07-19 17:31
If you open the folder where TranslucentTB is stored, you should see a file named "config.cfg".

Open the Windows registry editor, go to `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. You should see an entry named TranslucentTB. Double-click on it to edit it and add ` --config C:\Path\to\where\TranslucentTB\is\stored\config.cfg`. Press OK, and reboot.

**Comment by denosawr** [comment] 2017-07-20 01:27
This is only a temporary solution, though. We're working on a better fix.

**Comment by wapanap** [comment] 2017-08-03 13:06
Finally got around to doing this and it didn’t work; TranslucentTB doesn’t open at all. I just added it to the existing entry with a space in between. Original entry was in quotes so I extended the quotes to the end of the new entry. What did I do wrong and there must be a way of making the program behave properly without resorting to this kind of complication.  If I don’t have it open at boot but open manually after booting up the configuration sticks and the program opens at ‘Clear’. When is the ‘better fix’ going to arrive?

**Comment by charlesmilette** [comment] 2017-08-03 14:57
You shouldn't have extended the quotes. Restore them where they where and
it will work.

**Comment by Spencer4134** [comment] 2018-05-27 00:31
I tried the "Temporary Solution", doesn't work. What DOES work, however, is to simply copy a shortcut to the .exe into your startup folder. Don't use the "Open at Boot" option.

Startup folder (Replace USERNAME with applicable user folder): C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by pyokorider** [comment] 2018-06-11 17:26
Spent 2 hours to find the solution and here's what I did to fix the issue eventually
-Create TranslucentTB.exe shortcut
-Win+R(Run)->shell:common startup and hit Enter
-Cut/copy the shortcut to the Startup folder
-Right-click the shortcut to open Properties
-In Target box, add  --clear to the end of the line (don't forget the blank). Like this
 "C:\Program Files\TranslucentTB\TranslucentTB.exe" --clear

**Comment by pyokorider** [comment] 2018-06-11 17:28
Spent 2 hours to find the solution and here's what I did to fix the issue eventually
-Disable Open at boot
-Create TranslucentTB.exe shortcut
-Win+R(Run)->shell:common startup and hit Enter
-Cut/copy the shortcut to the Startup folder
-Right-click the shortcut to open Properties
-In Target box, add --clear to the end of the line (don't forget the blank). Like this
"C:\Program Files\TranslucentTB\TranslucentTB.exe" --clear
