### ISSUE TITLE
Windows 11 Update Version 22H2, Taskbar Unhidable Line Issue

### ISSUE THREAD

**Issue by 7krai** [TranslucentTB/TranslucentTB#658] opened 2022-10-05 12:36 UTC
After the Windows 11 Updated to 22H2, the taskbar now has a visible line on top of it which TrunslucentTB can't hide anymore in "Clear" option.  [here is how it looks like](https://ibb.co/tpKZbzf)

**Comment by tomzappala** [comment] 2022-10-05 12:44
Same. Eager for a fix.

**Comment by sylveon** [comment] 2022-10-05 12:51
Duplicate of #425

**Closed as not planned by sylveon** 2022-10-05 12:51 UTC
