### ISSUE TITLE
New Version Doesn't Work When Start Menu Opened on W11

### ISSUE THREAD

**Issue by robertoleonardo** [TranslucentTB/TranslucentTB#411] opened 2021-09-01 08:26 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Translucent TB 21.1.0.0 [Windows 11 - 22000.168]

Every time i open the start menu, its as if Translucent TB is running. 
Once start menu closes, i have to resize a window before my TB goes clear again.
I've tried every permutation of settings i could think of - and edited the file directly - and still no luck.

I've tried resetting to default settings and all. Nothing works. 
![2021-09-01_01-25-35](https://user-images.githubusercontent.com/13153043/131638420-4ca56a1d-7a58-4567-b336-7e164e2523fa.png)
![2021-09-01_01-25-46](https://user-images.githubusercontent.com/13153043/131638425-aec9e057-6dbe-4045-9768-9b12aabdb419.png)

**Comment by VCStardust** [comment] 2021-09-01 08:39
After the upgrade in the Microsoft Store just now, Windows 10 (19043.1165) also has this problem, where it does not turn the taskbar fully transparent (aka. **Clear** in its option, I use this in all six settings) when opening the start menu.
And after closing the start menu and focusing on a maximized window, it still doesn't work. But it works between closing the start menu and clicking on the window.

**Comment by sylveon** [comment] 2021-09-01 10:49
The first case of not working on windows 11 is known - it doesn't detect the monitor start was opened on reliably. The second thing is some weird bug I thought was eliminated but seems to have creeped back.

**Comment by sylveon** [comment] 2021-09-01 13:16
I suspect this might be caused by VS 2022. I'll try reverting to VS 2019 this afternoon, and make another update with this build if it resolves issues.

**Comment by sylveon** [comment] 2021-09-01 20:41
Fixed by #413, update has been submitted to the store for approval.

**Closed as completed by sylveon** 2021-09-01 20:41 UTC

**Comment by sylveon** [comment] 2021-09-02 22:33
Fixed on 2021.4, the update is available in the store now.
