### ISSUE TITLE
FLASH when I switch from maximised window to desktop

### ISSUE THREAD

**Issue by vickychinghk** [TranslucentTB/TranslucentTB#297] opened 2020-04-14 02:07 UTC
**FLASH** when I switch from maximised window to desktop

a very short time (about 0.05 second ) flash of the theme color at the  taskbar

right after I get to the desktop (from window) (by using "windows+D" or aero peek)

sometime twice (0.05 second x 2) or more

**Comment by misaeldry** [comment] 2020-04-18 01:59
Hello!

I have the same problem. In my case, the taskbar flashes whenever I open the Start menu. It also happens after opening the start menu and clicking somewhere else.

**Comment by sylveon** [comment] 2020-04-18 02:09
This flash is caused by a transition between normal (or acrylic) and another style. The dev builds use another technique that makes this flash invisible or much less noticeable, but they're not in a pretty poor state otherwise.

**Comment by x10102** [comment] 2020-05-14 11:05
@sylveon Any idea when will this get fixed? I love the program otherwise but this is annoying the hell out of me.

**Comment by linpxzz** [comment] 2020-05-18 03:32
me too

**Comment by thvozdovic** [comment] 2020-06-08 14:11
Same here

**Comment by sylveon** [comment] 2020-06-08 21:10
Wish I had a timeframe. I'm hoping by the end of the year it will be ready.

**Comment by sylveon** [comment] 2021-09-02 22:39
This should be fixed in the latest update, available in the Store.

**Closed as completed by sylveon** 2021-09-02 22:39 UTC
