### ISSUE TITLE
After the Windows update this weeks, didn't work on Windows 11 22H2 (KB5022913)

### ISSUE THREAD

**Issue by songib** [TranslucentTB/TranslucentTB#779] opened 2023-03-10 10:55 UTC
### Please check for a duplicate first

- [ ] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update windows 11 and bork the app, idk and Win 11 got a few taskbar UI updates this week, which may be causing this app not to work. 

This update >> (https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9)

### Expected results

work normally before (KB5022913).

### Actual results

the app Didn't work after (KB5022913)

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by TremblingFool** [comment] 2023-03-10 12:56
Yes，I also had this bug

**Comment by MBrinks2239** [comment] 2023-03-10 15:06
I am also experiencing this bug

**Comment by LagBug** [comment] 2023-03-10 15:55
Same, just installed it today and it doesn't seem to work at all.

**Comment by kthecoder** [comment] 2023-03-10 16:26
Aw man, this was the coolest feature. I hate the taskbar color. I hope this is fixed soon.

**Comment by FortuneMidnight** [comment] 2023-03-10 16:57
same here

**Comment by sylveon** [comment] 2023-03-10 18:13
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-10 18:13 UTC
Labels: bug
