### ISSUE TITLE
[Bug]: The software no longer works after the cumulative update to Windows11 in 2023 03

### ISSUE THREAD

**Issue by KelaLeaf** [TranslucentTB/TranslucentTB#832] opened 2023-04-15 02:11 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

The Windows11 software fails after being updated to the latest version

### Expected results

Implement taskbar transparency

### Actual results

The taskbar only has ground glass effects

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Windows11 after March 2023 update and later，After this update, Windows Explorer seems to change this version, and much different from before
版本	Windows 11 专业工作站版
版本	22H2
安装日期	‎2023/‎4/‎14
操作系统版本	22621.1555
体验	Windows Feature Experience Pack 1000.22640.1000.0

### Relevant log output

```shell
[2023-04-15 02:08:25.484] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x40072 [] [Shell_TrayWnd] [explorer.exe]
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x103a8 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-04-15 02:08:25.494] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by sylveon** [comment] 2023-04-15 02:12
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-15 02:12 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:28
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

**Comment by KelaLeaf** [comment] 2023-05-03 09:46
> 

Thank you for your help. I have been using Start11 recently, but it is too ugly. ViveTool is a great tool, thank you again.

**Comment by KelaLeaf** [comment] 2023-05-03 09:48
> If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

Thank you for your help. I have been using Start11 recently, but it is too ugly. ViveTool is a great tool, thank you again.
