### ISSUE TITLE
Delay in start

### ISSUE THREAD

**Issue by masona99** [TranslucentTB/TranslucentTB#307] opened 2020-05-17 15:48 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 2020.1
 - Windows build number: 19041
 
Hello The program starts a few seconds later when Windows starts Is it possible to eliminate this time interval?

**Comment by sylveon** [comment] 2020-05-17 20:18
Duplicate of #135

**Closed as completed by sylveon** 2020-05-17 20:18 UTC
