### ISSUE TITLE
[Bug]: Unable to display normally in the Windows 22H2-22621.1344

### ISSUE THREAD

**Issue by amlei** [TranslucentTB/TranslucentTB#754] opened 2023-03-04 00:28 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

In recently,the Windows sended new's updata and I do it. Restarting, I detected TranslucentTB unable to display normally that no matter how I adjust the parameters. Sorry, maybe my english word and grammar using inappropriate and I try hard learning.

### Expected results

I hope TranslucentTB can adoptation the new Windows 22H2-22621.1344.

### Actual results

Accoding to the steps to reproduce the issue. In addition, you can to see necessary already setting. But it is undisplay.
![image](https://user-images.githubusercontent.com/98502145/222862256-10daf25a-10e8-4498-b454-673867b38d91.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by amlei** [comment] 2023-03-04 00:41
![image](https://user-images.githubusercontent.com/98502145/222861119-5be53263-dbb0-488e-aee2-084ba631ee62.png)
In addition, you can to see necessary  already setting. But it is undisplay.

**Comment by sylveon** [comment] 2023-03-04 01:45
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-04 01:45 UTC
Labels: bug
