### ISSUE TITLE
[FIX W11]: quick fix for Windows 11 issues

### ISSUE THREAD

**Issue by daniel-de-luca** [TranslucentTB/TranslucentTB#826] opened 2023-04-11 14:32 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

TB is not properly working on W11 after update.
This is a quick fix workaround.

### Expected results

TB should be working

### Actual results

it is not. 

### Windows version

Windows 11 

### Other details

WORKAROUND:

Download VIVE Tool https://github.com/thebookisclosed/ViVe/releases/ currently the version i'm using is [ViVeTool-v0.3.3.zip](https://github.com/thebookisclosed/ViVe/releases/download/v0.3.3/ViVeTool-v0.3.3.zip)

Create a new directory named " zVIVE " (no quotes) in C:

Extract the content of the downloaded file to " C:/zVIVE " (no quotes)

Open CMD as Administrator (Right Click)

Navigate to the dir: " cd C:\zVIVE " (no quotes)

Input: " vivetool /disable /id:26008830 "

A successfull message should show.

Now restart the machine.

Done.

**Comment by sylveon** [comment] 2023-04-11 20:22
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-11 20:22 UTC
Labels: bug
