### ISSUE TITLE
[Bug]: Latest Windows 11 update breaks all functionality

### ISSUE THREAD

**Issue by pat15312** [TranslucentTB/TranslucentTB#768] opened 2023-03-06 23:51 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Updated to:
2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913)
OS Build 22621.1344

This has broken all functionality. Literally none of TranslucentTB works now.

### Expected results

TranslucentTB to work, as it had been doing before the Windows update.

### Actual results

TranslucentTB is not working.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

This is a main line release of Windows 11, not a Windows Insider build.

### Relevant log output

```shell
[2023-03-06 23:43:18.052] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10089:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x20380 [] [Shell_TrayWnd] [explorer.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:708] 			0xc0e50 [New Issue · TranslucentTB/TranslucentTB - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:708] 			0x507b0 [Inbox - My.Name@email.co.uk - Outlook] [rctrl_renwnd32] [OUTLOOK.EXE]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:708] 			0x70826 [February 28, 2023—KB5022913 (OS Build 22621.1344) Preview - Microsoft Support - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1056] Monitor 0x20001:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x3037c [] [Shell_SecondaryTrayWnd] [explorer.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x103b2 [] [WorkerW] [explorer.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x50070 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-03-06 23:43:18.062] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by sylveon** [comment] 2023-03-07 00:03
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-07 00:03 UTC
Labels: bug

**Comment by abusayed0206** [comment] 2023-03-08 09:13
Same problem! not working! I use Lively along with TTB. I thought lively is doing this misfunction!
