### ISSUE TITLE
[Bug]: TranslucentTB is incompatible with Windows 11 22621.1344

### ISSUE THREAD

**Issue by fiqhimaulana** [TranslucentTB/TranslucentTB#765] opened 2023-03-06 08:07 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

[TranslucentTB is incompatible with Windows 11 22621.1344

### Expected results

compatible

### Actual results

incompatible

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-06 08:08
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-06 08:08 UTC
Labels: bug
