### ISSUE TITLE
[Bug]: TTB NOT FUNCTIONING AND NO FIX

### ISSUE THREAD

**Issue by iAlify** [TranslucentTB/TranslucentTB#799] opened 2023-03-24 23:03 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Turn on PC or maybe an update. 

### Expected results

The task bar to turn transparent. 

### Actual results

Only thing that works is a different shade of color. Nothing else. And yes, I have tried everything. Yes, I have done that too. 

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Maybe the new windows customizations. New transparency update too maybe. 

### Relevant log output

```shell
deleted all logs to clear out the cache to see if that would fix the issue.
```

**Comment by sylveon** [comment] 2023-03-24 23:05
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-24 23:05 UTC
Labels: bug
