### ISSUE TITLE
Still not working on win 11

### ISSUE THREAD

**Issue by Lestra13** [TranslucentTB/TranslucentTB#605] opened 2022-05-02 19:02 UTC
Updated to 22610.1 build, still the same issue clear taskbar mode does not work.

**Comment by sylveon** [comment] 2022-05-02 19:08
Duplicate of #537

**Closed as completed** 2022-05-02 19:08 UTC

**Comment by syauqihazimi** [comment] 2022-05-04 15:02
> Updated to 22610.1 build, still the same issue clear taskbar mode does not work.

it's true, same not working on me
