### ISSUE TITLE
[Bug]: Translucent TB is not working on Windows 11 Pro after 2023 - 03 update

### ISSUE THREAD

**Issue by FrosenMercure** [TranslucentTB/TranslucentTB#804] opened 2023-03-26 12:59 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I don't know if this is an issue or a bug, but it seems like most of win 11 pro users are having the same trouble with me after 2023 - 03 update, we can open the app, but all the functions inside are not working

### Expected results

Maybe you can update them if you have time

### Actual results

Thanks

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by Ruubke** [comment] 2023-03-26 13:20
Yeah same here, 
Trough i have Windows 11 Home Fully updated 
Here is a Log file:
`[2023-03-26 13:23:16.698] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x100da [] [Shell_TrayWnd] [explorer.exe]
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x304e2 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-03-26 13:23:16.700] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
`

**Comment by neochan1** [comment] 2023-03-26 14:56
I have the same problem.

**Comment by xbaoziplus** [comment] 2023-03-26 15:17
My friend had this problem before I updated the latest version, I thought it was sporadic, but I also encountered this problem after upgrading

**Comment by zp-86** [comment] 2023-03-26 15:49
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/537

**Closed as not planned** 2023-03-26 19:31 UTC
Labels: bug
