### ISSUE TITLE
Straight Line Across The TaskBar Windows 11

### ISSUE THREAD

**Issue by panagiwtisgewrgas** [TranslucentTB/TranslucentTB#623] opened 2022-07-20 18:34 UTC
I didn't use to have this specific issue back on Windows 10 as far as I remember. But since I upgraded to Windows 11 and installed the app from Microsoft Store, I am getting a white line across my entire taskbar. Any recommendation or workaround for this problem? 
![image](https://user-images.githubusercontent.com/109692402/180056662-fe6e7b86-6498-4092-ab62-24c8a9806a17.png)

**Comment by sylveon** [comment] 2022-07-20 19:06
Duplicate of #425

**Closed as not planned by sylveon** 2022-07-20 19:06 UTC
