### ISSUE TITLE
The "clear" mode isn't working.

### ISSUE THREAD

**Issue by MichaelWendrell** [TranslucentTB/TranslucentTB#666] opened 2022-10-13 21:15 UTC
[x
![imagem_2022-10-13_181536170](https://user-images.githubusercontent.com/74889070/195712141-543b738b-6214-4050-9178-197f26282313.png)
] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment] 2022-10-13 21:54
Duplicate of #537

**Closed as completed by sylveon** 2022-10-13 21:54 UTC

**Comment by MichaelWendrell** [comment] 2022-10-13 22:27
@sylveon my build's different. I'm wunning my Windows at build 22623.746 ver

**Comment by sylveon** [comment] 2022-10-13 22:28
It's the same issue, 22623 also has the new taskbar implementation.

**Comment by MichaelWendrell** [comment] 2022-10-13 22:30
Ah yes, I get it now! Thanks!
