### ISSUE TITLE
 The software does not work on 22571 Windows systems

### ISSUE THREAD

**Issue by jichuan254** [TranslucentTB/TranslucentTB#546] opened 2022-03-10 10:06 UTC
[yes] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: the latest in the Microsoft store

 - Steps to reproduce:
 After upgrading the latest dev preview version 22572.1 of windows11, I found that the software could not take effect correctly. No matter how I operated, including uninstalling and reinstalling the software, restarting the resource manager, restarting the computer, switching software options, etc., the taskbar could not become transparent. Although the software does open in the background at this time, it can't have any effect

 - When I set the option to clear, the taskbar should become completely transparent.

 - There is no change in the taskbar, which is still the same as the default state

 - Other: This is not the first time I have used the software, and the settings of the software have never changed since the first change. I guarantee that there is no problem with my operation. This is a bug of the software under the windows system of 22571 version

**Comment by chooky19** [comment] 2022-03-10 11:41
TB is totally broken now on Win 11 Dev v22H2 OS Build 22572.1. 
None of the options work at all now.
From event viewer:
Faulting application name: TranslucentTB.exe, version: 2021.5.0.0, time stamp: 0xbc80e78f
Faulting module name: ProgramLog.dll, version: 0.0.0.0, time stamp: 0xb8786f63
Exception code: 0xc0000409
Fault offset: 0x000000000001a611
Faulting process ID: 0x0x3020
Faulting application start time: 0x0x1D8345E92BC9E6C
Faulting application path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2021.5.0.0_x64__v826wp6bftszj\TranslucentTB.exe
Faulting module path: C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2021.5.0.0_x64__v826wp6bftszj\ProgramLog.dll
Report ID: d744fed4-3803-41ef-9e29-039e427d8221
Faulting package full name: 28017CharlesMilette.TranslucentTB_2021.5.0.0_x64__v826wp6bftszj
Faulting package-relative application ID: TranslucentTB

**Comment by sylveon** [comment] 2022-03-10 16:41
Duplicate of #537

**Closed as completed by sylveon** 2022-03-10 16:41 UTC
