### ISSUE TITLE
White line in windows 11 22H2

### ISSUE THREAD

**Issue by Zanoxxx** [TranslucentTB/TranslucentTB#648] opened 2022-09-25 18:53 UTC
![unknown](https://user-images.githubusercontent.com/102561837/192160330-697ce323-e48a-49ac-aaa0-7602af387697.png)

**Comment by sylveon** [comment] 2022-09-25 21:32
Duplicate of #425

**Closed as not planned by sylveon** 2022-09-25 21:32 UTC

**Comment by DexterzGretege** [comment] 2022-09-29 02:24
Just install RoundedTB from Windows Store and Under Advanced Options select TranslucentTb Compatibility. It should fix the issue. I had the same issue after updating to Win 11 Version 22H2 and after doing the above it was fixed instantly.
