### ISSUE TITLE
TranslucentTB not working after latest windows update

### ISSUE THREAD

**Issue by arkaprabhaP** [TranslucentTB/TranslucentTB#584] opened 2022-03-30 06:40 UTC
Hi, so I recently updated my laptop (Asus Vivobook K15) to version 22H2 , OS Build 22581.200 of windows 11. Ever since the update, Translucent TB was not working properly. I deleted it, restarted my machine and tried it again. All the other options like Acrylic, Opaque, Blur work except the Clear option, which I want for myself. 

Translucent TB version: 2021.5.0.0
Windows version: 22H2
OS Build: 22581.200

**Comment by sylveon** [comment] 2022-03-30 06:41
Duplicate of #537

**Closed as completed by sylveon** 2022-03-30 06:41 UTC
