### ISSUE TITLE
[Bug]:   Broken on Windows 11 After KB5022913 Installed

### ISSUE THREAD

**Issue by ajkochev** [TranslucentTB/TranslucentTB#767] opened 2023-03-06 21:58 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Windows 11 22H2 with 5022913 Installed and TranslucentTB installed.

### Expected results

TB should work as expected.

### Actual results

TTB was working correctly until 5022913 was installed.  I with all the changes the update made to the taskbar the app will need updated.  No changes to the taskbar are shown altering or enabling any setting in TTB.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I love this app.  It makes Windows look so much better with cool Taskbar affects.  I'm willing to collect and share any logs that might be helpful in updating the app.  Thank you to everyone for making this app great.

PS the Microsoft Store is getting a few reviews about this update causing the issue.

### Relevant log output

```shell
N/A
```

**Comment by nikcache** [comment] 2023-03-06 22:06
Glad to see someone opened this issue as a bug, would love a fix for this as well!

Edit: Wanted to mention that TB still works, but now Windows already has an effect present which is unaffected by TB. You can add colors using TB, but it's just laid on top of what windows has. Same thing with dark mode as well. I just want transparency :D

**Comment by sylveon** [comment] 2023-03-06 22:23
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-06 22:23 UTC
Labels: bug
