### ISSUE TITLE
Fix the dark line | Windows 11

### ISSUE THREAD

**Issue by vulGUN** [TranslucentTB/TranslucentTB#530] opened 2022-02-05 21:36 UTC
How can I remove the dark line on top of the taskbar in "clear" mode on windows 11?
I have not found a possible solution to this problem.

![Screenshot_2](https://user-images.githubusercontent.com/94137961/152659795-c151e851-b69f-48ac-ab7f-4bb6f9b6a426.jpg)

But this line disappears in the notification area.

![Screenshot_3](https://user-images.githubusercontent.com/94137961/152659977-ae4d1014-560d-476b-91d6-c96f0351a30e.jpg)

P.S.
I found a way to remove this line using the RoundedTV program. It is necessary to set a margin of 1 px and the line has disappeared.
Is it possible to add to the "clear" mode automatically removing 1 px from above, so as not to use a separate application for this?

**Comment by sylveon** [comment] 2022-02-06 22:12
Duplicate of #425

**Closed as completed by sylveon** 2022-02-06 22:12 UTC
