### ISSUE TITLE
[Bug]: Stopped working on Win11 Version 10.0.22621 Build 22621

### ISSUE THREAD

**Issue by icymaru** [TranslucentTB/TranslucentTB#786] opened 2023-03-14 09:32 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After upgrading to this version, TTB stopped working:
![image](https://user-images.githubusercontent.com/6220818/224957370-a5846a30-51dc-458d-8fb7-ffc8de8241e3.png)

### Expected results

It should work

### Actual results

Not working

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-14 10:25
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-14 10:25 UTC
Labels: bug
