### ISSUE TITLE
Doesn't work in win11 22581

### ISSUE THREAD

**Issue by Mamboing** [TranslucentTB/TranslucentTB#582] opened 2022-03-29 09:53 UTC
It doesn't work in win11 22581(beta version), maybe since microsoft uses new taskbar in this version.

**Comment by tlandman** [comment] 2022-03-29 10:39
I have the same issue. Seems like something changed indeed.

**Comment by tomwoerner** [comment] 2022-03-29 14:37
Same... in fact it never worked but im on this build

**Comment by sylveon** [comment] 2022-03-29 16:39
Duplicate of #537

**Closed as completed by sylveon** 2022-03-29 16:39 UTC
