### ISSUE TITLE
Taskbar icons not clear | Bug or Feature Request

### ISSUE THREAD

**Issue by tejasetty** [TranslucentTB/TranslucentTB#363] opened 2021-02-15 13:00 UTC
I have been generally setting up with automatic windows theme (day and night / Light and Dark),

System icons in task bar in Night mode (dark mode) is fine but Day mode its Not clear.

Could you please check if possible to change these icons to white Color or blackList icons to default mode?

During Day/Light Theme:
![Screenshot_1](https://user-images.githubusercontent.com/16817620/107949663-a4d63000-6fbb-11eb-97eb-8d9aa9582163.png)

During Night/Dark Theme:
![Screenshot_2](https://user-images.githubusercontent.com/16817620/107949666-a6075d00-6fbb-11eb-915c-54cc56c80db1.png)

**Comment by sylveon** [comment] 2021-02-19 09:20
There are two different theme settings:
- System, which affects the taskbar, start menu and action center
- Apps, which affects apps like Edge, settings, and other UWP apps.

Forcing only the icons to use light theme is not something I'm even sure can be done.

Instead, would it be possible to have whatever you use for the theme only change the app theme and keep the system theme as-is?

**Comment by tejasetty** [comment] 2021-02-25 10:57
Instead, would it be possible to have whatever you use for the theme only change the app theme and keep the system theme as-is?

--Ofcourse, this should fix my issue :)

**Comment by tejasetty** [comment] 2021-02-25 11:00
Instead, would it be possible to have whatever you use for the theme only change the app theme and keep the system theme as-is?

 -- I would like to change both  of the themes i.e. App as well as System theme :)

**Comment by sylveon** [comment] 2023-07-15 21:17
Duplicate of #41

**Closed as not planned by sylveon** 2023-07-15 21:17 UTC
