### ISSUE TITLE
After updating the new version, the settings cannot be opened in the tray icon

### ISSUE THREAD

**Issue by klora-sun** [TranslucentTB/TranslucentTB#686] opened 2022-12-01 03:18 UTC
After updating to the new version, I can't right-open the settings in the win11 tray icon.

**Comment by sylveon** [comment] 2022-12-01 03:25
What OS version are you running

**Comment by klora-sun** [comment] 2022-12-01 03:34
Hello，Charles,
Windows runs at version 22623.1020.and the app runs, And the running version of the software is the latest version in the Microsoft store.



从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Charles ***@***.***>
发送时间: 2022年12月1日 11:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [TranslucentTB/TranslucentTB] After updating the new version, the settings cannot be opened in the tray icon (Issue #686)


What OS version are you running

―

**Comment by klora-sun** [comment] 2022-12-01 03:35
Windows runs at version 22623.1020. And the running version of the software is the latest version in the Microsoft store.

**Comment by klora-sun** [comment] 2022-12-01 03:38
I also tried to install using the version of GitHub, but after installation, the tray icon existed, but I still couldn't use the right button to open the settings.

**Comment by sylveon** [comment] 2022-12-01 03:47
You are using Insider builds - this is a duplicate of #537

**Closed as not planned by sylveon** 2022-12-01 03:47 UTC
