### ISSUE TITLE
[Bug]: in windows11 22621.1344 version, all the features are not working

### ISSUE THREAD

**Issue by UnnamedDavid** [TranslucentTB/TranslucentTB#769] opened 2023-03-07 01:14 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

open the latest software in windows 22h2 22621.1344 version

### Expected results

the taskbar should be clear or blur or stuff like that

### Actual results

nothing happened but the software is working 

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

i used start 11 blur taskbar features, but i think i unstall it properly.

**Comment by sylveon** [comment] 2023-03-07 01:28
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-07 01:28 UTC
Labels: bug
