### ISSUE TITLE
Translucent Taskbar - Is there a way to eliminate the line that makes up the top of the taskbar regardless of which of the five settings is used??

### ISSUE THREAD

**Issue by lujon2** [TranslucentTB/TranslucentTB#630] opened 2022-08-14 19:07 UTC
[x
<img width="1919" alt="TaskbarLine" src="https://user-images.githubusercontent.com/111246140/184551251-699e0337-feac-4350-8112-c38d7221f39e.png">
<img width="1919" alt="TaskbarLine" src="https://user-images.githubusercontent.com/111246140/184551258-64746823-e15c-457c-ab6d-60ce0a44e390.png">
] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.
<img width="1919" alt="TaskbarLine" src="https://user-images.githubusercontent.com/111246140/184551306-66b51494-0808-4c7f-8449-36e45679cd9e.png">

**Comment by sylveon** [comment] 2022-08-14 19:32
Duplicate of #425

**Closed as completed by sylveon** 2022-08-14 19:32 UTC
