### ISSUE TITLE
Application closing when "windows" key is pressed.

### ISSUE THREAD

**Issue by GalexY727** [TranslucentTB/TranslucentTB#462] opened 2021-10-10 05:39 UTC
Whenever I launch TranslucentTB that being on startup or manually. It will only stay open until the windows key is pressed exclusively. Not when "Win+1" or "Win+R" is pressed, for example. It also closes when I click the Windows logo, opening the start menu.

Below is some extra information that happened today to maybe provide a helpful answer to what might be causing my issue above, but can be also 100% un-needed.
_///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////_
I am also getting a "Windows cannot find the specified device..." issue, but I was able to dodge that via just making another shortcut in the [Win+R] "shell:startup" folder. No changes were made to the application to cause this. (also I think the reason this "sub" issue is occurring is being the shortcut is invalid for the startup thing on windows, but that is not related to the main issue.

**Comment by sylveon** [comment] 2021-10-10 17:03
Is there any indication about a TTB crash in the [reliability history](https://www.tenforums.com/tutorials/75294-view-reliability-history-windows-10-a.html)?

**Comment by GalexY727** [comment] 2021-10-10 19:40
> Is there any indication about a TTB crash in the [reliability history](https://www.tenforums.com/tutorials/75294-view-reliability-history-windows-10-a.html)?

It only says "stopped working" in the summary, here is the full description:
////////////////////////////////////////////////////////////////////////////////////
Source
TranslucentTB

Summary
Stopped working

Date
‎10/‎10/‎2021 12:35 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\28017CharlesMilette.TranslucentTB_2021.5.0.0_x64__v826wp6bftszj\TranslucentTB.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	TranslucentTB.exe
Application Version:	2021.5.0.0
Application Timestamp:	bc80e78f
Fault Module Name:	combase.dll
Fault Module Version:	10.0.19041.1202
Fault Module Timestamp:	474f0ba7
Exception Code:	802b000a
Exception Offset:	00000000000862a6
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	0e92
Additional Information 2:	0e92a002f32562680d82b3758e265ea5
Additional Information 3:	e13f
Additional Information 4:	e13f4c00802c2a9cfcb7c4ec7bf8183f

Extra information about the problem
Bucket ID:	01637718c12a19f3150f04e330c1e759 (1517436973269247833)

![Capture](https://user-images.githubusercontent.com/65139378/136710759-4d50bb1b-d61a-4ecc-832d-e75ac3ebade0.PNG)

**Comment by sylveon** [comment] 2021-10-12 03:37
Can you capture a memory dump of this? To do so, run the following commands in an admin command prompt
```
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpFolder /d "C:\dumps"
reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpType /t REG_DWORD /d 2
```

Then reproduce the crash. There should be a .dmp file in `C:\dumps` now. You can then email it to me (charles.milette (at) gmail.com).

**Comment by sylveon** [comment] 2021-10-16 19:08
I got the dump and am looking at it.

So you're saying it happens when you press the Windows key? This is weird because in the memory dump I'm seeing a failure happen during initialization of the app, but that should already be done by this point.

**Comment by sylveon** [comment] 2021-10-16 19:56
Ok so the application actually crashes at startup, but the effect persists until you open the start menu because there isn't anything in explorer that resets the appearance to normal until start opens (and a few other things). That's why it feels like the app crashes only when you press the windows key.

Looking at the dump, it says it can't find a WinUI class, despite the package explicitly referencing WinUI as a dependency.

Can you open PowerShell, run `get-appxpackage`, and send the full output here?

**Comment by GalexY727** [comment] 2021-10-16 19:59
Yes, I don’t be home until later today, so I will be a bit

**Comment by GalexY727** [comment] 2021-10-17 07:54
[Packages.txt](https://github.com/TranslucentTB/TranslucentTB/files/7359038/Packages.txt)

**Comment by sylveon** [comment] 2021-10-23 03:32
Does this crash occur when you use the Windows Terminal app?

**Comment by sylveon** [comment] 2022-12-01 00:39
Closing since no feedback from the OP

**Closed as completed by sylveon** 2022-12-01 00:39 UTC

**Comment by GalexY727** [comment] 2022-12-02 06:59
My goodness this is old... so sorry about that
I use the [TaskbarX rainmeter skin](https://github.com/ChrisAnd1998/TaskbarX) now and it integrates all of the features of TranslucentTB. I think something was wrong with my computer because apps would just have a hard time auto-launching or similar. I assume the windows key thing that I was mentioning was Windows just not updating the taskbar until I hit the key or similar, unsure fully but it has been a while, sorry again for the inconvenience!
