### ISSUE TITLE
Line at the start of taskbar 

### ISSUE THREAD

**Issue by Varmolord** [TranslucentTB/TranslucentTB#620] opened 2022-07-10 22:52 UTC
Hello, Im currently using WIN 11 Pro 64bit version with display that has 2560 x 1440 resolution and Im getting this line at my "clear" taskbar. Does anybody know how to fix it or is it on purpose?

Thank you for the answer
VARMOLORD

![Screenshot 2022-07-11 005127](https://user-images.githubusercontent.com/53459216/178165084-bddd8612-1832-4bdc-a0a7-c15e9058cf4e.png)

**Comment by sylveon** [comment] 2022-07-10 22:54
Duplicate of #425

**Closed as not planned by sylveon** 2022-07-10 22:54 UTC
