### ISSUE TITLE
[Bug]: Hi, just updated windows 11 and the windows task bar isnt transparent anymore. Thank you for your time!

### ISSUE THREAD

**Issue by Woohoo420** [TranslucentTB/TranslucentTB#773] opened 2023-03-09 04:14 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just did my windows 11 updates and it happend.

### Expected results

That my task bar would stay transparent... xD

### Actual results

The task bar did not stay transparent.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Windows 11 Pro 22H2 Windows Feature Experience Pack 1000.22639.1000.0

**Comment by sylveon** [comment] 2023-03-09 04:14
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-09 04:14 UTC
Labels: bug
