### ISSUE TITLE
[Bug]: if i have a black wallpaper i cant see the text on the botmom of the taskbar because is black.

### ISSUE THREAD

**Issue by DJparzy315** [TranslucentTB/TranslucentTB#864] opened 2023-06-13 16:48 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

.

### Expected results

.

### Actual results

.

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

is there any way i can change the color of the text?

**Comment by sylveon** [comment] 2023-06-14 15:50
Set your system theme to dark so that the text turns white.

**Comment by sylveon** [comment] 2023-07-09 20:14
Duplicate of #41

**Closed as not planned by sylveon** 2023-07-09 20:14 UTC
Labels: bug
