### ISSUE TITLE
Problem with Windows 11 22H2 Insider version

### ISSUE THREAD

**Issue by Keymetal** [TranslucentTB/TranslucentTB#674] opened 2022-10-27 16:41 UTC
Hi!
Translucent doesn't work with Windows 11 22H2 Insider version.

My Windows 11 version is:

Edizione	Windows 11 Home
Versione	22H2
Build sistema operativo	22623.870
Esperienza	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by sylveon** [comment] 2022-10-27 16:42
Duplicate of #537

**Closed as not planned by sylveon** 2022-10-27 16:42 UTC
