### ISSUE TITLE
A static line present in the taskbar

### ISSUE THREAD

**Issue by sparsh-karna** [TranslucentTB/TranslucentTB#670] opened 2022-10-20 14:19 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

This problem started when I updated my windows from 2021H2 to 2022H2.

 - Version information: 2021.5.0

 - Steps to reproduce:
   1. Simply download and install Translucentb from git library.

 - Expected results: The taskbar should be fully transparent .

 - Actual results: The taskbar is transparent but with a white line on top of it.
![image](https://user-images.githubusercontent.com/78959094/196976430-6c3f23ae-2470-4b0b-8ae6-7a1fb7355a03.png)

**Comment by sylveon** [comment] 2022-10-20 14:27
Duplicate of #537

**Closed as not planned by sylveon** 2022-10-20 14:27 UTC
