### ISSUE TITLE
Windows 11 black line issue

### ISSUE THREAD

**Issue by NiklasVoigt** [TranslucentTB/TranslucentTB#510] opened 2021-12-24 15:30 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5.0.0

 - Steps to reproduce:
   1. Use Windows 11
   2. Fresh install from windows store
   3. Set all to clear

 - Expected results: It should be all clear.

 - Actual results: There is a black line 
 ![Screenshot 2021-12-24 162810](https://user-images.githubusercontent.com/18678779/147362220-a9098d86-9ab0-4acd-ac36-ff198097d6b9.png)
![Screenshot 2021-12-24 163417](https://user-images.githubusercontent.com/18678779/147362466-35f242e6-8c6a-407d-b1aa-08ee155ca965.png)

 - Other:

**Comment by sylveon** [comment] 2021-12-24 22:43
Duplicate of #425

**Closed as completed by sylveon** 2021-12-24 22:43 UTC
