### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Alper0506** [TranslucentTB/TranslucentTB#794] opened 2023-03-22 16:39 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

With the new windows 11 update, the TranslucentTB application has become COMPLETELY dysfunctional and a solution must be found urgently.

### Expected results

application to run

### Actual results

didn't work

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

With the new windows 11 update, the TranslucentTB application has become COMPLETELY dysfunctional and a solution must be found urgently.

**Comment by sylveon** [comment] 2023-03-22 16:40
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-22 16:40 UTC
Labels: bug
