### ISSUE TITLE
[Bug]: TranslucentTB doesn't work after installing Windows 11 Update KB5022913

### ISSUE THREAD

**Issue by PatZer0** [TranslucentTB/TranslucentTB#788] opened 2023-03-14 11:20 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1.Install Windows 11 Update pack KB5022913
2.Reboot
3.TranslucentTB doesn't work no matter how I change its settings.

### Expected results

Make it work on Windows 11 with KB5022913

### Actual results

TranslucentTB doesn't work no matter how I change its settings.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by EvianMcKeown** [comment] 2023-03-14 11:42
Duplicate of #537

**Comment by TEOACV** [comment] 2023-03-14 16:08
también me sucede lo mismo.

**Closed as not planned** 2023-03-14 19:47 UTC
Labels: bug
