### ISSUE TITLE
[Bug]: TranslucentTB is incompatible with Windows 11 22621.1413

### ISSUE THREAD

**Issue by adityapotadar07** [TranslucentTB/TranslucentTB#870] opened 2023-07-01 12:00 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install and make the taskbar clear

### Expected results

taskbar should be clear.

### Actual results

stays on acrylic. Opaque works though.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-07-01 16:08
Duplicate of #537

**Closed as not planned by sylveon** 2023-07-01 16:08 UTC
Labels: bug
