### ISSUE TITLE
Not working in the last windows build

### ISSUE THREAD

**Issue by obsessedlady** [TranslucentTB/TranslucentTB#564] opened 2022-03-24 02:43 UTC
TB not working in the last beta build of windows.

![image](https://user-images.githubusercontent.com/79773674/159831508-65dc5fb3-ebc5-4c8a-98bf-5078504491da.png)

**Comment by sylveon** [comment] 2022-03-24 02:43
Duplicate of #537

**Closed as completed by sylveon** 2022-03-24 02:43 UTC
