### ISSUE TITLE
Fluent is more opaque (darker) on Windows 11

### ISSUE THREAD

**Issue by chooky19** [TranslucentTB/TranslucentTB#403] opened 2021-07-13 06:42 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.00
 - Windows build number:  21H2 Build 22000.65
 - Steps to reproduce: Change Regular -> Accent Colour to Fluent
 - Expected results: Fluent have more transparency like in Win 10
 - Actual results: Fluent has less transparency & is darker.
 - Other: 
 - ![tb fluent](https://user-images.githubusercontent.com/51835591/125403310-be5b9680-e3f8-11eb-97ef-4148b7feced4.jpg)

**Comment by sylveon** [comment] 2021-07-14 04:44
Does it occur in [the latest dev build](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzE0MC9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)?

**Comment by chooky19** [comment] 2021-07-14 08:42
Yes it does.

**Comment by sylveon** [comment] 2021-09-02 22:35
I can reproduce the issue now. It seems to be a change on Microsoft's side unfortunately.

**Comment by ypurpl** [comment] 2021-09-24 17:05
can reproduce using clear. shows as black 
![image](https://user-images.githubusercontent.com/81705406/134713935-ccd26ae0-1715-4088-bab7-75ea87e3051e.png)

**Comment by sylveon** [comment] 2021-10-08 20:13
Fixed in 2021.5

**Closed as completed by sylveon** 2021-10-08 20:13 UTC
