### ISSUE TITLE
When switching between desktops with gestures, the "fluent design" is temporarily disabled

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#328] opened 2020-08-25 17:01 UTC
[X] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.
 - TranslucentTB version: Latest
 - Windows build number: OS Build 19041.450  (version 2004)
 - How to reproduce: set every option to "Fluent", "Enabled". Use a touchpad and switch between desktops through the use of gestures.
 - What's happening: when sliding to the next/previous desktop, the taskbar becomes clear instead of using the "fluent" blur. This happens until the desktop switch sliding animation ends. Once the animation ends, the taskbar "fluent" blur is restored.
*obs: this bug couldn't be reproduced when the taskbar location was set to top, left or right.
*obs2: transparency **is** enabled under windows settings
*obs3: when TranslucentTB is not running, this also happens with the default Window's taskbar blur
*obs4: a couple months ago, this issue was fixed through the use of "UseOLEDTaskbarTransparency". Which would not only apply a "fluent-like" blur effect, but would also entirely fix desktop transitions with the use of gestures. However, after a couple windows updates, this option no longer works (nor does said taskbar effect).
*obs5: when swapping between desktops with Ctrl+Winkey+Left/Right, using alt+tab, clicking on a taskbar icon/window name or using the "task view" window and clicking directly into another desktop or having a program swap to another virtual desktop to open something on another application, this issue does not occur.

**Comment by sylveon** [comment] 2020-08-25 17:03
Duplicate of #320

**Closed as not planned** 2023-07-09 20:05 UTC
