### ISSUE TITLE
Right click on system tray not working anymore 

### ISSUE THREAD

**Issue by srt54558** [TranslucentTB/TranslucentTB#695] opened 2022-12-04 16:33 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

By right clicking on the system tray nothing happens. The menu does not open.

### Expected results

The menu should open

### Actual results

Nothing 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

I updated to the newest insider build of window 11 pro.

**Comment by Staleyy** [comment] 2022-12-04 17:27
Happens to me too and has been going on for the last 2 days.

**Comment by sylveon** [comment] 2022-12-04 19:05
Duplicate of #537

**Closed as not planned by sylveon** 2022-12-04 19:05 UTC
Labels: bug
