### ISSUE TITLE
[Workaround]: For thoese who only want transparent taskbar, there's a mod on Windhawk can do that

### ISSUE THREAD

**Issue by iloxmn** [TranslucentTB/TranslucentTB#873] opened 2023-07-03 16:32 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Don't know if it's appropriate to post here but it's been a year since the new taskbar incompatible with this software. It's working greet so I just want to share it. 

### Expected results

Mod: Windows 11 Taskbar Styler
Install and go to Settings
Add a new item in Control styles
Target:
Rectangle#BackgroundFill
Styles:
Visibility=Collapsed

Add this to remove Taskbar border
Rectangle#BackgroundStroke
Fill=Transparent

### Actual results

![image](https://github.com/TranslucentTB/TranslucentTB/assets/22426402/b89cea7f-0d71-42d7-bf26-03ee91175fd0)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-07-03 16:58
Duplicate of #537

**Closed as not planned by sylveon** 2023-07-03 16:58 UTC
Labels: bug

**Comment by Muhammed-bin** [comment] 2024-08-28 09:42
When using Transluscent TB the taskbar is seemless with the wallpaper. Doing this make a thin line that really removes the immersion.
![TB](https://github.com/user-attachments/assets/2246d76f-e4f1-4207-a79b-d717d30dbe9e)
Any reccomendations or solutions on how to remove the line?

**Comment by iloxmn** [comment] 2024-08-28 09:55
Yes,  by using windhawk Taskbar styler. I don't remember the exact name, but you can use uwpspy to inspect the Taskbar, it's called padding line or something, and set it to transparent.

**Comment by iloxmn** [comment] 2024-08-28 09:55
> When using Transluscent TB the taskbar is seemless with the wallpaper. Doing this make a thin line that really removes the immersion.
> ![TB](https://github.com/user-attachments/assets/2246d76f-e4f1-4207-a79b-d717d30dbe9e)
> Any reccomendations or solutions on how to remove the line?

Yes,  by using windhawk Taskbar styler. I don't remember the exact name, but you can use uwpspy to inspect the Taskbar, it's called padding line or something, and set it to transparent.

**Comment by Muhammed-bin** [comment] 2024-08-28 12:51
Thank you. Really helped with the issue.

**Comment by MrKamilekPL** [comment] 2025-08-24 12:45
Massive Thank you! I don't have to use TranslucentTB and Windhawk at the same time anymore.
