### ISSUE TITLE
[Bug]: latest w11 update broke TTB but found a possible fix 

### ISSUE THREAD

**Issue by CitizenDroid** [TranslucentTB/TranslucentTB#761] opened 2023-03-05 22:37 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

update windows 11
But found a possible fix !! see below

### Expected results

TTB stops working

### Actual results

nothing happens 

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Hi I have w11 build 22621.1344 ni-release latest Release preview and TTB stopped working but on my travels found a fix on you tube here are the instructions:

download Vivetool GUI from github install it and open app
in the top left box where it says select build just select the first build it shows mine shows 25309 when selected vivetool starts loading all the files fast. once its done type inthe search box 26008830 that should highlight STTest now click on "Perform action" and select deactivate feature then it should say disabled next to STTest
close all windows and reboot 
TTB is now working however I've only just done this but saw some one report further down the comments that after a few reboots it lost ability again so he repeated it not sure if thats the case for every one but at lease we're closer to finding a fix!.
lets hope he was an odd one out LOL hope this helps all of us :)

**Comment by sylveon** [comment] 2023-03-05 23:05
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-05 23:05 UTC
Labels: bug
