### ISSUE TITLE
White line above taskbar on Windows 11 22H2

### ISSUE THREAD

**Issue by Princekin** [TranslucentTB/TranslucentTB#661] opened 2022-10-06 17:49 UTC
After updating to Windows 11 22H2 issue #425 is back.

![image](https://user-images.githubusercontent.com/70045520/194383415-048b12e4-915d-4547-ac7b-b098603e69a6.png)

**Comment by sylveon** [comment] 2022-10-06 18:25
The update with the fix to issue #425 has not been released yet, I'm hoping to release it as soon as possible but I'm being kept busy by my internship.

**Comment by mariosemes** [comment] 2022-10-09 17:57
Can confirm the issue.

**Comment by tushamanking** [comment] 2022-10-13 12:25
I found the white line, after I updated Windows 11 22H2

**Comment by Detektif4670** [comment] 2022-10-14 11:36
me too, is anyone able to help

**Comment by jonatino** [comment] 2022-10-18 00:27
> The update with the fix to issue #425 has not been released yet, I'm hoping to release it as soon as possible but I'm being kept busy by my internship.

Might be worth the time to setup CI building for easier future updates.

**Comment by sylveon** [comment] 2022-10-18 00:30
There is a CI, what's lacking is time for me to finish up a couple details in the code.

**Comment by Scoffbrrand** [comment] 2022-10-19 17:10
same issue. windows 11 22h2 moment update 1

**Comment by DhruvCx** [comment] 2022-10-21 01:57
had the same issue, found a temp fix by installing rounded tb to cut of the margins for taskbar.

**Comment by jonatino** [comment] 2022-10-21 02:34
Just download the latest artifact from https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=255&view=results which has the fix for whiteline. It fixed the line issue on win 11 22h2 for me

**Comment by edfus** [comment] 2022-10-27 08:49
> Just download the latest artifact from https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=255&view=results which has the fix for whiteline. It fixed the line issue on win 11 22h2 for me

For anyone else who can't download published artifacts from the webpage, here's the Azure DevOps REST API link:
https://dev.azure.com/sylve0n/TranslucentTB/_apis/build/builds/255/artifacts?artifactName=Portable%20x64%20Release&api-version=5.0

Unfortunately it did nothing for me tho.

**Comment by tushamanking** [comment] 2022-10-27 12:10
> Just download the latest artifact from https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=255&view=results which has the fix for whiteline. It fixed the line issue on win 11 22h2 for me

it's work !! thankyou so much

**Comment by Hellobrine** [comment] 2022-10-27 12:43
> > Just download the latest artifact from https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=255&view=results which has the fix for whiteline. It fixed the line issue on win 11 22h2 for me
> 
> For anyone else who can't download published artifacts from the webpage, here's the Azure DevOps REST API link: https://dev.azure.com/sylve0n/TranslucentTB/_apis/build/builds/255/artifacts?artifactName=Portable%20x64%20Release&api-version=5.0
> 
> Unfortunately it did nothing for me tho.

I just tried it and it didn't seem to work, but I found out that there's an option for this. Try turning on "Show taskbar line" it fixed the issue for me.

**Comment by edfus** [comment] 2022-10-27 14:09
> > > Just download the latest artifact from https://dev.azure.com/sylve0n/TranslucentTB/_build/results?buildId=255&view=results which has the fix for whiteline. It fixed the line issue on win 11 22h2 for me
> > 
> > 
> > For anyone else who can't download published artifacts from the webpage, here's the Azure DevOps REST API link: https://dev.azure.com/sylve0n/TranslucentTB/_apis/build/builds/255/artifacts?artifactName=Portable%20x64%20Release&api-version=5.0
> > Unfortunately it did nothing for me tho.
> 
> I just tried it and it didn't seem to work, but I found out that there's an option for this. Try turning on "Show taskbar line" it fixed the issue for me.

Appreciate the info but still no luck. Glad you got a fix for it!

**Comment by okibcn** [comment] 2022-10-28 04:55
I assume the new version will be soon in the MS App store, However, the direct links to the latest TranslucentTB development versions 2021.5.121 are here for the different platforms:
- [MSIX ARM64 installer](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzI1NS9hcnRpZmFjdE5hbWUvTVNJWCtBUk02NCtSZWxlYXNl0/content?format=zip)
- [MSIX x64 installer](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzI1NS9hcnRpZmFjdE5hbWUvTVNJWCt4NjQrUmVsZWFzZQ2/content?format=zip)
- [Portable ARM64](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzI1NS9hcnRpZmFjdE5hbWUvUG9ydGFibGUrQVJNNjQrUmVsZWFzZQ2/content?format=zip)
- [Portable x64](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzI1NS9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)

I confirm the problem is fixed in this release, at least the x64 portable I've tested. THere is an additional option to show the line. The default is off, so it is not shown anymore unless you decide to show it. Great!!!!

**Comment by noriellecruz** [comment] 2022-11-30 22:18
latest update was already released on ms app store

**Closed as completed** 2022-12-01 00:22 UTC
