### ISSUE TITLE
Outline on Taskbar Windows 11 ver. 22H2

### ISSUE THREAD

**Issue by danuganisp** [TranslucentTB/TranslucentTB#655] opened 2022-09-30 22:44 UTC
**There is an outline on taskbar now. Windows 11 latest version.
please fix it**

![image](https://user-images.githubusercontent.com/75341961/193366074-b98039d9-6ec6-47a8-945b-d47d78f97cef.png)

**Comment by sylveon** [comment] 2022-09-30 22:47
Duplicate of #425

**Closed as not planned by sylveon** 2022-09-30 22:47 UTC
