### ISSUE TITLE
[Bug]: Cannot access the settings from the tray.

### ISSUE THREAD

**Issue by Aatish-S** [TranslucentTB/TranslucentTB#684] opened 2022-11-28 12:24 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just installed this app on windows 11 Home. I got the welcome message and showed that I could either use the config file or change settings from the system tray. But everytime I click on the icon the whole tray dismisses itself and can't access the settings. Any workaround for this?
Windows Feature Experience Pack 1000.22637.1000.0

### Expected results

I tried installing an older version and that would let me access the system tray settings but the newer version doesn't do so.

### Actual results

The newer update will not let me access the settings.

https://user-images.githubusercontent.com/76836647/204276824-c812b999-37ea-4192-b44b-bff474dc34f7.mp4

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

![image](https://user-images.githubusercontent.com/76836647/204277181-32046678-c996-4919-b9c7-c297027bb864.png)

**Comment by InvictusDude** [comment] 2022-11-28 15:07
Same issue here with the current version from the Microsoft store.

Edition	Windows 11 Pro
Version	22H2
Betriebssystembuild	22623.891
Leistung	Windows Feature Experience Pack 1000.22637.1000.0

**Comment by sylveon** [comment] 2022-11-28 15:29
Duplicate of #537

**Closed as not planned by sylveon** 2022-11-28 15:29 UTC
Labels: bug
