### ISSUE TITLE
the "blur" option disappeared in win11

### ISSUE THREAD

**Issue by alt-0191** [TranslucentTB/TranslucentTB#490] opened 2021-11-18 23:50 UTC
![142514435-b0cf829d-49c7-49c9-99cd-c724eebbd27c](https://user-images.githubusercontent.com/56725325/142514579-fbc63a52-9f7a-4d06-8210-ad1cacfd35b8.png)
I notice that the "blur"effect is not at the list,but can use it by edit setting profile.

**Comment by sylveon** [comment] 2021-11-18 23:57
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/405

**Closed as completed by sylveon** 2021-11-18 23:57 UTC
