### ISSUE TITLE
Light border on Win 11

### ISSUE THREAD

**Issue by Snakzi** [TranslucentTB/TranslucentTB#456] opened 2021-10-08 09:12 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Hello,

I have downloaded the program and searched on google and here, but seems like I'm the only one having this issue?
There is a light border on my taskbar (over the icons), is there a way to deactivate it?

Screen: https://imgur.com/SR7ONmz

Best regards

**Comment by actualdankcoder** [comment] 2021-10-08 13:39
I have a similar situation but its a very thin black border(unnoticeable to the naked eye)
![image](https://user-images.githubusercontent.com/60839576/136567113-37e2300f-6819-48b7-a886-94fb248f029d.png)

**Comment by vigo113** [comment] 2021-10-08 14:53
I also have this bug, it is more visible on bright backgrounds 
https://i.imgur.com/mXeYa9L.png

**Comment by JackKillEveryday** [comment] 2021-10-08 15:00
I have the exact same issue, there is about a 1 pixel high line filled with black.

**Comment by Brandlovec** [comment] 2021-10-08 19:10
Same here.
![image](https://user-images.githubusercontent.com/92181123/136613005-8766e0d1-c6ac-48a8-88cf-37ca9107bf03.png)

**Comment by sylveon** [comment] 2021-10-08 19:12
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/425

This is not a bug of TranslucentTB, it's something built-in to Windows. It appears even when TTB isn't running, but is much more subtle. I'm looking into ways to get rid of this line.

**Closed as completed by sylveon** 2021-10-08 19:12 UTC
