### ISSUE TITLE
[FEATURE REQUEST] Adjust font colors in taskbar

### ISSUE THREAD

**Issue by Oman395** [TranslucentTB/TranslucentTB#497] opened 2021-11-27 00:09 UTC
[X] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

# Changing font color in taskbar
My wallpaper goes from purple to a light cyan, but I like having dark mode on all other things. If I want a passable dark mode on windows, I need to set all styles to dark-- but this sets the font color of the taskbar to white, which makes it hard to read.

50/50 I'm just being an idiot, but figured might as well post it here. No pressure obv, fairly minor feature request.

**Comment by ghost** [comment] 2022-04-20 04:52
I have something very similar issue. I'm using a white theme, but my wallpaper is dark.
So, by default the TB is whiteish as well but with BLACK text. If I use TranslucentTB with acrylic theme, I attached what you can see from the bottom right bar. Nearly nothing.

![image](https://user-images.githubusercontent.com/8837736/164152911-76ff022b-5c7a-4d2a-b136-2348f65001e1.png)

Would be a really great feature if we could modify the font color used there.

**Comment by akozyritskiy** [comment] 2022-10-05 23:44
Looks like this issue has been reported over 11 month ago and still not fixed?

This issue defeats the purpose for the clear transparency effects as:
1. Not every user is using dark mode in Windows.
2. Not every wallpapper has bright background.

**Comment by sylveon** [comment] 2022-10-05 23:45
If it was easy to fix it would have been already fixed. It's practically impossible to fix if you also want third party tray icons to adjust.

**Comment by akozyritskiy** [comment] 2022-10-05 23:52
I think the main issue was mentioned is related to font colours e.g. you can see in the screenshot above the time is barely readable. 

If you're able to fix the basic windows icons as well that would be great.

**Comment by ghost** [comment] 2022-10-11 07:25
As @akozyritskiy said, if some of the 3rd party icons are not well visible, that's not a big deal, fault of the software. But if the Windows-related DEFAULT font & icons (Eg. the Wifi icon) can't be seen, I think that's important.
For me, it was a breaking issue, so personally, I'm not using translucent only because of this.

**Comment by sylveon** [comment] 2023-07-15 21:18
Duplicate of #41

**Closed as not planned by sylveon** 2023-07-15 21:18 UTC

**Comment by foxdie987** [comment] 2023-12-27 17:11
> I have something very similar issue. I'm using a white theme, but my wallpaper is dark. So, by default the TB is whiteish as well but with BLACK text. If I use TranslucentTB with acrylic theme, I attached what you can see from the bottom right bar. Nearly nothing.
> 
> ![image](https://user-images.githubusercontent.com/8837736/164152911-76ff022b-5c7a-4d2a-b136-2348f65001e1.png)
> 
> Would be a really great feature if we could modify the font color used there.

In Setting -> Personalization -> Color
I select Mode as Custom, and Choose your default Windows mode as Dark, while Choose your default app mode as Light.
This will make the tray icon region have White text and keep apps continue to use White theme. As for now, this is a workaround.
(My system: Win 11 Home 23H2 build 22631.2861)
