### ISSUE TITLE
[Bug]: Does not work properly on dual monitors when taskbar is place on the side of the screen.

### ISSUE THREAD

**Issue by jfrgagnon** [TranslucentTB/TranslucentTB#814] opened 2023-04-04 15:21 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm using [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) to customize my Win11 explorer and [TranslucentTB](https://github.com/TranslucentTB/TranslucentTB) to make my taskbar completely transparent.

When I enable TranslucentTB, I can't see my opened apps in my second monitor taskbar. I tried many options, and the only way that I found to restore the apps tabs visibility is to use the "show taskbar border" Desktop option in TranslucentTB.

### Expected results

Should be able to see app tabs in the second monitor side placed taskbar even if the "show taskbar border" isn't enabled.

![ShowTaskbarBorder](https://user-images.githubusercontent.com/74669377/229840073-1605da80-f572-470e-b96b-451dc6f26166.png)

### Actual results

I only see the Windows button and the date&clock sections in the second monitor side placed taskbar.

![NoTaskbarBorder](https://user-images.githubusercontent.com/74669377/229840121-59604a9a-6b0a-4c3f-ae1d-61921f6ebab6.png)

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Win 11 Pro Insider Build 23424.ni_prerelease.230324-1354

**Comment by DEAN-Cherry** [comment] 2023-04-07 10:05
I have this problem too. The only solution is to toggle this on.
<img src="https://user-images.githubusercontent.com/76607677/230590869-f39b3e8f-0674-4c56-9428-1425a872e20e.png" width=50% height=50%>

And after this setting toggled, everything will be fine in my case.

<img src="https://user-images.githubusercontent.com/76607677/230589883-8783a3b6-f951-423c-b1b0-f99649aab94a.png" height=500px>


![图片](https://user-images.githubusercontent.com/76607677/230590096-dbc8ac6d-cbda-42e5-a339-de175a69553a.png)

---
And here is my system version
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022/‎11/‎29
OS build	22621.1485
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by ShayBox** [comment] 2023-05-15 11:44
Same here, it's been bugging me for months only when on desktop my icons would disappear, I had to enable the taskbar border toggle.

**Comment by sylveon** [comment] 2023-07-09 20:21
Duplicate of #702

**Closed as not planned by sylveon** 2023-07-09 20:21 UTC
Labels: bug
