### ISSUE TITLE
[Bug]: About the issue that Windows 11 Builds 22621.1344 cannot take effect

### ISSUE THREAD

**Issue by VanoraMoore** [TranslucentTB/TranslucentTB#737] opened 2023-03-01 04:09 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

The internal version of Moment2 updated by Microsoft today, 22621.1344, is currently invalid and cannot be used normally.

### Expected results

I hope it can be repaired and updated in time

### Actual results

This version is no longer available
(Thank you again for your production)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Version：Windows 11 Builds 22621.1344

**Comment by jok3rsgr1n** [comment] 2023-03-01 04:51
Same here sadly !

**Comment by dnxbice** [comment] 2023-03-01 05:31
的确是失效了

**Comment by sylveon** [comment] 2023-03-01 05:36
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-01 05:36 UTC
Labels: bug

**Comment by VanoraMoore** [comment] 2023-03-01 06:10
> Duplicate of #537

Is there a plan to repair it?

**Comment by sylveon** [comment] 2023-03-01 06:21
Yes

**Comment by VanoraMoore** [comment] 2023-03-01 06:29
> Yes

Thanks for your work
