### ISSUE TITLE
Latest Win 11 update has broken this app please fix I am so used to used to it being this way it's OCD levels of bothering me

### ISSUE THREAD

**Issue by joshthehappy** [TranslucentTB/TranslucentTB#569] opened 2022-03-24 18:12 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by joshthehappy** [comment] 2022-03-24 18:13
not sure what just posed in there but my title says it all - Microsoft broke it now you - but would like to have it back

**Comment by sylveon** [comment] 2022-03-24 18:17
Duplicate of #537

**Closed as completed** 2022-03-24 18:17 UTC
