### ISSUE TITLE
App bugged: doesn't change transparency and has only two functioning modes.

### ISSUE THREAD

**Issue by Aqua-Hellz** [TranslucentTB/TranslucentTB#574] opened 2022-03-26 09:13 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

Last night it was working fine, when I turned on my laptop today found the app broken. It wasnt making the taskbar transparent, all the modes other than opaque didnt do any changes to the taskbar. The transparency right now is very low (If there is any).

I have tried reinstalling the app, doesn't fix the issue. 

I had a major windows 11 update yesterday KB5007297. I have uninstalled the update to check if that fixes the issue, but it didnt.

Attached the screenshot.

![image](https://user-images.githubusercontent.com/43025047/160232874-7728c2f4-2cb2-4c84-a9d0-55f729adf1fe.png)

**Comment by animeshy2jj** [comment] 2022-03-26 09:20
Yeah same happened with me after the latest windows update , this app functionality has stopped working.
![image](https://user-images.githubusercontent.com/9849649/160233205-6220aace-c945-41e6-b9dd-e8c3fed8e320.png)

**Comment by Aqua-Hellz** [comment] 2022-03-26 09:24
You can count on windows to destroy perfectly running apps :)

**Comment by sylveon** [comment] 2022-03-26 16:13
Duplicate of #537

**Closed as completed by sylveon** 2022-03-26 16:13 UTC
