### ISSUE TITLE
[Bug]: Not working on Windows 11 Version 22H2 for x64-based Systems (KB5022913) 

### ISSUE THREAD

**Issue by Marsh03** [TranslucentTB/TranslucentTB#750] opened 2023-03-03 10:58 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

.

### Expected results

.

### Actual results

.

### Windows version
Windows 11 Home Single Language

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Not working on new win 11 version (KB5022913)

### Relevant log output

```shell
.
```

**Comment by sylveon** [comment] 2023-03-03 11:05
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-03 11:05 UTC
Labels: bug
