### ISSUE TITLE
How do I set it up so that at startup it's dynamic ws?

### ISSUE THREAD

**Issue by McBaws** [TranslucentTB/TranslucentTB#110] opened 2017-10-20 17:28 UTC
I've tried setting it up in config, but it's not working. 
Sidenote: Also, I have it set to accent = transparent, but when it's on at startup, it opens with blur on. Any way to fix this?

**Comment by sylveon** [comment] 2017-10-20 17:29
Duplicate of #79

**Closed by sylveon** 2017-10-20 17:29 UTC

**Comment by ethanhs** [comment] 2017-10-20 17:31
See https://github.com/TranslucentTB/TranslucentTB/issues/79#issuecomment-316569713
(Closing as a duplicate)
