### ISSUE TITLE
Invalidated on Win11!

### ISSUE THREAD

**Issue by 1191000814** [TranslucentTB/TranslucentTB#595] opened 2022-04-14 01:05 UTC
TranslucentTB is invalidated on the latest version of win11, The taskbar cannot be transparent or otherwise styled any more! So, has anyone solved it? Or I have to wait until the official fixes the bug?
please help me ~

**Comment by sylveon** [comment] 2022-04-14 01:28
Duplicate of #537

**Closed as completed by sylveon** 2022-04-14 01:28 UTC
