### ISSUE TITLE
Refresh Taskbar handles is gone. I need this for using multiple monitors

### ISSUE THREAD

**Issue by ChristerJohn007** [TranslucentTB/TranslucentTB#432] opened 2021-09-06 09:38 UTC
[X] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Version 5

 - Steps to reproduce:
   1. Activate Multi-window
   2. Refresh taskbar handles to fix the bug in the taskbar is gone

 - Expected results: The taskbar will match both monitor if Refresh taskbar handles is present

 - Actual results:  Only the other monitor is translucent/transparent while the other one isn't

Whenever I use multi-monitors, the current screen's taskbar resets to Window's Default, while the second monitor is translucent. This bug exists for a very long time now, and my temporary fix for it is the "refresh taskbar handles".
Now it is gone and now the two displays won't match

**Comment by sylveon** [comment] 2021-09-06 12:40
This should have been fixed in this update, and it works on my multi monitor setup even through various hot plugs. Do you have some shell customization software like DisplayFusion which could affect it? If you enable trace verbosity and plug in a monitor to reproduce the issue, what does the log look like?

**Comment by maozermao** [comment] 2021-09-07 19:27
I can confirm this happens on my multimonitor setup as well. Zero shell customization software on my side (unless WallpaperEngine counts)

"Whenever I use multi-monitors, the current screen's taskbar resets to Window's Default, while the second monitor is translucent. This bug exists for a very long time now, and my temporary fix for it is the "refresh taskbar handles".
Now it is gone and now the two displays won't match"


@ChristerJohn007 I use this option - Advanced -> Reset Dynamic state, and it works for me.

I can post a trace log here soon if I have the time so it can be looked at.

**Comment by sylveon** [comment] 2021-09-07 19:33
Yes, please post a trace log.

**Comment by maozermao** [comment] 2021-09-07 19:47
To begin, here are my workflow configurations:

**_Configuration 1_**: Monitor 1 (2560 x 1440@150), Monitor 2 (2560 x 1440@75), Monitor 3(Power Off, Not detected) 
**_Confguration 2_**: Monitor 1 (1920 x 1080@60), Monitor 3 (Cloned with Monitor 1, clone source is 1), Monitor 2 (Plugged in standby mode, disabled via Nvidia)

**_So I did a dynamic state reset and both taskbars are transparent operating as intended in Configuration 1.
I also took a dynamic state dump for further info:_**


2021-09-07 22:23:13.202] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:23:13.207] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c06 [Refresh Taskbar handles is gone. I need this for using multiple monitors · Issue #432 · TranslucentTB/TranslucentTB - Brave] [Chrome_WidgetWin_1] [brave.exe] to monitor 0x1b740e55
[2021-09-07 22:23:13.208] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x802ea [Task Manager] [TaskManagerWindow] [Taskmgr.exe] to monitor 0x1b740e55
[2021-09-07 22:23:13.208] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c0e [Code Geass: Lelouch of the Rebellion - Playback - Netflix - Brave] [Chrome_WidgetWin_1] [brave.exe] to monitor 0x10080bad
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:863] ===== Begin TaskbarAttributeWorker state dump =====
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:870] Monitor 0x10080bad [taskbar 0x100d2]:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:872]     Maximised windows:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:875]     Normal windows:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:585]         0x10c0e [Code Geass: Lelouch of the Rebellion - Playback - Netflix - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:870] Monitor 0x1b740e55 [taskbar 0xb0d80]:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:872]     Maximised windows:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:875]     Normal windows:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:585]         0x10c06 [Refresh Taskbar handles is gone. I need this for using multiple monitors · Issue #432 · TranslucentTB/TranslucentTB - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:585]         0x802ea [Task Manager] [TaskManagerWindow] [Taskmgr.exe]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:881] User is using Aero Peek: false
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:885] User is using Task View: false
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:895] Start menu is opened: false
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:906] Search is opened: false
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:911] Worker handles requests from hooks: true
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:915] Power saver is active: false
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:917] Taskbars currently using normal appearance:
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:591]     [none]
[2021-09-07 22:23:22.254] [off] [taskbarattributeworker.cpp:920] ===== End TaskbarAttributeWorker state dump =====

**_Switching from Configuration 1 to Configuration 2 and taking a dynamic state dump  - results: Taskbar is transparent and working as intended in Monitor 1, Monitor 3_**

[2021-09-07 22:23:37.109] [debug] [taskbarattributeworker.cpp:241] Monitor configuration change detected, refreshing...
[2021-09-07 22:23:37.109] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:23:37.208] [debug] [taskbarattributeworker.cpp:196] Work area change detected, refreshing...
[2021-09-07 22:23:37.208] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:23:37.273] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c06 [REDACTED] [brave.exe] to monitor 0x7e0851
[2021-09-07 22:23:37.603] [debug] [taskbarattributeworker.cpp:116] A taskbar got destroyed, refreshing...
[2021-09-07 22:23:37.603] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:23:37.616] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c06 [REDACTED] [Chrome_WidgetWin_1] [brave.exe] to monitor 0x7e0851
[2021-09-07 22:23:37.628] [info] [taskbarattributeworker.cpp:388] Failed to set window composition attribute (0x80070006: The handle is invalid.)
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:863] ===== Begin TaskbarAttributeWorker state dump =====
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:870] Monitor 0x7e0851 [taskbar 0x100d2]:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:872]     Maximised windows:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:875]     Normal windows:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:585]         {REDACTED}
macroId=53dabdf2-06ab-4600-af4c-e707e7278fac - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:870] Monitor 0x0 [taskbar 0xb0d80]:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:872]     Maximised windows:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:875]     Normal windows:
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:881] User is using Aero Peek: false
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:885] User is using Task View: false
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:895] Start menu is opened: false
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:906] Search is opened: false
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:911] Worker handles requests from hooks: true
[2021-09-07 22:23:51.991] [off] [taskbarattributeworker.cpp:915] Power saver is active: false
[2021-09-07 22:23:51.992] [off] [taskbarattributeworker.cpp:917] Taskbars currently using normal appearance:
[2021-09-07 22:23:51.992] [off] [taskbarattributeworker.cpp:591]     [none]
[2021-09-07 22:23:51.992] [off] [taskbarattributeworker.cpp:920] ===== End TaskbarAttributeWorker state dump =====

**_Switching back from Configuration 2 to Configuration 1: - Monitor 1 has default windows opaque taskbar (fault lies here), Monitor 2 has TranslucentTb transparent taskbar (still working)_**

[2021-09-07 22:24:11.824] [debug] [taskbarattributeworker.cpp:241] Monitor configuration change detected, refreshing...
[2021-09-07 22:24:11.824] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:24:11.915] [debug] [taskbarattributeworker.cpp:196] Work area change detected, refreshing...
[2021-09-07 22:24:11.915] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:24:11.929] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c0e [Code Geass: Lelouch of the Rebellion - Playback - Netflix - Brave] [Chrome_WidgetWin_1] [brave.exe] to monitor 0x776025b
[2021-09-07 22:24:12.378] [debug] [taskbarattributeworker.cpp:99] A taskbar got created, refreshing...
[2021-09-07 22:24:12.378] [debug] [taskbarattributeworker.cpp:925] Resetting worker state
[2021-09-07 22:24:12.411] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x10c0e [Code Geass: Lelouch of the Rebellion - Playback - Netflix - Brave] [Chrome_WidgetWin_1] [brave.exe] to monitor 0x776025b
[2021-09-07 22:24:12.426] [info] [taskbarattributeworker.cpp:357] Can't find peek button handle
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:863] ===== Begin TaskbarAttributeWorker state dump =====
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:870] Monitor 0x776025b [taskbar 0x190fd2]:
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:872]     Maximised windows:
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:591]         [none]
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:875]     Normal windows:
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:585]         0x10c0e [Code Geass: Lelouch of the Rebellion - Playback - Netflix - Brave] [Chrome_WidgetWin_1] [brave.exe]
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:881] User is using Aero Peek: false
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:885] User is using Task View: false
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:895] Start menu is opened: false
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:906] Search is opened: false
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:911] Worker handles requests from hooks: true
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:915] Power saver is active: false
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:917] Taskbars currently using normal appearance:
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:591]     [none]
[2021-09-07 22:24:26.513] [off] [taskbarattributeworker.cpp:920] ===== End TaskbarAttributeWorker state dump =====
[2021-09-07 22:24:34.428] [debug] [taskbarattributeworker.cpp:432] Inserting normal window 0x6009d2 [new 1 - Notepad++] [Notepad++] [notepad++.exe] to monitor 0x776025b

**Comment by maozermao** [comment] 2021-09-07 19:56
Tried a couple more times after resetting dynamic state and here's some more data; hope im not bombarding


EDIT: log dump linked here [REDACTED]

In my humble opinion a quick fix to this solution would be to reset dynamic state about 5 - 20 seconds after the monitor configuartion change detection event, and if there were a way to automate that and tweak the delay timing in the settings.json file, it would be super awesome

**Comment by ChristerJohn007** [comment] 2021-09-08 00:16
I tried resetting dynamic state few times and now I can't seem to replicate the problem anymore. Weird. But hey, at least it is fixed on my side. I don't know but when it happens again, I'll post my trace logs. Thanks

**Comment by kingfisherimperialist** [comment] 2021-09-19 09:39
Same issue, also wallpaperengine also present

**Comment by sylveon** [comment] 2022-12-01 00:41
The new update should help with this issue.

**Closed as completed by sylveon** 2022-12-01 00:41 UTC
