### ISSUE TITLE
dynamic-ws not working

### ISSUE THREAD

**Issue by PLyczkowski** [TranslucentTB/TranslucentTB#61] opened 2017-04-30 21:45 UTC
I guess you do it by creating a shortcut and and adding parameters to Target field? How to specify attributes to parameters though? And how to add dynamic states? 

Please provide examples.

**Comment by PLyczkowski** [comment] 2017-04-30 22:01
I tried with "C:\Users\PLyczkowski4\Desktop\TranslucentTB.2017.2\TranslucentTB.exe --dynamic-ws" set in shortcut's Target field. Doesn't work. Is this the correct way of setting the dynamic mode?

**Comment by charlesmilette** [comment] 2017-04-30 22:28
Parameters can either be entered with the command prompt, or via the "Target" field of a shortcut's properties. Why the shortcut failed is probably because there is already another instance of TranslucentTB running, the program only allows one instance. Close it before trying to open the shortcut.

Also sometimes dynamic mode keeps frozen on blurred because of a bug in ApplicationFrameHost.exe and doesn't takes in account virtual desktops.

**Comment by PLyczkowski** [comment] 2017-04-30 22:55
Ok, so I guess I was doing this correctly (I also kept one instance running at a time). Seems like the dynamic mode just doesn't work here.

**Comment by ethanhs** [comment] 2017-05-01 00:15
@PLyczkowski if it isn't working we'd like to figure out why. Could you give us what version of Windows 10 you are on? You can check by pressign <kbd>win</kbd> + <kbd>r</kbd> then entering "winver".
Mine says "Microsoft Windows Version 1703 OS Build 16179.1000".

**Comment by ethanhs** [comment] 2017-05-01 00:25
[If you could try this build I would appreciate it.](https://github.com/TranslucentTB/TranslucentTB/files/967120/TranslucentTB.zip)

**Comment by PLyczkowski** [comment] 2017-05-02 08:13
Ok, that works, but only on my right monitor. The left one gets a blurred taskbar correctly, but doesn't switch to transparent on window maximize (the right one does).

My windows version is:
![image](https://cloud.githubusercontent.com/assets/7307968/25609550/f1b8a6e0-2f1f-11e7-81ad-cdba538ebb38.png)

**Comment by denosawr** [comment] 2017-05-02 08:18
Interesting. I am on 1607 (stupid IT and Windows 10 Education), so I cannot test your behaviour.

**Comment by PLyczkowski** [comment] 2017-05-02 08:21
Also feature request for dynamic-ws - ability to set the maximized settings, for instance opaque with custom color instead of the current blurred.

**Comment by denosawr** [comment] 2017-05-02 08:22
Some information to reproduce your error would be nice; is your right monitor your primary one or is it your left? Also, what applications are open on the left?

**Comment by denosawr** [comment] 2017-05-02 08:23
Also earlier today I raised an issue for your request: https://github.com/TranslucentTB/TranslucentTB/issues/64.

**Comment by denosawr** [comment] 2017-05-02 08:31
So what apps are **currently** open on the left window? Some applications are known to screw up the detection thanks to the glory of Windows.

**Comment by PLyczkowski** [comment] 2017-05-02 08:58
Chrome, Visual Studio Code, Godot, Rescue Time, Steam, Rainmeter, Avast, Google Drive, OneDrive, Dropbox, Pushbullet, AudioSwitch, Plex Server, Nvidia GeForce Experience, Launchy, Cloudshot, ROCCAT Tyon, Slack.

**Comment by denosawr** [comment] 2017-05-02 09:00
Try moving those apps onto your right monitor, one at a time? Also try quitting Rainmeter, and if that doesn't work Launchy; both could possibly cause issues.

**Comment by denosawr** [comment] 2017-06-03 09:12
This issue has been inactive for 30 days, closing. Feel free to reopen if it still persists.

**Closed by denosawr** 2017-06-03 09:12 UTC
