### ISSUE TITLE
Dynamic Start just works once or just flickers

### ISSUE THREAD

**Issue by capstan1** [TranslucentTB/TranslucentTB#82] opened 2017-07-08 09:29 UTC
If I enabe Dynamic Start via System Tray Icon it's working just once or its even just flickering. Then it just stays transparent.

My config:
```
; Taskbar appearance: opaque, transparent, or blur (default).
accent=transparent
dynamic-ws=opaque
```

Also can I set dynamic-ws with a very very subtle transparency and blur (Like Windows does by default, about 0,95) to match the start menu?
![screenshot_1](https://user-images.githubusercontent.com/17147867/27984255-7e16e4e0-63d1-11e7-8c29-b97cfa7875d0.png)

**Comment by denosawr** [comment] 2017-07-13 02:25
First, I think the issue you are experiencing with the `dynamic-start` feature is because of Windows - try using _**the Windows button on your keyboard instead of the mouse**_ and report back if that issue still exists.

**Comment by denosawr** [comment] 2017-07-13 02:41
As for your second request, I think the closest you'll get is probably using `--blur --tint 0xc5000000`. It would be hard to replicate the acrylic of the Start Menu, but I set my background to white, got the colour of the Start Menu in that (assuming I have disabled the accent colour) and subtracted that from `FF`, to form my alpha value.

**Comment by userisro** [comment] 2017-07-15 05:28
> using the Windows button on your keyboard instead of the mouse

For me, this is the cause of the problem. After opening translucentTB, and pressing the start button, the `dynamic-start` works properly, but if I press the start button again to close the start menu, the feature stops working until I reopen the program. This only happens when I press on the button to *close* the start menu, and not when I press somewhere else to do so...

**Comment by ethanhs** [comment] 2017-07-15 06:43
@userisro thanks so much for the detailed bug report! It will be quite useful for fixing it.

**Comment by denosawr** [comment] 2017-07-15 07:02
Thanks! Anyway, this is a duplicate of #51, so please move all discussion of the start menu bug to there.

**Closed** 2017-07-15 07:16 UTC
