### ISSUE TITLE
[Bug]: The problem that the transparent work column does not work.

### ISSUE THREAD

**Issue by nuskjp** [TranslucentTB/TranslucentTB#771] opened 2023-03-08 06:37 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Hello, after I updated to Windows 11 22H2 (KB5022913), I found the problem that the transparent task bar was not working.

### Expected results

Transparency taskbar and more 

### Actual results

Transparency doesn't work.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Windows 11 22H2 (KB5022913)

**Comment by sylveon** [comment] 2023-03-08 07:18
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-08 07:18 UTC
Labels: bug
