### ISSUE TITLE
[Bug]: App no longer support Win11 version 22H2

### ISSUE THREAD

**Issue by Cyproximity** [TranslucentTB/TranslucentTB#813] opened 2023-04-04 04:35 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I just recently updated my PC to windows 11 version 22H2. it was working, before this recent update.

### Expected results

Thanks for the work on this beautiful app. it should work on the win11 with the latest updates.  hopefully, my logs helps you

### Actual results

the taskbar no longer shows the translucent background

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Windows 11 Pro 64-bit (build 22621) 

### Relevant log output

```shell
[2023-04-04 04:28:54.587] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:28:54.645] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:28:55.329] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:708] 			0x905f2 [New Issue · TranslucentTB/TranslucentTB - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:708] 			0xe044a [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:708] 			0x80400 [DirectX Diagnostic Tool] [#32770] [dxdiag.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-04-04 04:29:03.338] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:03.989] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:04.064] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:04.755] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:08.632] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0xb040c [Notepad] [Notepad] [Notepad.exe] to monitor 0x10001
[2023-04-04 04:29:08.638] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0xb040c [Notepad] [Notepad] [Notepad.exe]
[2023-04-04 04:29:23.341] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:23.382] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:24.138] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:28.019] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:28.100] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:28.822] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:708] 			0x905f2 [New Issue · TranslucentTB/TranslucentTB - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:708] 			0xe044a [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:708] 			0x80400 [DirectX Diagnostic Tool] [#32770] [dxdiag.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:708] 			0xb040c [Notepad] [Notepad] [Notepad.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-04-04 04:29:32.417] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:33.845] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0xb040c [Notepad] [Notepad] [Notepad.exe]
[2023-04-04 04:29:33.926] [debug] [taskbarattributeworker.cpp:574] Removing normal window 0xb040c [Notepad] [Notepad] [Notepad.exe] from monitor 0x10001
[2023-04-04 04:29:33.927] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0xe044a [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-04-04 04:29:34.590] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:34.645] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:36.032] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:36.230] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x130406 [Windows Shell Experience Host] [Windows.UI.Core.CoreWindow] [ShellExperienceHost.exe]
[2023-04-04 04:29:36.698] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:37.331] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:38.060] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:39.026] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:39.544] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:708] 			0x905f2 [New Issue · TranslucentTB/TranslucentTB - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:708] 			0xe044a [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:708] 			0x80400 [DirectX Diagnostic Tool] [#32770] [dxdiag.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-04-04 04:29:42.012] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
[2023-04-04 04:29:46.483] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x5002c [] [Shell_TrayWnd] [explorer.exe]
[2023-04-04 04:29:46.562] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x10586 [System tray overflow window.] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-04-04 04:29:47.222] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x2a052e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-04-04 04:29:49.872] [debug] [taskbarattributeworker.cpp:137] Changed foreground window to 0x12003a [Notepad] [Notepad] [Notepad.exe]
[2023-04-04 04:29:49.873] [debug] [taskbarattributeworker.cpp:566] Inserting normal window 0x12003a [Notepad] [Notepad] [Notepad.exe] to monitor 0x10001
```

**Comment by sylveon** [comment] 2023-04-04 06:02
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-04 06:02 UTC
Labels: bug
