### ISSUE TITLE
Taskmgr bug

### ISSUE THREAD

**Issue by wendelbartz** [TranslucentTB/TranslucentTB#194] opened 2018-08-24 07:26 UTC
When i open taskmgr, he use 100% of cpu when TranslucentTB is open. Why?

(sorry if my english is not correct, i'm   ##brazilian)

**Comment by Vixb1122** [comment] 2018-08-24 09:55
maybe , your issue is same as #173

**Comment by sylveon** [comment] 2018-08-24 15:36
Yes, duplicate of #173

**Closed by sylveon** 2018-08-24 15:36 UTC
