### ISSUE TITLE
[Bug]: TB在系统启动时报错

### ISSUE THREAD

**Issue by cs-xiyan** [TranslucentTB/TranslucentTB#899] opened 2023-07-21 01:47 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

<img width="228" alt="image" src="https://github.com/TranslucentTB/TranslucentTB/assets/42777375/b245ff2d-dbaf-4196-bef0-b4160179be70">

### Expected results

希望不再报错

### Actual results

保错弹窗

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

<img width="498" alt="image" src="https://github.com/TranslucentTB/TranslucentTB/assets/42777375/1ad51a7d-6f0e-4344-87fe-c628f681b22b">

**Comment by sylveon** [comment] 2023-07-21 08:32
Duplicate of #888

**Closed as not planned by sylveon** 2023-07-21 08:32 UTC
Labels: bug
