### ISSUE TITLE
win11 pro , Split Screen almost stop work

### ISSUE THREAD

**Issue by kdxiaoyi** [TranslucentTB/TranslucentTB#656] opened 2022-10-01 10:13 UTC
Settings: When windows maximize , taskbar should be normal like win-11's default

But when windows are split screen and maximize , it doesn't work like ↑

![A version of Chinese I ues](https://user-images.githubusercontent.com/96934144/193404381-b73657f0-816d-458e-a279-6f79e00953d1.png)

Should work like:
![It should work like this](https://user-images.githubusercontent.com/96934144/193404425-0a38e3d1-6f7b-4257-b231-a9cc5d61e2ca.png)

**Comment by sylveon** [comment] 2023-07-09 20:17
Duplicate of #116

**Closed as not planned by sylveon** 2023-07-09 20:17 UTC
