### ISSUE TITLE
[Bug]: Doesnt work anymore

### ISSUE THREAD

**Issue by Tetrax-10** [TranslucentTB/TranslucentTB#812] opened 2023-04-03 16:26 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just look at the taskbar

### Expected results

Clear taskbar

### Actual results

stock taskbar

![image](https://user-images.githubusercontent.com/75513645/229570283-596c17b0-d843-4828-adf2-22a78c4492a3.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Edition	Windows 11 Home
Version	22H2
Installed on	‎10/‎8/‎2022
OS build	22621.1485
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Comment by gaomigithub** [comment] 2023-04-03 16:47
same issue for a week age

**Comment by hexkraft** [comment] 2023-04-03 17:07
https://github.com/TranslucentTB/TranslucentTB/issues/537

**Comment by sylveon** [comment] 2023-04-03 18:19
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-03 18:19 UTC
Labels: bug
