### ISSUE TITLE
[Bug]: Since March Update, not working anymore

### ISSUE THREAD

**Issue by fresH229a** [TranslucentTB/TranslucentTB#815] opened 2023-04-06 10:21 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After installing Windows Version 22621.1485, the App stopped working :( 

### Expected results

Functional App :D 

### Actual results

No functionality of the App anymore

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-04-06 14:08
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-06 14:08 UTC
Labels: bug

**Comment by killereks** [comment] 2023-04-06 14:11
Has this been fixed?

**Comment by nisarg-78** [comment] 2023-04-06 14:16
> Has this been fixed?

https://github.com/TranslucentTB/TranslucentTB/issues/537#issuecomment-1491289377
it is been worked on

**Comment by WantedTab** [comment] 2023-05-03 09:32
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
