### ISSUE TITLE
win 11 Build 22572 breaks it.

### ISSUE THREAD

**Issue by mtbboy1993** [TranslucentTB/TranslucentTB#547] opened 2022-03-10 23:35 UTC
22572 breaks the functionality, but the build also fixed issue where selected colour would not show. so now I can have the colour I want.

**Comment by liukenny961** [comment] 2022-03-12 01:34
I have the some problem!

**Comment by sylveon** [comment] 2022-03-13 19:39
Duplicate of #537

**Closed as completed by sylveon** 2022-03-13 19:39 UTC
