### ISSUE TITLE
This isnt to big.. but its annoying to someone like me

### ISSUE THREAD

**Issue by rvwt** [TranslucentTB/TranslucentTB#479] opened 2021-10-29 19:50 UTC
I dont know if like.. this issue is too much to look into.. but sometimes its jsut annoying.. its on windows 11.. theres a small line that separates the wallpaper and taskbar even with transparent taskbar.. 
![image](https://user-images.githubusercontent.com/91895035/139493866-3acb3ea7-5623-4ed3-96ef-69a5af5e8926.png)

**Comment by rvwt** [comment] 2021-10-29 19:51
gonna have to click the image to see it..

**Comment by sylveon** [comment] 2021-10-29 19:59
Duplicate of #425

**Closed as completed by sylveon** 2021-10-29 19:59 UTC
