### ISSUE TITLE
[Feature Request]:  dynamic color of icon

### ISSUE THREAD

**Issue by yt6983138** [TranslucentTB/TranslucentTB#848] opened 2023-05-08 11:24 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Sooo i cant figure out how to submit out a issue without using template soo real feature request at other details

### Expected results

e

### Actual results

e

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Other details

I use this with few light-themed backgrounds  (also mixed with black-themed backgrounds), the problem is, sometimes the icon is very hard to see, pic below
![image](https://user-images.githubusercontent.com/83499886/236811305-cdbf96d8-38aa-4986-8bfa-761ebbe48163.png)

I've tried switch entire pc to light theme, but then my eyes hurts 💀

**Comment by sylveon** [comment] 2023-05-08 14:11
You can set the system theme to light separately from the app theme, and that should fix it.

**Comment by yt6983138** [comment] 2023-05-12 23:00
> You can set the system theme to light separately from the app theme, and that should fix it.

Sorry for late reply. I mentioned my backgrounds are black and light themed mixed together, so switch to light mode would just turn another few background unseeable.

Also, I want system ui black.

**Comment by yt6983138** [comment] 2023-05-12 23:01
Oops, clicked wrong.

**Comment by sylveon** [comment] 2023-07-09 20:15
Duplicate of #41

**Closed as not planned by sylveon** 2023-07-09 20:15 UTC
Labels: bug
