### ISSUE TITLE
Probllz

### ISSUE THREAD

**Issue by AbelPB12** [TranslucentTB/TranslucentTB#619] opened 2022-07-08 21:24 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Install and launch TranslucentTB from the Microsoft Store on Windows 11
   2. Set the desktop mode to "clear" and go to the desktop

 - Expected results: Having a clea
<img width="425" alt="Capture d’écran 2022-07-08 233653" src="https://user-images.githubusercontent.com/108957824/178073653-f13d5a80-f2a5-42e7-9572-44716f2be48b.png">
<img width="425" alt="Capture d’écran 2022-07-08 233653" src="https://user-images.githubusercontent.com/108957824/178073692-22dc1021-8c76-4941-844d-2e7eb0fee478.png">
r toolbar when I'm on the desktop.

 - Actual results: The toolbar isn't clear: there's actually a small line at the top of the toolbar going from one side to another.

 - Other: That never happened when I was on Windows 10.

**Comment by AbelPB12** [comment] 2022-07-08 21:44
I recently upgraded my pc from Windows 10 to 11 and there is a little line all along the top of the toolbar that is in "clear" mode on the desktop when I am on it. 
<img width="425" alt="Capture d’écran 2022-07-08 233653" src="https://user-images.githubusercontent.com/108957824/178074170-5146866b-c02e-4927-bf76-9ee44b952690.png">

**Comment by sylveon** [comment] 2022-07-09 02:21
Duplicate of #425

**Closed as not planned by sylveon** 2022-07-09 02:21 UTC
