### ISSUE TITLE
TranslucentTB version: 9.0.0.0 - Windows build num the propeber: 19042.685  - Steps to reproduce: Switching my main monitor between HDMI 1 and DP causes translucent to disable on my primary monitor.  - Expected results: Task bar always stays translucent <!-- What should happen --> As said - Actual results: As said, the bar often goes back to normal meaning I always have to re open the app. 

### ISSUE THREAD

**Issue by Lukey115** [TranslucentTB/TranslucentTB#346] opened 2020-12-15 17:34 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by mgrddsj** [comment] 2020-12-17 09:40
Duplicate of #308 
I also have this problem. Hope they are fixing it soon.

**Comment by sylveon** [comment] 2021-09-02 22:36
This should be fixed in the latest update, available in the Store.

**Closed as completed by sylveon** 2021-09-02 22:36 UTC
