### ISSUE TITLE
[Bug]: Windows 11 Cumulative Update Messes Up TranslucentTB

### ISSUE THREAD

**Issue by Sussy-OS** [TranslucentTB/TranslucentTB#780] opened 2023-03-11 14:41 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update to latest cumulative update for Windows 11, run TranslucentTB. 

### Expected results

Runs normally, as should.

### Actual results

The TranslucentTB spawns above the actual taskbar. See Image(s): 
![image](https://user-images.githubusercontent.com/98842253/224490722-a1692b3e-92ae-4126-99dc-040d702d354f.png)
![image](https://user-images.githubusercontent.com/98842253/224490730-e4ee4abf-a500-4ec6-91f2-786ed220afb8.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

WinVer: 
![image](https://user-images.githubusercontent.com/98842253/224490771-c6320b64-6d5a-4592-af30-6f9680f64425.png)

**Comment by sylveon** [comment] 2023-03-11 15:01
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-11 15:01 UTC
Labels: bug
