### ISSUE TITLE
No Clear, Acrylic etc

### ISSUE THREAD

**Issue by arcooke** [TranslucentTB/TranslucentTB#560] opened 2022-03-19 22:20 UTC
I am on the latest TranlucentTB release (updated today 19/3/2022) and my current W11 release is:

W11 Pro, Evaluation copy.Build 22579.ni_release.220315-1501

I have no alternative taskbar option other than Normal it seems.  I have uninstalled/reinstalled and tried everything I can think of to enable Clear/Acrylic etc.  No success.

I use RoundedTB in conjunction and have tried Translucent with and without Rounded and I have uninstalled/reinstalled RoundedTB as well.  I simply cannot get the mentioned options to work.

Perhaps I am missing something but if I have I am not sure what it might be.

Cheers

Alan

**Comment by sylveon** [comment] 2022-03-19 22:24
Duplicate of #537

**Closed as completed by sylveon** 2022-03-19 22:24 UTC
