### ISSUE TITLE
[Bug]: it stops working to clear the taskbar after windowns 11 update

### ISSUE THREAD

**Issue by zualteaxd** [TranslucentTB/TranslucentTB#807] opened 2023-03-27 14:38 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

it works just fine and after win11 update my taskbar is not clear anymore

### Expected results

fixing the bug with just one update

### Actual results

z

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Other details

idk but i want my taskbar clear bro

### Relevant log output

```shell
z
```

**Comment by sylveon** [comment] 2023-03-27 18:11
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-27 18:11 UTC
Labels: bug
