### ISSUE TITLE
Battery saver option still doing the changes even when turned Off

### ISSUE THREAD

**Issue by noenic** [TranslucentTB/TranslucentTB#673] opened 2022-10-23 19:00 UTC
[x]  I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue. similar to #459 

It looks like the Battery Saver toggle doesn't actually do anything (it will stay activated)

 - Version information: 2021.5

 - Steps to reproduce:
   1. Put the computer in power saver mode
   2. watch

 - Expected results :
The toggle is turned Off and the accent is "clear", 
The taskbar shouldn't update to clear when the power saving mode is turned on

 - Actual results: 
 The toggle is turned Off and the accent is "clear" the taskbar updates to clear when power saving mode is turned on

 - Other: changing the Accent from clear to acrylic will change the taskbar to acrylic so i guess the problem is the toggle

I am on Windows 11 22H2

Here is the json config : 
```json
{
    "$schema": "https://sylveon.dev/TranslucentTB/schema",
    "desktop_appearance": {
        "accent": "clear",
        "color": "#353C3F0A",
        "show_peek": true
    },
    "visible_window_appearance": {
        "enabled": false,
        "accent": "clear",
        "color": "#00000000",
        "show_peek": true
    },
    "maximized_window_appearance": {
        "enabled": true,
        "accent": "acrylic",
        "color": "#353C3F0A",
        "show_peek": true
    },
    "start_opened_appearance": {
        "enabled": true,
        "accent": "acrylic",
        "color": "#00000000",
        "show_peek": true
    },
    "search_opened_appearance": {
        "enabled": false,
        "accent": "normal",
        "color": "#00000000",
        "show_peek": true
    },
    "task_view_opened_appearance": {
        "enabled": true,
        "accent": "acrylic",
        "color": "#353C3F0A",
        "show_peek": true
    },
    "battery_saver_appearance": {
        "enabled": false,
        "accent": "clear",
        "color": "#00000000",
        "show_peek": true
    },
    "ignored_windows": {
        "window_class": [],
        "window_title": [],
        "process_name": []
    },
    "hide_tray": false,
    "disable_saving": false,
    "verbosity": "warn"
}
````

If it's suppose to work like that, is there a way to ignore the battery saver and just keep it clear on desktop and acrylic onwindow maximized

thanks

**Comment by sylveon** [comment] 2022-10-23 19:04
Duplicate of #459, will be fixed next update

**Closed as not planned by sylveon** 2022-10-23 19:04 UTC
