### ISSUE TITLE
[Bug]: It no longer works in the latest version of windows 11

### ISSUE THREAD

**Issue by renlucana** [TranslucentTB/TranslucentTB#760] opened 2023-03-05 18:06 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Almost all customization options have no effect including transparency with the latest Windows 11 March update

### Expected results

Maybe a correction is necessary

### Actual results

Currently it does not work in any of the modes that the application has

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by ghost** [comment] 2023-03-05 19:31
Same here

**Comment by sylveon** [comment] 2023-03-05 19:53
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-05 19:53 UTC
Labels: bug
