### ISSUE TITLE
Black bar above the taskbar

### ISSUE THREAD

**Issue by panacea911** [TranslucentTB/TranslucentTB#551] opened 2022-03-13 17:56 UTC
Very annoying with a white desktop background.
![Screenshot_1](https://user-images.githubusercontent.com/90102210/158072651-ce0d6ea3-912b-4b32-a883-491115923653.png)

**Comment by sylveon** [comment] 2022-03-13 19:27
Duplicate of #425

**Closed as completed by sylveon** 2022-03-13 19:27 UTC
