### ISSUE TITLE
[Bug]: The icons and words in the bar are black and blend into the background.

### ISSUE THREAD

**Issue by changxin111** [TranslucentTB/TranslucentTB#887] opened 2023-07-13 12:57 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. I updated the latest version in the Microsoft Store.
2. I changed it to a dark background.
3. I found that the icons and words in the status bar had become transparent and were no longer visible in the background.

### Expected results

With a dark background, icons and words can be distinguished from the background.

### Actual results

![image](https://github.com/TranslucentTB/TranslucentTB/assets/51196618/9b87cd0a-3a60-49b3-8c61-168dd0fec306)
![image](https://github.com/TranslucentTB/TranslucentTB/assets/51196618/14757158-b9f1-4702-b455-8a9fc5088e7c)

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-07-20 02:49
Duplicate of #41

**Closed as not planned by sylveon** 2023-07-20 02:49 UTC
Labels: bug

**Comment by changxin111** [comment] 2023-07-21 11:33
Thank you for your help. My problem has been solved.

设置--个性化--颜色--选择模式改成深色，状态栏的图标和字都会变成白色。
