### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by msiraczor** [TranslucentTB/TranslucentTB#763] opened 2023-03-06 00:48 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After new windows update, only colours can be assigned to the taskbar. Can't be opaque, transparent etc.

### Expected results

To be able choose every option except colour.

### Actual results

It only can enable colour and it can't enable clear option.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-06 00:48
Duplicate of #537

**Closed as completed by sylveon** 2023-03-06 00:48 UTC
Labels: bug
