### ISSUE TITLE
[Bug]: i cant use it

### ISSUE THREAD

**Issue by Colese** [TranslucentTB/TranslucentTB#859] opened 2023-05-31 05:25 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

i cant use it it not working why??

### Expected results

i cant use it it not working why??

### Actual results

i cant use it it not working why??

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

i cant use it it not working why??

### Relevant log output

```shell
i cant use it it not working why??
```

**Comment by sylveon** [comment] 2023-05-31 05:40
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-31 05:40 UTC
Labels: bug
