### ISSUE TITLE
[Bug]: Win11-22H2 (Sep 2022 release) TTB activates but changes to TB 

### ISSUE THREAD

**Issue by bradleysavoy** [TranslucentTB/TranslucentTB#708] opened 2022-12-26 00:54 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Downloaded TranslucentTB - it's launching and showing as running but no settings seem to work no matter what I try (restarts, theme changes,, etc.)  I haven't done anything with regedit so figured this might be a bug based on the newest release?

### Expected results

TB to be translucent when enabled

### Actual results

No change

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

![image](https://user-images.githubusercontent.com/48191466/209486795-9a3508c4-e10d-4a09-a85b-a277b1b0bc46.png)

**Comment by sylveon** [comment] 2022-12-26 00:54
Duplicate of #537

**Closed as not planned by sylveon** 2022-12-26 00:54 UTC
Labels: bug
