### ISSUE TITLE
TranslucetTb 

### ISSUE THREAD

**Issue by Marcossant59** [TranslucentTB/TranslucentTB#587] opened 2022-03-31 23:47 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment] 2022-03-31 23:48
What

**Comment by Marcossant59** [comment] 2022-03-31 23:49
Program is not working with the latest version of windows v.22581.10.

**Comment by sylveon** [comment] 2022-03-31 23:49
Duplicate of #537

**Closed as completed by sylveon** 2022-03-31 23:49 UTC
