### ISSUE TITLE
[Bug]: Translucent is not working after update the newest windows 11 update

### ISSUE THREAD

**Issue by Koncek123** [TranslucentTB/TranslucentTB#774] opened 2023-03-09 04:37 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. this sofware can't make taskbar transparant 
2. I've tried restarting but it didn't work

### Expected results

This program can be fix in the next update

### Actual results

![Documentation](https://user-images.githubusercontent.com/103942622/223917876-6aaa08be-49db-4b77-9e6e-cceb30264123.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Translucent version: 2022.1

**Comment by sylveon** [comment] 2023-03-09 04:39
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-09 04:39 UTC
Labels: bug
