### ISSUE TITLE
Start Menu issue with new TB update and Win 11

### ISSUE THREAD

**Issue by bitkbs** [TranslucentTB/TranslucentTB#418] opened 2021-09-02 07:35 UTC
Received a new TranslucentTB update on my Win 11 machine today. Start Menu open is set to clear but opens as normal.

**Comment by sylveon** [comment] 2021-09-02 10:22
Duplicate of #415

**Closed as completed by sylveon** 2021-09-02 10:22 UTC

**Comment by sylveon** [comment] 2021-09-02 22:33
Fixed on 2021.4, the update is available in the store now.
