### ISSUE TITLE
Start opened trigger doesn't work on Win11

### ISSUE THREAD

**Issue by 42willow** [TranslucentTB/TranslucentTB#553] opened 2022-03-16 07:44 UTC
✅ I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

When you start translucent TB the "Start opened" isn't triggered when the Windows 11 start menu is opened.
 - Version information: Installed via MS Store

 - Steps to reproduce:
   1. Change the start opened trigger to work with windows 11.

 - Expected results: Start opened is triggered when the start menu is opened in windows 11.

 - Actual results: "Start opened" doesn't trigger when the start menu is opened in windows 11, like I just said...

 - Other: The Windows icon is also outdated..
<img width="253" alt="image" src="https://user-images.githubusercontent.com/70784752/158540809-ee044a0d-2459-46b2-9ccf-2c6fa316a056.png">

**Comment by sylveon** [comment] 2022-03-16 15:42
Duplicate of #483

**Closed as completed by sylveon** 2022-03-16 15:42 UTC
