### ISSUE TITLE
[Bug]: No longer works after recent windows 11 update 22H2

### ISSUE THREAD

**Issue by Demoss66** [TranslucentTB/TranslucentTB#802] opened 2023-03-26 04:37 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

after the most recent windows 11 update under 22H2 KB5023706 the TB program no longer makes my task bar clear like before no matter what I have tried.

### Expected results

thought uninstall and reinstall would work clearing data, among a couple other things like changing many settings, with no changes what so ever till I roll back the update which my system just forced the update again so I can't and shouldn't, have to keep rolling back updates to make a program function, great program love what it does and wish it still did.

### Actual results

Task bar looks exactly as it normally ewould without program installed.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Windows 11 updates 22H2 KB5023706 OS Build 22621.1413

**Comment by sylveon** [comment] 2023-03-26 04:37
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-26 04:37 UTC
Labels: bug
