### ISSUE TITLE
Translucenttb app not working with windows 11

### ISSUE THREAD

**Issue by KillerWolf1805** [TranslucentTB/TranslucentTB#588] opened 2022-04-01 06:10 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Windows 11 22581.200   -  app version 2021.5.0.0 
 the problem is that the app is not woking right with windows 11 
 
   1. when ever i click on the desktop option and select "clear" it goes into blur, and when i click on blur it just turns black
   2. With the maximised option is the same thing

**Comment by sylveon** [comment] 2022-04-01 07:04
Duplicate of #537

**Closed as completed** 2022-04-01 07:04 UTC
