### ISSUE TITLE
[Bug]: Has the invalidity in win11 not been fixed yet? I need him so much!

### ISSUE THREAD

**Issue by Uoki-im** [TranslucentTB/TranslucentTB#855] opened 2023-05-23 09:06 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Has the invalidity in win11 not been fixed yet? I need him so much!

### Expected results

Has the invalidity in win11 not been fixed yet? I need him so much!

### Actual results

Has the invalidity in win11 not been fixed yet? I need him so much!

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-05-23 09:17
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-23 09:17 UTC
Labels: bug
