### ISSUE TITLE
White Line at the bottom of the screen, if firefox in fullscreen

### ISSUE THREAD

**Issue by Aaron987BTW** [TranslucentTB/TranslucentTB#609] opened 2022-05-26 16:24 UTC
I noticed that, when firefox is in fullscreen, there is a white line at the bottom of the screen, which doesn't appear if TranslucentTB is closed.

 - TranslucentTB Version information: Newest version
 - Windows 11
 - Firefox 100.0.2 (64-Bit)

 - Steps to reproduce:
   1. Have "automaticlly hide taskbar" enabled
   2. Open TranslucentTB (with every setting on clear)
   3. Open Firefox in fullscreen
   4. Taskbar hides automatically 

-Results
  - Expected results: Taskbar hidden and Firefox in fullscren

  - Actual results: Firefox in fullscreen, Taskbar hidden, but a white line appears at the bottom

-My TranslucentTB settings: [settings.txt](https://github.com/TranslucentTB/TranslucentTB/files/8780482/settings.txt)

-Other: There is no other program, that is messing with the Taskbar

**Comment by sylveon** [comment] 2022-07-03 20:21
Duplicate of #425

**Closed as completed by sylveon** 2022-07-03 20:21 UTC
