### ISSUE TITLE
Software doesn't work in Windows 11

### ISSUE THREAD

**Issue by Super12138** [TranslucentTB/TranslucentTB#585] opened 2022-03-30 09:17 UTC
In Windows 11, although the Clear property is set, the taskbar color is still acrylic. (As shown below)
![image](https://user-images.githubusercontent.com/86954101/160796556-da3d34fd-02ac-43fd-9c5a-556a0bda2f31.png)

**Comment by AuraElicase** [comment] 2022-03-30 09:59
I have the same problem when I updated to windows 11 22H2 Windows Feature Experience Pack 1000.22581.100.0

**Comment by DrLadaa** [comment] 2022-03-30 14:47
I have the same problem and i did try to download it again and it didnt work.

**Comment by sylveon** [comment] 2022-03-30 15:04
Duplicate of #537

**Closed as completed by sylveon** 2022-03-30 15:04 UTC
