### ISSUE TITLE
Windows 11, Translucent can't change(affect) taskbar when I open the Start..

### ISSUE THREAD

**Issue by pauciloquento** [TranslucentTB/TranslucentTB#421] opened 2021-09-02 16:06 UTC
Yo, everyone, I have just installed clean windows 11 (reset) and I downloaded my favorite app too, I thought everything works very well as it used to  but somehow when I click at start TranslucentTB app doesn't change it or affect it at all, it just shows my normal theme color, I currently use Windows 11 and I downloaded the app from Microsoft Store 

![image](https://user-images.githubusercontent.com/89993890/131878006-21923d6a-57b8-42f7-8df5-9c77f4ddc45d.png)

And after I close the start, I need to open another window to make the taskbar clear again.

Is there any option to fix this issue?

**Comment by sylveon** [comment] 2021-09-02 16:08
Duplicate of #415

**Comment by sylveon** [comment] 2021-09-02 22:32
Fixed on 2021.4, the update is available in the store now.

**Closed as completed by sylveon** 2021-09-02 22:32 UTC
