### ISSUE TITLE
Unfortunately no longer works since the update 22623.1095

### ISSUE THREAD

**Issue by JaTiTV** [TranslucentTB/TranslucentTB#712] opened 2023-01-06 06:51 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Since the update 22623.1095 it unfortunately does not work m

### Expected results

Since the update 22623.1095 it unfortunately does not work m

### Actual results

Since the update 22623.1095 it unfortunately does not work m

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

Edition	Windows 11 Pro
Version	22H2
Installiert am	‎29.‎11.‎2022
Betriebssystembuild	22623.1095
Leistung	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by sylveon** [comment] 2023-01-06 07:04
Duplicate of #537

**Closed as completed by sylveon** 2023-01-06 07:04 UTC
Labels: bug
