### ISSUE TITLE
[Bug]: The Clear option doesn't work after the latest windows 11 update.

### ISSUE THREAD

**Issue by phyil** [TranslucentTB/TranslucentTB#822] opened 2023-04-09 21:57 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I updated windows 11 (KB5023706) a couple weeks ago, and since then, have not been able to utilize the Clear option for the taskbar. Honestly it's actually all of the other options too such as Acrylic, Opaque, etc.

### Expected results

Taskbar should be clear when selected.

### Actual results

The normal Windows taskbar is shown instead.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-04-09 21:57
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-09 21:57 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:31
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
