### ISSUE TITLE
[Bug]: TranslucentTB Fatal Error - 0x80070003

### ISSUE THREAD

**Issue by Venus642** [TranslucentTB/TranslucentTB#958] opened 2023-12-04 09:21 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

![error](https://github.com/TranslucentTB/TranslucentTB/assets/72867951/b1bc0f6e-f05e-405f-a4cd-57e8b3ca79c3)

### Expected results

I updated under Windows 2023.1 to 2023.2 with "TranslucentTB-portable-x64.zip"
and get this error message when windows starts: 
Failed to copy ExplorerHooks.dll
0x80070003: The system cannot find the specified path.

### Actual results

Where is the entry ExplorerHooks.dll made?
As soon as Windows starts, the error message appears. How can the problem be fixed? The previous version ran fine.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-12-04 09:52
The file gets copied to the temporary folder. Does yours exist?

**Comment by Venus642** [comment] 2023-12-04 11:06
No, the file is not copied to the temporary folder when Windows starts.
Folder TranslucentTB is created but the files
"ExplorerHooks.dll" and "ExplorerTAP.dll" are only created when you start the program manually.
[critical] [loadabledll.cpp:51] Failed to copy ExplorerHooks.dll (0x80070003: Das System kann den angegebenen Pfad nicht finden.)

When you create a batch under
... \AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
with copy the files to tmp folder that doesn't work
because the error window error message comes first.

**Comment by sylveon** [comment] 2023-12-04 22:50
You extracted the entire ZIP file that TTB comes in, right?

**Comment by Venus642** [comment] 2023-12-05 03:49
Yes.
![extracted](https://github.com/TranslucentTB/TranslucentTB/assets/72867951/1bd1ed9d-3c84-4056-a26a-2b8ad793cd79)

**Comment by QianMoXi** [comment] 2023-12-17 04:04
I'm having the same issue
![image](https://github.com/TranslucentTB/TranslucentTB/assets/26250460/4a7d3649-64f4-4454-bbc8-3987d2818bba)

**Comment by Venus642** [comment] 2023-12-17 04:30
It's a 2023.2 problem. Downgrade to 2023.1 and you have not the problem more..

**Comment by QianMoXi** [comment] 2023-12-17 04:47
> It's a 2023.2 problem. Downgrade to 2023.1 and you have not the problem more..

@Venus642  Yes, I've rolled back to 2023.1

@sylveon I know the problem is https://github.com/TranslucentTB/TranslucentTB/blob/0f9ba88d8b08ee329857850c319d3eb92354ac2d/TranslucentTB/loadabledll.cpp#L41

The folder `%temp%/TranslucentTB` does not necessarily exist on the computer, so the API should be called first to create it.
But I don't know how to fix it because I'm not a C++ programmer.

**Comment by sylveon** [comment] 2023-12-17 06:40
Good catch. Creating that directory should work as a workaround. The fix is relatively easy.

**Comment by Venus642** [comment] 2023-12-17 08:34
No. Creating the directory in the tmp directory and inserting the two .dll doesn't help. Especially not if the tmp directory is on a RAM drive. It only works properly with 2023.1

**Comment by QianMoXi** [comment] 2023-12-17 08:56
> When you create a batch under
> ... \AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
> with copy the files to tmp folder that doesn't work
> because the error window error message comes first.

Are you copying files using this method? Creating a startup item in the Startup folder does not guarantee that it will run before TranslucentTB starts (Windows Task Scheduler may be possible). This is different from directly creating a folder in the program.

**Comment by Overryde113** [comment] 2024-01-05 22:32
I'm having the same exact problem and would love to know what the problem might be and how to fix it

**Comment by Sure-Will** [comment] 2024-01-14 15:54
how to roll back to 2023.1

**Comment by sylveon** [comment] 2024-03-05 00:47
Fixed in 2024.1

**Closed as completed by sylveon** 2024-03-05 00:47 UTC
Labels: bug

**Comment by latiao48** [comment] 2024-03-15 09:11
<img width="524" alt="image" src="https://github.com/TranslucentTB/TranslucentTB/assets/47521776/cabdb694-f534-46a3-855b-48bdd5a61af4">
using version 2024.1, is it a same problem?

**Comment by lzmxff521** [comment] 2024-03-18 01:34
> Fixed in 2024.1

Excuse me，The problem exists in 2024.1

System: Windows 10 Enterprise Edition  22H2
