### ISSUE TITLE
[Bug]: Does not work on latest version of Windows

### ISSUE THREAD

**Issue by oonqt** [TranslucentTB/TranslucentTB#838] opened 2023-04-21 17:42 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Dude, just read the reviews on the app store. It's been going on for almost a month and your reviews are littered with complaints about the app completely not working.

### Expected results

Taskbar to be transparent.

### Actual results

Taskbar is not transparent.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-04-21 18:20
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-21 18:20 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:25
It's strange that if it doesn't work normally, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

For those looking for a fix, here is your fix. :))
