### ISSUE TITLE
Suggestion | Option to apply our settings to start menu as well

### ISSUE THREAD

**Issue by anilcduran** [TranslucentTB/TranslucentTB#311] opened 2020-05-29 00:44 UTC
I'd love to see my taskbar appearance match with the start menu. I know that this project focuses on taskbar but it would be nice to have a choice to apply settings to start menu as well.

Thanks

**Comment by sylveon** [comment] 2020-07-01 02:33
Duplicate of #46

**Closed as completed by sylveon** 2020-07-01 02:33 UTC
