### ISSUE TITLE
[Bug]: cannot working on newest windows 11 update

### ISSUE THREAD

**Issue by xhanfx** [TranslucentTB/TranslucentTB#811] opened 2023-03-30 00:46 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

cannot working on newest windows 11 update

### Expected results

cannot working on newest windows 11 update

### Actual results

cannot working on newest windows 11 update

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5023706)

### Relevant log output

```shell
cannot working on newest windows 11 update
```

**Comment by sylveon** [comment] 2023-03-30 01:11
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-30 01:11 UTC
Labels: bug
