### ISSUE TITLE
选择开机自启后为何开机后不是之前选择的透明而是模糊

### ISSUE THREAD

**Issue by uc1255085** [TranslucentTB/TranslucentTB#88] opened 2017-07-19 08:15 UTC
已经选择了开机自启并且在配置文件里面已经设置了Taskbar appearance: opaque, transparent, or blur (default).
accent=transparent
但是开机后还是模糊，怎么回事啊

**Comment by ethanhs** [comment] 2017-07-19 09:13
Hi! Im afraid I don't know Chinese.

(For reference, Google translate of the title gives `Choose to boot from the start after why the boot is not selected before the transparent but fuzzy` which I can only guess is "I set it to boot transparent, but it is blurred"). If anyone here knows Chinese, and is willing to do a more precise translation it'd be appreciated.

@uc1255085 this is the same problem as #79. Thank you for the report.

Im marking this as Duplicate of #79

**Closed by ethanhs** 2017-07-19 09:13 UTC

**Comment by denosawr** [comment] 2017-07-19 11:37
I can barely read and write mandarin, but can speak it semi-fluently and I can confirm that this _is_ a duplicate of #79.
