### ISSUE TITLE
Is it possible to support registration as a system service in future versions to improve the boot priority?

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#521] opened 2022-01-18 01:37 UTC
The software is great, but you need to log in and wait for a period of time to take effect when you start up the software. The software startup priority is relatively low. Can you support registration as a system service, load it directly with the system, and you can use it directly after logging in? I think this is the experience
The software is great, but you need to log in and wait for a period of time to take effect when you start up the software. The software startup priority is relatively low. Can you support registration as a system service, load it directly with the system, and you can use it directly after logging in?

**Comment by sylveon** [comment] 2022-01-18 03:44
Duplicate of #135

**Closed as completed by sylveon** 2022-01-18 03:44 UTC
