### ISSUE TITLE
Moving explorer window destroys Windows 11

### ISSUE THREAD

**Issue by Mekrip** [TranslucentTB/TranslucentTB#457] opened 2021-10-08 20:01 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: 2021.5

 - Steps to reproduce:
   1. Move the windows explorer frome one monitor to the other.

 - Expected results: You can move it correctly to the other monitor.

 - Actual results: While TransculentTB is running, Windows 11 is completely destroyed if you try to move the Explorer from one monitor to the other. The cursor becomes independent and moves very slowly, nothing reacts anymore, so you have to disconnect the PC from the power to "fix" the problem. 

 - Other: --

**Comment by sylveon** [comment] 2021-10-08 20:11
Duplicate of #405

Use another option than blur. It's a bug in Windows 11 for now.

**Closed as completed by sylveon** 2021-10-08 20:11 UTC
