### ISSUE TITLE
[Bug]: win11 22623.1245 无法切换语言

### ISSUE THREAD

**Issue by visiLi** [TranslucentTB/TranslucentTB#722] opened 2023-02-05 06:51 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

软件无法或是不能识别系统语言

### Expected results

希望能解决一下

### Actual results

希望能解决一下

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-02-05 07:23
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-05 07:23 UTC
Labels: bug
