### ISSUE TITLE
[Bug]: No combination of settings seems to work

### ISSUE THREAD

**Issue by ted-he** [TranslucentTB/TranslucentTB#835] opened 2023-04-16 18:58 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

No clear method to reproduce the issue, as my taskbar has seemingly reverted to Windows default.

### Expected results

I expected the taskbar to be entirely transparent. Here's the settings file:
```
// See https://TranslucentTB.github.io/config for more information
{
  "$schema": "https://sylveon.dev/TranslucentTB/schema",
  "desktop_appearance": {
    "accent": "clear",
    "color": "#FFFFFF00",
    "show_peek": false,
    "show_line": false
  },
  "visible_window_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "maximized_window_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false,
    "rules": {
      "window_class": {},
      "window_title": {},
      "process_name": {}
    }
  },
  "start_opened_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "search_opened_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "task_view_opened_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "battery_saver_appearance": {
    "enabled": true,
    "accent": "clear",
    "color": "#00000000",
    "show_peek": false,
    "show_line": false
  },
  "ignored_windows": {
    "window_class": [],
    "window_title": [],
    "process_name": []
  },
  "hide_tray": false,
  "disable_saving": false,
  "verbosity": "warn"
}
```

### Actual results

This is what my taskbar currently looks like:
![image](https://user-images.githubusercontent.com/113558554/232335289-89a06674-ffa6-4312-8eae-f30b97921c03.png)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

### Other details

I've tried reinstalling TTB, restarting Windows, changing "Adjust the appearance and performance of Windows" settings, updating Windows, and installing the latest release.

### Relevant log output

```shell
(I can't seem to access the log file "0x800401F5: Application not found")
```

**Comment by sylveon** [comment] 2023-04-16 20:18
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-16 20:18 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:26
It's strange that if it doesn't work normally, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.

For those looking for a fix, here is your fix. :))
