### ISSUE TITLE
[Bug]:  taskbar doesn't become transparent with Translucent TB

### ISSUE THREAD

**Issue by MeltaDachi** [TranslucentTB/TranslucentTB#857] opened 2023-05-28 10:03 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I download Translucent TB on Microsoft's Store, after that I launch it and I click on continue. But the taskbar doesn't want become transparent. I uninstalled and reinstalled the app but no change. Before, when I was on w10, the app hasn't any problem, and when I passed on w11, it doesn't want to run.

### Expected results

The results that I expected was the taskbar become transparent.

### Actual results

The taskbar doesn't change

### Windows version

Windows 11 RTM (build 22000)

### Other details

The app says that it runs, but it doesn't change my taskbar, and it not appeared on task manager. I don't get any error message either.

**Comment by pokedo0** [comment] 2023-05-28 16:37
same, not work in win 11

**Comment by sylveon** [comment] 2023-05-28 17:29
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-28 17:29 UTC
Labels: bug
