### ISSUE TITLE
[Bug]: Microsoft Store version not working on build 25330 even after disabling STTest

### ISSUE THREAD

**Issue by LowlevelMo** [TranslucentTB/TranslucentTB#853] opened 2023-05-18 07:26 UTC
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just run TranslucentTB on any new build, change it to Clear, and see it not do anything

### Expected results

For the taskbar to be acrylic or transparent

### Actual results

Nothing

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-05-18 07:28
Duplicate of #537 - the flag got removed but the root cause is the same.

**Closed as not planned by sylveon** 2023-05-18 07:28 UTC
Labels: bug
