### ISSUE TITLE
Clear, Fluent, Blur - None of them working on Timeline, Start menu & Cortana?!?!

### ISSUE THREAD

**Issue by Ansu72** [TranslucentTB/TranslucentTB#340] opened 2020-10-15 01:39 UTC
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version:  9.000 Version 9.0000
 - Windows build number:  Windiws 10 Version 2004 Build 19041.546
 - Steps to reproduce:  Opening the sotwaare triggers the problem, its there from day one.
 - Expected results:  Im expecting to be able to use the functions suggested in the program, but so many options are not working
 - Actual results: Clear, Fluent, Blur - None of them working on Timeline, Start menu & Cortana?!?! There is no info saying its not working its just does not.
Also, How do you change the taskbar taxt color, Transparent and white text its to similar on light bacgrounds
 - Other:  No but im dissapointed why this in the Microsoft store and certinly not why its not ther as a BETA rather than advertized as a fully working app, because its not not by a serious measure.

Apprecite any solutions here or just know if its best i just abandon it

Best regards,

Ansu

**Comment by sylveon** [comment] 2020-10-15 01:52
I'm on the same build as you and they all work for me, see [this clip](https://imgur.com/9d7NoFn) (in order: clear on start opened, blur on search, and fluent on timeline)

Your bug report doesn't help me figure out what exactly is your issue, and this software is certainly not beta. Are you sure it's not misconfiguration of TranslucentTB on your side? By default, opening Cortana, the start menu, or the timeline restores your taskbar's appearance to normal.

**Comment by Ansu72** [comment] 2020-10-19 07:46
Hi, 

 

Thanks for your response. Well the problem is that I I can’t change anything on the task view/timeline, it remains clear whatever I do. Cortona will also not change, Taskbar I can get clear, Star menu cant change that at all.

 

A number of things I’ve never got it to work fully, hence I’m calling it a beta. If the app is 

A. not working and never has over a year with different installs,

B. is difficult to understand with no explanation anywhere

C. has no help site

Then sorry I has to say that its not ready even if id not call ite a beta. At the best its obscure. Ill not say shady because that would not be true. Its probably the only app I’ve had problems with from the windows store to the extent that I could not get it to work as advertised and there is a Lot of apps both there and on my Acer Nitro 5.

 

But hey’ maybe you can change my mind 😊

 

Best regards,

 

Ansu

Från: Charles Milette <notifications@github.com> 
Skickat: den 15 oktober 2020 03:53
Till: TranslucentTB/TranslucentTB <TranslucentTB@noreply.github.com>
Kopia: Ansu72 <ansuaronsson@me.com>; Author  <mailto:author@noreply.github.comclear> author@noreply.github.comclear 
Ämne: Re: [TranslucentTB/TranslucentTB] Clear, Fluent, Blur - None of them working on Timeline, Start menu & Cortana?!?! (#340)

 

I'm on the same build as you and they all work for me, see  <https://imgur.com/9d7NoFn> this clip (in order: clear on start opened, blur on search, and fluent on timeline)

Your bug report doesn't help me figure out what exactly is your issue, and this software is certainly not beta. Are you sure it's not misconfiguration of TranslucentTB on your side? By default, opening Cortana, the start menu, or the timeline restores your taskbar's appearance to normal.

**Comment by sylveon** [comment] 2020-10-19 08:27
Maybe you're confused about the purpose of this program: it only changes the taskbar's apperance. Changing start menu/Cortana/timeline is out of scope, and generally much harder to achieve.

The options present affect how the taskbar looks when one of those is opened.

**Comment by Ansu72** [comment] 2020-10-22 12:17
Oh, didnt evn consider that as an option, that must be It then, that im confused! quite sure im not confused about the purpose of the of the program, but now when you say so i actually get confused. I downloaded this from Miscrosoft store.
Please take part of what is written there, ive attached a screen picture. 

As you can read from the description at tue Microsoft Store just as i did and probably thousands before Me it says very clearly that its for Maximized windows,  Start meny Open, Cortana Open, each one with a customizable taskbar apperance. 
Since its the non functioning of those functions above clearly stipilated as indeed withine the scope of the program, infact to the extent its advertized at Microsoft Store; in what way would you say im confused? 
That is why i downloaded the program, and there are even Menus for each function in the program, isnt that a clear way of saying "Hey' try out these functions. But if they are There and fully not functioning "Reliably" then perhaps there should be a "BETA"sign somewhere, as anyone trying them and its not working would probably swear the same after one hours fiddeling. 

By the way wasnt ther mention of "Fix cortana detection in newer windows builds", why fix that if its outside the scope of the program. Certainly if thats so then there would be a lot of things with higher priority Inside the scope of the program. 

So what im really confused about, and rightly so, is the not small gap from what it says on Your page in Microsoft store, and what you are saying; that im confused about these functions not being in the scope of the program, if you follow what i mean.
I do off cource not want to confuse you the way i am,  i am, that would be a very difficult conversation :o)

Best regards,

Ansu Aronsson

**Comment by Ansu72** [comment] 2020-10-22 12:20
I off course forgot to attached the picture in all the confusion. :)
![TrancelucentTBp](https://user-images.githubusercontent.com/64692228/96870733-a0689300-1471-11eb-87f5-739331dcd35f.JPG)

**Comment by torchgm** [comment] 2020-10-22 15:05
The first line of the Store description makes it very clear that it is for controlling and manipulating the appearance of the _taskbar_ and nothing else; at no point would I ever consider to interpret the list of actionable states as other things that can be customised, especially if you actually read the Store description fully. The functions are very-much there. You can have the taskbar's appearance change depending on whether or not you have the start menu open, when you're viewing Timeline or using Cortana or if you have a maximised window occupying the monitor. TTB does as-advertised and I'm honestly not sure as to what the issue is.

**Comment by Ansu72** [comment] 2020-10-22 15:37
You are Unsure about what the Issue is?? Really?? A lot Of people are having issues and problems with your software, I’m one of them. It’s impossible for me to have the program influence Anything but the task bar. And if it’s so that you don’t now Stand for that even then you should not state that it can. And what the hell do you mean it’s clear from the first line!! Yes maybe if you stop reading there but as you continue other statements are being made. Of course it says Customize becuse that’s what the whole program is about.
Rediculous reply, how about you would have helped out instead as I simply asked for in the beginning instead of being argumentative and telling me that I’m confused 
Sure you say it’s for the taskbar well all the other functions comes from the taskbar and most importantly you have clear functions for each part,  that says it all. Stop seem like a scammer rather than what seems clear in your response.

And how about when you communicate for the company outside you Underwrite your replies, like I do.. that’s the norm so anyone will know who they spoke to. Or are you intentionally shying from that as well??!!

/Ansu Aronsson

**Comment by torchgm** [comment] 2020-10-22 15:52
The fact that you can't even realise that this isn't my software and I'm another person commenting demonstrates quite clearly that you don't read things in full before stirring up a tantrum. Quite frankly I struggle to understand how comprehending one relatively simple paragraph eludes you, but the very first line is, and I quote:
> Take control of your **taskbar!**

At no point does it say it can control or customise anything other than the taskbar. It says it can respond to actions such as the user interacting with the Start Menu (functionality that works as-described) but that doesn't suddenly imply it can also control the Start Menu (or any of the other cited actions) in any way, shape or form. This is a non-issue based on your misunderstanding of the app's description that you misread and now won't back down from.

**Comment by Ansu72** [comment] 2020-10-22 16:12
Did I suggest that you Own the company, you wrote to me reagarding this hence you get response. 

Just read the second sentence which happens to be quite long but read what it says more than Taskbar.



So do you mean you are not speaking on behalf of the company?
If not then don’t mind answering anymor as it’s a waste of time.

/Ansu

**Comment by sylveon** [comment] 2020-10-22 16:17
This isn't really a company... But what he's saying is right. TTB can only change **the taskbar**, it can make **the taskbar** look different depending if you have Start Menu, Cortana, etc open. It *won't change* what Start Menu and Cortana themselves look like.

**Closed as completed by sylveon** 2020-10-22 16:17 UTC
