### ISSUE TITLE
[Bug]: Windows11今天更新后，半透明失效了

### ISSUE THREAD

**Issue by 2635384122** [TranslucentTB/TranslucentTB#852] opened 2023-05-16 12:29 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Windows11今天更新后，半透明失效了

### Expected results

需要更新软件了

### Actual results

需要更新软件了

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-05-16 15:07
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-16 15:07 UTC
Labels: bug
