### ISSUE TITLE
[Bug]: win11不支持全透明了吗？？？？

### ISSUE THREAD

**Issue by InternetofThingsprogrammer** [TranslucentTB/TranslucentTB#698] opened 2022-12-08 18:47 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

win11beta 版本 22623.1028 没有全透明选项？？？

### Expected results

希望可以全透明

### Actual results

没有透明选项

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2022-12-08 19:55
Duplicate of #537

**Closed as not planned by sylveon** 2022-12-08 19:55 UTC
Labels: bug
