### ISSUE TITLE
app stopped working after windows 11 February 28, 2023—KB5022913 (OS Build 22621.1344) update 

### ISSUE THREAD

**Issue by ak137guru** [TranslucentTB/TranslucentTB#766] opened 2023-03-06 11:06 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I have uninstalled/reinstalled the app, stopped the transparent effect from windows settings. repaired, reset. 

### Expected results

none of the above remedied the situation.

### Actual results

i think the new search function with the update is affecting the app

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-06 11:37
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-06 11:37 UTC
Labels: bug
