### ISSUE TITLE
[Bug]: Full transparent mode stop working after Windows update

### ISSUE THREAD

**Issue by lesada** [TranslucentTB/TranslucentTB#785] opened 2023-03-13 20:50 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Just stop working after updates, please check this

### Expected results

Clear taskbar

### Actual results

Taskbar stays like acrylic mode

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

22621.1344

**Comment by sylveon** [comment] 2023-03-13 20:50
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-13 20:50 UTC
Labels: bug
