### ISSUE TITLE
[Solved]: No use on Win11.OS.22621.1702

### ISSUE THREAD

**Issue by Lioncky** [TranslucentTB/TranslucentTB#862] opened 2023-06-11 18:50 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

[Download](https://www.microsoft.com/software-download/windows11) the lateset win11 edition and apply I think it will recurring.

### Expected results

The problems solved.

### Actual results

I followed this [article ](https://windowsreport.com/transparent-taskbar-windows-11/)then found this app and try.
Another app 'Private.BlurClear.exe' not work as well, the taskbar's alpha seems always lock to 50%. 

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-06-11 19:04
Duplicate of #537

**Closed as not planned by sylveon** 2023-06-11 19:05 UTC
Labels: bug

**Comment by Lioncky** [comment] 2023-06-11 19:25
I've seen that, better to add more details in bug report aera

Solutions: ViveTool /disable /id:26008830

**Comment by dinaau** [comment] 2023-06-18 00:39
> ViveTool

can you elaborate this more? what is Vivetool ? how to disable it ?
