### ISSUE TITLE
In Windows 11 light mode, the taskbar text cannot be seen clearly.

### ISSUE THREAD

**Issue by Dazzle-sys** [TranslucentTB/TranslucentTB#442] opened 2021-09-21 08:01 UTC
In Windows 11 light mode, the taskbar text cannot be seen clearly.

**Comment by sylveon** [comment] 2021-09-22 01:37
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/41

**Closed as completed by sylveon** 2021-09-22 01:37 UTC
