### ISSUE TITLE
[Bug]: I'm probably not intelligent enough but TranslucentTB doesn't work at all! My data is:

### ISSUE THREAD

**Issue by Draskic** [TranslucentTB/TranslucentTB#715] opened 2023-01-13 18:03 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm probably not intelligent enough but TranslucentTB doesn't work at all!
My data is:

### Expected results

I'm probably not intelligent enough but TranslucentTB doesn't work at all!
My data is:

### Actual results

I'm probably not intelligent enough but TranslucentTB doesn't work at all!
My data is:

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

I'm probably not intelligent enough but TranslucentTB doesn't work at all!
My data is:Edition	Windows 11 Pro
Version	22H2
Installed on	‎12.‎5.‎2022.
OS build	22623.1095
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by sylveon** [comment] 2023-01-13 20:30
Duplicate of #537

**Closed as not planned by sylveon** 2023-01-13 20:31 UTC
Labels: bug

**Comment by Draskic** [comment] 2023-01-13 21:23
Thanks for closing the case!
I wouldn't be able to stand one more amateur massage like for, say, 11clock, which is buggy like all the programs in this world!
That TraslucentTB definitely doesn't work on mine:
Windows 11 Pro
Version 22H2
Installed on ‎12.‎5.‎2022.
OS build 22623.1095
Experience Windows Feature Experience Pack 1000.22638.1000.0
Greeting!
