### ISSUE TITLE
[Bug]: Windows 11 KB5022913 (OS Build 22621.1344) Preview - **Breaks TranslucentTB**

### ISSUE THREAD

**Issue by alexhollis** [TranslucentTB/TranslucentTB#784] opened 2023-03-13 15:37 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After installing the update - KB5022913 (OS Build 22621.1344) Preview
TranslucentTB no longer functions, 
Update Details: [https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9](https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9)

### Expected results

Taskbar to display according to the configuration in the application 

### Actual results

Taskbar remains in default appearance, and no longer changes

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Relevant log output

```shell
[2023-03-13 15:37:37.609] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1056] Monitor 0x6030b:
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x409d2 [] [Shell_SecondaryTrayWnd] [explorer.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x301ee [] [WorkerW] [explorer.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:708] 			0x109be [New Issue · TranslucentTB/TranslucentTB - Google Chrome] [Chrome_WidgetWin_1] [chrome.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:708] 			0x10b0e [New tab - Personal - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:708] 			0x90b7c [Microsoft Store] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:708] 			0x2098c [Settings] [ApplicationFrameWindow] [ApplicationFrameHost.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x1060e [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:708] 		0x1011c
[2023-03-13 15:37:37.611] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by smultar** [comment] 2023-03-13 16:10
#741

**Comment by smultar** [comment] 2023-03-13 16:11
Meant to mentioned #537

**Comment by sylveon** [comment] 2023-03-13 18:06
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-13 18:06 UTC
Labels: bug
