### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sure-Will** [TranslucentTB/TranslucentTB#972] opened 2024-01-14 15:52 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

when i restart my pc, and click this software it warns like below:
TranslucentTB has encountered a fatal error and cannot continueexecuting.
Failed to copy ExplorerHooks.dll
0x80070003. The system cannot find the path specified

### Expected results

i want to use this software normally

### Actual results

![image](https://github.com/TranslucentTB/TranslucentTB/assets/127877795/72bfcb0a-28ad-422d-9aa5-bd31b18c430f)

### Windows version

Windows 10 2004-22H2 (builds 19041-19045)

**Comment by Sure-Will** [comment] 2024-01-14 15:53
I try to download the portable x64 version in github not in microsoft store, but the bug still exists.

**Comment by sylveon** [comment] 2024-01-14 23:36
Duplicate of #958

**Closed as not planned by sylveon** 2024-01-14 23:36 UTC
Labels: bug
