### ISSUE TITLE
[Bug]: I'm not sure if this is a bug: after I upgraded my Windows system, the startup software didn't work. 

### ISSUE THREAD

**Issue by xbaoziplus** [TranslucentTB/TranslucentTB#805] opened 2023-03-26 15:15 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm not sure if this is a bug: after I upgraded my Windows system, the startup software didn't work. 
Here is my upgrade info: 2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5023706)

### Expected results

I hope this can be fixed in time if you guys time it right and figure it out

### Actual results

I would appreciate it if I get a reply or if the problem is fixed

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by zp-86** [comment] 2023-03-26 15:50
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/537

**Closed as not planned** 2023-03-26 19:31 UTC
Labels: bug
