### ISSUE TITLE
TRANSLUCENT TB IS NOT WORKING! NOTHING HAPPENS AFTER TURNING ON

### ISSUE THREAD

**Issue by vikulverma** [TranslucentTB/TranslucentTB#586] opened 2022-03-31 03:49 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.
 - x
 -
![Screenshot 2022-03-31 091820](https://user-images.githubusercontent.com/102712316/160972617-c7c8db20-4286-41d1-baf7-0cc48df45a92.png)

It is not working in my windows 11 pc, nothing happens whenever I turn ON TranslucentTB

**Comment by sylveon** [comment] 2022-03-31 04:11
Duplicate of #537

**Closed as completed by sylveon** 2022-03-31 04:11 UTC
