### ISSUE TITLE
[Bug]: You can't apply transparency in the action bar

### ISSUE THREAD

**Issue by marcaomaresia** [TranslucentTB/TranslucentTB#704] opened 2022-12-16 12:23 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After the last update the application stopped working. Even reinstalling there is no way to make the windows bar transparent.

### Expected results

Full transparency of the windows action bar

### Actual results

The transparency bar remains the same way

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2022-12-16 14:05
Duplicate of #537

**Closed as not planned** 2022-12-16 14:05 UTC
Labels: bug
