### ISSUE TITLE
[Bug]: After installing "2023 - 03 Cumulative Update for Windows 11 Version 22H2, Suitable for x64 Based Systems (KB5023706)", TranslucentTB cannot be transparent/translucent on the Windows taskbar

### ISSUE THREAD

**Issue by renmoren** [TranslucentTB/TranslucentTB#803] opened 2023-03-26 05:55 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install "2023 - 03 Cumulative Update for Windows 11 Version 22H2, Suitable for x64 Based Systems (KB5023706)"

### Expected results

Transparent/Translucent Windows Taskbar

### Actual results

The Windows taskbar remains as is

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Relevant log output

```shell
[2023-03-26 05:32:35.048] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x10178 [] [Shell_TrayWnd] [explorer.exe]
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:708] 			0x104c2 [新发行 ·半透明结核/半透明结核 和另外 2 个页面 - 个人 - Microsoft​ Edge] [Chrome_WidgetWin_1] [msedge.exe]
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x60054 [系统托盘溢出窗口。] [TopLevelWindowForOverflowXamlIsland] [explorer.exe]
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-03-26 05:32:35.050] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by sylveon** [comment] 2023-03-26 05:57
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-26 05:57 UTC
Labels: bug
