### ISSUE TITLE
The blur effect is missing from Windows 11

### ISSUE THREAD

**Issue by CharlieWilkinson005** [TranslucentTB/TranslucentTB#476] opened 2021-10-25 21:00 UTC
The blur effect is missing from Windows 11. It is there on Windows 10 but it is not on Windows 11.
![Untitled](https://user-images.githubusercontent.com/71225213/138770038-0c6407fc-2588-4d4e-a080-8149533c0c25.png)

**Comment by sylveon** [comment] 2021-10-26 03:29
Duplicate of #405

**Closed as completed by sylveon** 2021-10-26 03:29 UTC
