### ISSUE TITLE
[Bug]: Need a new patch for Windows 11 22621.1555 

### ISSUE THREAD

**Issue by 0xKoharu** [TranslucentTB/TranslucentTB#833] opened 2023-04-15 06:05 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After update KB5025239 -  22621.1555 (2023-04 Cumulative Update for Windows 11 Version 22H2) , the reg patch version of 22621.1343 in issue #537 (KB5023706) is no longer working

While the fix is been working on #537, Hope someone could make the small reg patch for 22621.1555 too - Tysm
### Expected results

taskbar transparent

### Actual results

Taskbar not changed after open the app

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by hexkraft** [comment] 2023-04-15 06:08
https://github.com/TranslucentTB/TranslucentTB/issues/537

**Comment by sylveon** [comment] 2023-04-15 07:22
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-15 07:22 UTC
Labels: bug

**Comment by 0xKoharu** [comment] 2023-04-17 12:51
k nvm just reopen the reg patch and it still working as normal

**Comment by WantedTab** [comment] 2023-05-03 09:27
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
