### ISSUE TITLE
[Bug] The application crashes when executed a second time

### ISSUE THREAD

**Issue by pzzzling** [TranslucentTB/TranslucentTB#437] opened 2021-09-09 12:34 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Version 5 (2021.4)

 - Steps to reproduce:
   1. Run TranslucentTB.
   2. While the application is running, run it again.

 - Expected results: (in the previous version) the taskbar handle will be refreshed, and it looks like nothing happened.

 - Actual results: The application crashes.
<img width="339" alt="Snipaste_2021-09-09_19-53-56" src="https://user-images.githubusercontent.com/39448739/132682316-3624941a-d53a-41ce-86a9-5a0239b9e464.png">

 - Other: It seems this problem doesn't exist in the previous version. I tried version 2020.2 and it doesn't crash at all.

**Comment by sylveon** [comment] 2021-09-09 12:37
Caused by https://github.com/microsoft/STL/issues/2185

**Comment by pzzzling** [comment] 2021-09-10 05:22
Thanks for the reply! Looks hard to solve at this time...

**Comment by sylveon** [comment] 2021-10-08 20:13
Fixed in 2021.5

**Closed as completed by sylveon** 2021-10-08 20:13 UTC
