### ISSUE TITLE
[Bug]: It had stopped working in latest windows 11 update but found this workaround incase anyones interested

### ISSUE THREAD

**Issue by CitizenDroid** [TranslucentTB/TranslucentTB#839] opened 2023-04-23 11:31 UTC
### Please check for a duplicate first

- [ ] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I found this fix and works for me sorry if wrong place to post but can't find any other to help others and take pressure off TranslucentTB who I know is probably getting inundated with issues about it. may also shed some light on how to fix who know I'm no programmer :)

Part A is for those that want TranslucentTB, and Part B fixes TranslucentTB and allows the Taskbar Size tweak to work again.

Of course you can do both Part A and Part B if desired. I did both and it works so better off that this way.

Part A
1. Go here, scroll down a bit and download: TranslucentTB-portable-x64.zip (for 64 bit Windows 11).
2. make a folder called TranslucentTB-portable-x64 in C drive Extract the .zip file to it(assuming C:\ is where Win 11 is installed).
3. Open the folder: C:\TranslucentTB-portable-x64 ...and right click: TranslucentTB.exe and choose: Create shortcut.
4. Right click the shortcut and choose: Copy
5. Navigate to: C:\Users\user name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup ..and in the Startup folder, right click and "paste" the shortcut. This will cause TranslucentTB to start with Windows.

This could also work with the normal install of TTB in MS store version but I could be arsed to find the install directory so I used a portable version by all means play around if you have the time. I think it will work just by creating a shortcut inside directory then copy that shortcut and paiste inside \AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup folder.

how ever I first found the below work around using Vive tool and doing this,

download Vivetool GUI from github
install and open app
in the top left box where it says "select build" click it and select the first build at top of list
now paste this number "26008830" in the search box to find "STTest" once that is highlighted now click on 
"Perform action" and select deactivate feature then it should say disabled next to STTest
close all windows and reboot .
The only thing just using this was I think after a few rebots it stopped again so follow the above concerning pasting shortcut and do the vive tool job and see how you get on mines still working fine.

Part B
1. Go here and download ViVeTool-v0.3.2.zip
2. Create a folder in C:\ called zVIVE
3. Extract the contents of the .zip file you downloaded to: C:\zVIVE
4. Open an elevated (as admin), command prompt.
5. Type: cd C:\zVIVE
7. When the prompt changes to... c:\zVive, type: vivetool /disable /id:26008830
8. Reboot the computer, TranslucentTB and Taskbar resizing, should be working again.

### Expected results

now working again I believe it is because of shortcut is missing in start up folder in User Roaming ect folder

### Actual results

working again 

### Windows version
23/04/23
what I'm running
Windows 11 pro
Ver: 22H2
OS build 22621.1555
Windows Feature Experience Pack 1000.22640.1000.0

**Comment by sylveon** [comment] 2023-04-23 20:08
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-23 20:08 UTC
Labels: bug
