### ISSUE TITLE
[Bug]: Win 11 build 

### ISSUE THREAD

**Issue by FooYongLiang** [TranslucentTB/TranslucentTB#736] opened 2023-03-01 04:06 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I just update Windows 11 and now my Translucent TB isn't working at all. Everytime I try to set my Taskbar to "Clear" all I get is a solid gray. Tried uninstalling, re-installing, still nothing. 

Window update to: 
2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913)
Window build : 22621.1344

### Expected results

"Clear" and the app back to work properly

### Actual results

Still no one fix it.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-01 05:36
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-01 05:36 UTC
Labels: bug
