### ISSUE TITLE
Transparent doesn't work after turn on/Off multi monitors

### ISSUE THREAD

**Issue by denissyk2004** [TranslucentTB/TranslucentTB#409] opened 2021-08-29 06:43 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version:  9.0.0.0
 - Windows build number:  19043.1165
 - Steps to reproduce:  After I turn on or off my second monitor, the taskbar will go opaque.  I have to manually click refresh taskbar handles to let it transparent again.
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment] 2021-08-29 07:07
Duplicate of #308. A release with a fix is coming very soon.

**Closed as completed by sylveon** 2021-08-29 07:07 UTC
