### ISSUE TITLE
[Bug]: it doesn't change the taskbar color after update (22621.1344 version)

### ISSUE THREAD

**Issue by mooncakemimi** [TranslucentTB/TranslucentTB#762] opened 2023-03-05 23:46 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

After I open translucent tb, the taskbar remains the same. I tried resetting the settings, force closing, uninstalling and reinstalling. Nothing works.

[1678059206.log](https://github.com/TranslucentTB/TranslucentTB/files/10893268/1678059206.log)

### Expected results

Expected the taskbar to be transparent

### Actual results

![image](https://user-images.githubusercontent.com/127060555/222992921-98d90c6e-1cb7-4936-8972-6dbda1bed413.png)
Taskbar looks exacly like this.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-03-05 23:48
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-05 23:49 UTC
Labels: bug
