### ISSUE TITLE
I can't get something to work

### ISSUE THREAD

**Issue by sanojhb** [TranslucentTB/TranslucentTB#157] opened 2018-05-31 23:03 UTC
I'm trying to get dynamics windows to launch on startup. I have read the usage file but i'm doing something wrong. Whatever I do, every time is reboot it just restarts as blur. Can somebody help me out please? Thanks

**Comment by denosawr** [comment] 2018-06-07 02:13
Duplicate of #159.

**Closed by denosawr** 2018-06-07 02:13 UTC
