### ISSUE TITLE
Grey line above taskbar in clear mode in Windows 11

### ISSUE THREAD

**Issue by storym94374** [TranslucentTB/TranslucentTB#515] opened 2022-01-06 08:21 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

I just installed Windows 11 and TranslucentTB from Microsoft Store. I would like to make the taskbar being transparent and watch the wallpaper directly.
But when I changed the style to clear, I noticed that there is a grey line on the top of taskbar, which was not present in Windows 10.
And the grey line isn't as long as the width of the monitor. The right corner where system tray icons stay does not have that line, and that feels really weird.
Is it possible to remove the grey line when in clear mode?

**Comment by sylveon** [comment] 2022-01-06 14:40
Duplicate of #425

**Closed as completed by sylveon** 2022-01-06 14:40 UTC
