### ISSUE TITLE
Translucent TB is not working properly after Windows 11 22H2 update. A thin white line is showing above the taskbar even if the taskbar is transparent.

### ISSUE THREAD

**Issue by TharinduNava** [TranslucentTB/TranslucentTB#650] opened 2022-09-26 11:47 UTC
[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by alexd2005** [comment] 2022-09-26 12:00
Same issue here with 22H2.

**Comment by sylveon** [comment] 2022-09-26 12:54
Duplicate of #425

**Closed as not planned by sylveon** 2022-09-26 12:54 UTC

**Comment by DexterzGretege** [comment] 2022-09-29 02:25
Just install RoundedTB from Windows Store and Under Advanced Options select TranslucentTb Compatibility. It should fix the issue. I had the same issue after updating to Win 11 Version 22H2 and after doing the above it was fixed instantly.

**Comment by alexd2005** [comment] 2022-09-29 04:29
I downloaded the latest beta and it works now. RoundedTB doesn’t work with autohide.

**Comment by DexterzGretege** [comment] 2022-09-29 05:20
I see it worked perfectly fine for me though.
