### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Yashwanthramka** [TranslucentTB/TranslucentTB#697] opened 2022-12-06 18:04 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Right click

### Expected results

Wanted the context menu but its not even showing up

### Actual results

Context menu not showing up after rightclick. But TB service is running

### Windows version

Windows 10 May/November 2019 Update (builds 18362 and 18363)

### Other details

Context menu not showing up after rightclick. But TB service is running

### Relevant log output

```shell
Logs are empty
```

**Comment by sylveon** [comment] 2022-12-06 19:01
Are you on windows 11 insider builds?

**Comment by Yashwanthramka** [comment] 2022-12-06 19:04
Yes

**Comment by sylveon** [comment] 2022-12-06 19:06
Duplicate of #537

**Closed as not planned by sylveon** 2022-12-06 19:06 UTC
Labels: bug
