### ISSUE TITLE
[Bug]: n the system version of Windows 11 21H2, the option button "When opening the Start menu" in the software does not successfully execute the subdivision options within the option after it is enabled, such as changing the accent color.

### ISSUE THREAD

**Issue by FrankLier03** [TranslucentTB/TranslucentTB#894] opened 2023-07-15 17:25 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

n the system version of Windows 11 21H2, the option button "When opening the Start menu" in the software does not successfully execute the subdivision options within the option after it is enabled, such as changing the accent color.

### Expected results

succeed

### Actual results

fail

### Windows version

Windows 11 RTM (build 22000)

**Comment by Ptilopsis01** [comment] 2023-07-15 17:59
I've met this problem too

**Comment by sylveon** [comment] 2023-07-15 21:16
Duplicate of #886

**Closed as not planned by sylveon** 2023-07-15 21:16 UTC
Labels: bug
