### ISSUE TITLE
[Bug]: the taskbar doesn't become clear

### ISSUE THREAD

**Issue by omeGAmer** [TranslucentTB/TranslucentTB#733] opened 2023-02-25 14:30 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

The taskbar does not become clear. The TranslucentTB program works, there're no duplicates in task manager, the registry keys are in order

### Expected results

The taskbar does not become clear.

### Actual results

https://user-images.githubusercontent.com/82946443/221362285-78c77579-9f84-4357-843b-020bcf76f2fd.mp4

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by cbo305** [comment] 2023-02-25 18:35
I'm having the same issue after the most recent Windows 11 update. I rolled my system back to just prior to the update and it was working again. I had to restart my PC and accidentally updated again and the issue is back. So definitely seems to be an issue with the newest version of Window 11

**Comment by sylveon** [comment] 2023-02-25 20:00
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-25 20:00 UTC
Labels: bug
