### ISSUE TITLE
[Enhancement] Detect Aero snap side-by-side "fullscreen-like" window configuration

### ISSUE THREAD

**Issue by FSund** [TranslucentTB/TranslucentTB#167] opened 2018-06-29 08:48 UTC
I'm using the latest version from AppVeyor (Build #279), and noticed that, while detection of fullscreen windows works well, but when I put two windows side-by-side using Aero snap (which covers the whole desktop, and is thus pretty similar to a single fullscreen window) TB still uses the "Regular" transparency setting.

I think a great addition would be to use the "Maximized window" setting in such cases (or add a separate "Aero snap fullscreen" setting). No idea if it's possible to detect such a configuration though.

EDIT: Here is some info regarding detecting if a window is docked/snapped. No idea if that helps though, as I've never programmed any Windows apps! But it seems like the requested functionality might be possible.
https://stackoverflow.com/a/47911169/1850917

**Comment by denosawr** [comment] 2018-07-03 17:15
Thanks for the suggestion! However, I think this is a duplicate of #116. That being said, a brief look at the SO link you sent presents a possible way to approach the issue - I’ll probably repost the link there for further discussion.

**Closed by denosawr** 2018-07-03 17:15 UTC
