### ISSUE TITLE
[Bug]:now longer works for win11 22621.1413 

### ISSUE THREAD

**Issue by TwilightXQY** [TranslucentTB/TranslucentTB#791] opened 2023-03-15 05:27 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

upgrade your windows to 22621.1413

### Expected results

TB would still be working

### Actual results

TB does not work properly anymore
note: restart the system does not help

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-15 05:27
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-15 05:27 UTC
Labels: bug
