### ISSUE TITLE
Dragging windows got extremely lag if enable both TTB and Windows 11 Blur effect

### ISSUE THREAD

**Issue by happyme531** [TranslucentTB/TranslucentTB#405] opened 2021-07-17 13:00 UTC
[x] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 9.0.0.0
 - Windows build number: 22000.71
 - Steps to reproduce: 
    1. Enable Windows' Blur effect in settings > customize > colour > Transparent effect (透明效果)
    2. Enable TTB's blur mode
    3. Drag an window such as file explorer and feel the lagness
 - Expected results: Don't get lag
 - Actual results: Very laggy, your mouse cursor doesn't follow the real mouse's speed.
 - Other:

**Comment by sylveon** [comment] 2021-07-18 03:07
This is fixed in the [dev build](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzE0MC9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)

**Comment by happyme531** [comment] 2021-07-18 04:21
> 
> 
> This is fixed in the [dev build](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzE0MC9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)

This is NOT fixed.

**Comment by sylveon** [comment] 2021-07-18 04:52
It works for me on my laptop with an AMD APU. What's your system specs?

**Comment by happyme531** [comment] 2021-07-18 10:08
- CPU: AMD R3 2300U
 - RAM: 8GB
 - GPU: Vega 6
 - SSD: 128G M.2 NVMe
 - Windows: 22000.71 Enterprise
 - Language: Chinese
 - TTB Version: 2020.2.683.75f08b0
 - Config:
```json

// See https://TranslucentTB.github.io/config for more information
{
    "$schema": "https://sylveon.dev/TranslucentTB/schema",
    "desktop_appearance": {
        "accent": "clear",
        "color": "#00000000",
        "show_peek": true
    },
    "visible_window_appearance": {
        "enabled": false,
        "accent": "blur",
        "color": "#00000000",
        "show_peek": true
    },
    "maximized_window_appearance": {
        "enabled": true,
        "accent": "blur",
        "color": "#00000000",
        "show_peek": true
    },
    "start_opened_appearance": {
        "enabled": false,
        "accent": "normal",
        "color": "#00000000",
        "show_peek": true
    },
    "search_opened_appearance": {
        "enabled": false,
        "accent": "normal",
        "color": "#00000000",
        "show_peek": true
    },
    "task_view_opened_appearance": {
        "enabled": false,
        "accent": "normal",
        "color": "#00000000",
        "show_peek": false
    },
    "ignored_windows": {
        "window_class": [],
        "window_title": [],
        "process_name": []
    },
    "hide_tray": false,
    "disable_saving": false,
    "verbosity": "warn"
}
```

**Comment by happyme531** [comment] 2021-07-18 10:17
That looks like...
https://user-images.githubusercontent.com/20812356/126063582-a6e25e8e-dc08-4203-8f96-8785310c49eb.mp4

**Comment by sylveon** [comment] 2021-07-21 03:53
Ok I reproduced it. It happens with any app using this effect, eg Radeon Settings will reproduce it (even when TTB isn't running), so it's a Windows 11 bug.

**Comment by ameoverflow** [comment] 2021-08-13 12:29
still isn't fixed in newest build of TTB (Windows 11 22000.132)

**Comment by enoversum** [comment] 2021-08-23 14:46
I just realised today that this happens in conjunction with TTB (using the Store version). Is there anything that can be done via TTB, or is this something immanent in current Windows 11 builds and we're stuck with not using TTB for the moment?

**Comment by sylveon** [comment] 2021-08-23 18:05
The best I can do is probably completely hide the blur effect for now from the options when running on Windows 11, because it's a Windows bug and since the API we use is undocumented, the chances of a fix are low unfortunately

**Comment by enoversum** [comment] 2021-08-27 11:17
@sylveon Thanks Charles, for getting back and confirming the problem (again). Too bad it's basically not fixable at the moment, but I'm grateful for the time I had with your app :-) .

**Comment by Ikaleio** [comment] 2021-08-29 12:45
I use the "ignored_windows" option to avoid it.

```json
"ignored_windows": {
        "window_class": [],
        "window_title": [],
        "process_name": ["explorer.exe"]
    }
```

**Comment by enoversum** [comment] 2021-08-29 14:47
> I use the "ignored_windows" option to avoid it.
> 
> ```json
> "ignored_windows": {
>         "window_class": [],
>         "window_title": [],
>         "process_name": ["explorer.exe"]
>     }
> ```

Just out of curiosity, is that applicable in a way to the Store version?

**Comment by sylveon** [comment] 2021-08-29 20:11
> I use the "ignored_windows" option to avoid it.

I just tried and it stills results in noticeable lag when you drag the explorer window under the taskbar

> Just out of curiosity, is that applicable in a way to the Store version?

There's a different file in the store version which serves the same purpose. The one @dajia-1701 mentions comes from dev builds (which will soon land in the store)

**Comment by Ikaleio** [comment] 2021-08-30 01:23
> I just tried and it stills results in noticeable lag when you drag the explorer window under the taskbar

I tried again(explorer window under the taskbar) but there is no lag

**Comment by Wndstorms** [comment] 2021-08-30 05:23
I found another way to solve this. Just use the old explorer. Everything runs smooth.

**Comment by sylveon** [comment] 2021-08-30 05:23
Yeah cause then the Mica effect, which is the cause of this issue, is not enabled.

**Comment by sylveon** [comment] 2021-09-02 16:42
Fixed in build 22449, supposedly

> We’ve done some work to help address an underlying issue where moving certain app windows would be very slow if a File Explorer window was also visible on the screen.

**Comment by enoversum** [comment] 2021-09-03 11:00
> Fixed in build 22449, supposedly
> 
> > We’ve done some work to help address an underlying issue where moving certain app windows would be very slow if a File Explorer window was also visible on the screen.

Oh, great. I’m not on the Dev, but the Beta channel, so I can’t actually test this out right now, but once the update gets to the conservative Beta users, I will let you know 😉!

**Comment by sylveon** [comment] 2021-09-03 11:04
There's a chance that fix might flow downstream, as Radeon Settings and a few other apps reproduce the issue and it would be kind of bad if that released. I'll bring the option back to the context menu if that does happen.

**Comment by enoversum** [comment] 2021-09-03 11:12
Yes, I’m absolutely sure they’ll put that in a soon-after-release update or even into the release version of Windows 11. After I had disabled and even uninstalled your app, the problem re-occured, though a lot less often, so there are definitely other apps out there that suffer from that behaviour, even when they don’t alter the taskbar. I understand this is a wider problem, as you described.

**Comment by Wndstorms** [comment] 2021-09-03 12:36
Great news is that the lag is fixed in 22449 : )

**Comment by Ehoumaki** [comment] 2021-09-07 00:57
the problem has been sovled in Dev 22449.1000，if can bring blur option back again？

**Comment by KaizerHanz** [comment] 2021-09-11 16:09
> This is fixed in the [dev build](https://artprodcca1.artifacts.visualstudio.com/A9bd8285a-05b0-4590-a30d-489076a293f3/604b3a7f-cfeb-496e-aabc-35608a8095c9/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3N5bHZlMG4vcHJvamVjdElkLzYwNGIzYTdmLWNmZWItNDk2ZS1hYWJjLTM1NjA4YTgwOTVjOS9idWlsZElkLzE0MC9hcnRpZmFjdE5hbWUvUG9ydGFibGUreDY0K1JlbGVhc2U1/content?format=zip)

so far blur in this version working fine on insider build 22454.1000 and no lag so far (let me test few day if I found laggy) Thanks

**Comment by emanuelbg** [comment] 2021-10-20 16:43
Still lag on insider build 22478.1012

**Comment by james28909** [comment] 2021-10-31 06:40
the bug has been fixed with update KB5006746. can confirm translucenttb blur effect is working great and no more drag laggggg

**Closed as completed** 2022-05-30 06:59 UTC
