### ISSUE TITLE
Feature Request: chinese

### ISSUE THREAD

**Issue by QG2348** [TranslucentTB/TranslucentTB#243] opened 2019-04-18 15:22 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: 
 - Windows build number: 
 - Steps to reproduce: 
 - Expected results: 
 - Actual results: 
 - Other:

**Comment by sylveon** [comment] 2019-04-18 15:24
Duplicate of #231

**Closed by sylveon** 2019-04-18 15:24 UTC
