### ISSUE TITLE
[Feature Request] Select text color from background

### ISSUE THREAD

**Issue by FelixSchuetze** [TranslucentTB/TranslucentTB#439] opened 2021-09-17 18:03 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

If you are using "clear" setting and dark/light wallpaper, certain icons can become really hard to read/see. I would love to have TranslucentTB choosing black or white font color automatically from the background to get high contrast.

**Comment by sylveon** [comment] 2021-09-17 18:11
Duplicate of https://github.com/TranslucentTB/TranslucentTB/issues/41

**Closed as completed by sylveon** 2021-09-17 18:11 UTC

**Comment by FelixSchuetze** [comment] 2021-09-18 00:41
Oh I'm sorry
