### ISSUE TITLE
[Bug]: Cannot apply after KB5022913 (Build 22621.1343) update

### ISSUE THREAD

**Issue by LiarOnce** [TranslucentTB/TranslucentTB#730] opened 2023-02-23 10:41 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

This patch further modifies the search part of the taskbar.

### Expected results

Apply the previous settings (make the taskbar transparent or translucent).

### Actual results

Nothing happened.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Windows 11 22H2 Build 22621.1343

**Comment by sylveon** [comment] 2023-02-23 10:44
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-23 10:44 UTC
Labels: bug
