### ISSUE TITLE
[Bug]: App broke after Windows 11 New Update

### ISSUE THREAD

**Issue by Ahmedlii** [TranslucentTB/TranslucentTB#830] opened 2023-04-14 19:32 UTC
### Please check for a duplicate first

- [x] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I'm not really sure, I think it's just the new update that broke the app or changed the working of taskbar for any reason. 

### Expected results

I've restarted the pc and it's exactly same, same issue and such. I tried rebooting 

### Actual results

The taskbar is normal, despite me setting it to clear which means the app broke due to the update. I've checked in the recent reviews of the app on Microsoft Store and some people seem to have same issue as I do. 

![image](https://user-images.githubusercontent.com/127249650/232134843-22a94623-2ee7-4771-8785-4e244942ca42.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

The version I'm currently using is 2023-03 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5023706) and it updated to the current version on March 19th, 2023. 

### Relevant log output

[1681425566.log](https://github.com/TranslucentTB/TranslucentTB/files/11236518/1681425566.log)

**Comment by mcdonamw** [comment] 2023-04-14 19:36
Came to post this bug too.  HELP!  lol

**Comment by d3adwolf** [comment] 2023-04-14 20:53
> Came to post this bug too. HELP! lol

Similarly.

**Comment by sylveon** [comment] 2023-04-14 21:05
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-14 21:05 UTC
Labels: bug
