### ISSUE TITLE
Software doesn't work after update today

### ISSUE THREAD

**Issue by baipiaoguai23** [TranslucentTB/TranslucentTB#664] opened 2022-10-13 05:49 UTC
![image](https://user-images.githubusercontent.com/109348613/195512410-492760c9-fa36-4083-81c9-6eb86898b51d.png)
The software expires after the win11beta version is updated to 22623.741 today.

**Comment by sylveon** [comment] 2022-10-13 13:36
Duplicate of #537

**Closed as not planned by sylveon** 2022-10-13 13:36 UTC
