### ISSUE TITLE
[Bug]: When Upgrading To Windows 11 Insider Beta Preview, {Version 10.0.22623.1255 (ni_release)} The Program/Application Will Not Work Correctly

### ISSUE THREAD

**Issue by DJ-SNIPZ** [TranslucentTB/TranslucentTB#723] opened 2023-02-10 19:28 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Fix Code For TranslucentTB To Work On Windows 11 Insider Beta Preview, {Version 10.0.22623.1255 (ni_release)}

### Expected results

For TranslucentTB To Work On Windows 11 Insider Beta Preview, {Version 10.0.22623.1255 (ni_release)}

### Actual results

I Tried Fixing The Code Locally On My Device, Still Had The Same Issue

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

N/A

### Relevant log output

```shell
[2023-02-10 19:36:42.925] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x200dc [] [Shell_TrayWnd] [explorer.exe]
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:708] 			0x303a4 [[Bug]: When Upgrading To Windows 11 Insider Beta Preview, {Version 10.0.22623.1255 (ni_release)} The Program/Application Will Not Work Correctly · Issue #723 · TranslucentTB/TranslucentTB - Opera] [Chrome_WidgetWin_1] [opera.exe]
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x30440 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-02-10 19:36:42.926] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x200dc [] [Shell_TrayWnd] [explorer.exe]
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:708] 			0x303a4 [[Bug]: When Upgrading To Windows 11 Insider Beta Preview, {Version 10.0.22623.1255 (ni_release)} The Program/Application Will Not Work Correctly · Issue #723 · TranslucentTB/TranslucentTB - Opera] [Chrome_WidgetWin_1] [opera.exe]
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x30440 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-02-10 19:39:49.849] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====


```

**Comment by sylveon** [comment] 2023-02-10 21:50
Duplicate of #537

**Closed as not planned by sylveon** 2023-02-10 21:50 UTC
Labels: bug
