### ISSUE TITLE
#2021.5.121.386ebf1 does not work in Windows 11 Insider Preview (10.0.22623.875)

### ISSUE THREAD

**Issue by taozhiyu** [TranslucentTB/TranslucentTB#675] opened 2022-10-28 10:10 UTC
All following mentioned are the latest versions (#2021.5.121.386ebf1 )  

1. The portable version works fine, but the installation of the Microsoft Store version (msix) warns of a signature error.
2. After updating to Windows 11 Insider Preview (10.0.22623.875), the "transparency" feature does not work at all, as you can see by selecting the colour, it seems that this version comes with a blur or acrylic feature.

![GIF 2022-10-28 11-02-32](https://user-images.githubusercontent.com/49258735/198562273-fab88ed1-1937-4ed5-948f-a7a1ac88e434.gif)

The image above is 5MB in size and may take a while to load (Mainland China users can visit [here](https://pic.rmb.bdstatic.com/bjh/1f27bacda570f7313c56e474cb945f86.gif) if there are problems while loading)

**Comment by Aratolotl** [comment] 2022-10-28 13:40
Also having the same issue on 22H2 22623.875

**Comment by sylveon** [comment] 2022-10-28 14:35
Duplicate of #537

**Closed as not planned** 2022-10-28 14:35 UTC
