### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by OxeraZZ** [TranslucentTB/TranslucentTB#783] opened 2023-03-13 09:04 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I installed TranslucentTB and ran it but the taskbar was not transparent.

### Expected results

I was expecting the taskbar to be transparent.

### Actual results

TranslucentTB has worked but the taskbar doesn't look transparent.

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

I'm trying all settings but it doesn't work.

**Comment by sylveon** [comment] 2023-03-13 10:03
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-13 10:03 UTC
Labels: bug
