### ISSUE TITLE
no fullscreen behavior in full splitscreen mode

### ISSUE THREAD

**Issue by filipwasikai** [TranslucentTB/TranslucentTB#370] opened 2021-03-17 16:21 UTC
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version:  newest I guess
 - Windows build number:  OS Build 1094.867
 - Steps to reproduce:  if I put windows in splitscreen
 - Expected results:  the taskbar to use the setting from Fullscreen mode (black)
 - Actual results:  it uses the regular setting (clear)
 - Other: 
<img width="1280" alt="Screenshot 2021-03-17 171926" src="https://user-images.githubusercontent.com/74904353/111501073-f0a80080-8744-11eb-9705-ccb2d244140f.png">

**Comment by sylveon** [comment] 2021-03-17 16:47
Duplicate of #116

**Closed as completed** 2021-03-17 16:48 UTC
