### ISSUE TITLE
[Bug]: Not working with new win 11 taskbar

### ISSUE THREAD

**Issue by DetectiveYush** [TranslucentTB/TranslucentTB#849] opened 2023-05-09 05:43 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update to new Win 11 build and it will stop working

### Expected results

Should work

### Actual results

Doesn't work

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

It can be temporarily fixed by disabling feature id: 26008830 (new taskbar) with vivetool etc, but will cause blackscreen when and if microsoft removes the old taskbar entirely in an update. Needs to be fixed for the new taskbar.

**Comment by sylveon** [comment] 2023-05-09 15:02
Duplicate of #537

**Closed as not planned by sylveon** 2023-05-09 15:02 UTC
Labels: bug
