### ISSUE TITLE
[Bug]: Doesn't work after the lastest windows update

### ISSUE THREAD

**Issue by bews** [TranslucentTB/TranslucentTB#781] opened 2023-03-11 17:19 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Install update KB5022913

### Expected results

TB continues to work as before

### Actual results

TB doesn't work anymore

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by sylveon** [comment] 2023-03-11 23:16
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-11 23:16 UTC
Labels: bug
