### ISSUE TITLE
[Bug]: Doesn't Work in the latest Windows 11 Update 

### ISSUE THREAD

**Issue by arialp** [TranslucentTB/TranslucentTB#787] opened 2023-03-14 09:44 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

Update Windows 11 to **2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913)**
Launch TranslucentTB

### Expected results

A clear taskbar

### Actual results

Default taskbar

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

[Windows 11 Build 22621.1344](https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9) isn't supported by TranslucentTB because of numerous taskbar changes. 
Check the hyperlink for the changelogs.

### Relevant log output

```shell
[2023-03-14 09:41:00.387] [off] [taskbarattributeworker.cpp:1049] ===== Begin TaskbarAttributeWorker state dump =====
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1056] Monitor 0x10001:
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1060] 	Taskbar handle: 0x100d8 [] [Shell_TrayWnd] [explorer.exe]
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1064] 	Peek button handle: 0x0
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1068] 	Inner XAML handle: 0x0
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1072] 	WorkerW handle: 0x0
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1074] 	Maximised windows:
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1077] 	Normal windows:
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:714] 			[none]
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1083] User is using Aero Peek: false
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1087] User is using Task View: false
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1097] Start menu is opened: false
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1108] Search is opened: false
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1113] Current foreground window: 0x43f07d8 [TranslucentTB] [TrayWindow] [TranslucentTB.exe]
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1117] Worker handles attribute refresh requests from hooks: true
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1121] Battery saver is active: false
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1123] Taskbars currently using normal appearance:
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:714] 		[none]
[2023-03-14 09:41:00.389] [off] [taskbarattributeworker.cpp:1126] ===== End TaskbarAttributeWorker state dump =====
```

**Comment by sylveon** [comment] 2023-03-14 10:25
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-14 10:25 UTC
Labels: bug
