### ISSUE TITLE
White line in Windows 11 22H2 when in "clear" mode

### ISSUE THREAD

**Issue by grimmyxx** [TranslucentTB/TranslucentTB#613] opened 2022-06-08 12:01 UTC
![image](https://user-images.githubusercontent.com/37479830/172611289-516054e5-3fb0-4b1b-a6e7-907005c16ec6.png)

**Comment by sylveon** [comment] 2022-06-08 23:52
Duplicate of #425

**Closed as not planned by sylveon** 2022-06-08 23:52 UTC
