### ISSUE TITLE
Not transparent and doesn't work at all

### ISSUE THREAD

**Issue by aaron819chen** [TranslucentTB/TranslucentTB#552] opened 2022-03-15 00:17 UTC
It works on windows 10 but not windows 11 idk why

**Comment by Muzammil011** [comment] 2022-03-15 06:05
Yup, not working for me on windows 11, dev version 22572

**Comment by aaron819chen** [comment] 2022-03-16 01:40
same I'm also using dev lates version

**Comment by sylveon** [comment] 2022-03-16 01:40
Duplicate of #537

**Closed as completed by sylveon** 2022-03-16 01:40 UTC
