### ISSUE TITLE
[Bug]: My bar doesn't still clear

### ISSUE THREAD

**Issue by joaopldantas** [TranslucentTB/TranslucentTB#694] opened 2022-12-02 18:31 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

When I install and open the app, my bar still the same, don't be clear. Idk what it is, but, i think its the windows 11

### Expected results

a clear bar

### Actual results

nothing really lmao

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2022-12-02 22:33
Duplicate of #537

**Closed as completed by sylveon** 2022-12-02 22:33 UTC
Labels: bug
