### ISSUE TITLE
[regression] [win10] Battery saving mode turns taskbar black 

### ISSUE THREAD

**Issue by DamienCarpy** [TranslucentTB/TranslucentTB#429] opened 2021-09-04 08:46 UTC
[x] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

I uninstalled TB / reinstalled, checked if there was a topic or bug related to a battery saving feature, no joy. My taskbar is ugly black when using battery saving mode ; it was not the case with the previous version.
Also, I lost a lot of time figuring version 2021.4.0.0 is indeed what you call "Version 5" 🙄

**Comment by sylveon** [comment] 2021-09-04 22:20
This is intentional, it's to save battery. It also helps with a Windows 10 bug where the taskbar turns completely transparent if any setting is changed while battery saver is active. Would rather have a new state corresponding to battery saver?

As for versions, 2021.4 is auto-generated while version 5 is manually named. In the future I'll just use the autogenerated name everywhere.

**Comment by DamienCarpy** [comment] 2021-09-06 19:29
It would be nice indeed to be able to turn off this battery saving feature and let people chose 😎 Thanks a lot !

**Comment by TimmyP777** [comment] 2021-09-06 22:55
Is this really working as intended? On my Surface Pro I can change to a battery mode to make it transparent, set it back and it turns black...

But then I exit the app, and the taskbar becomes transparent and stays that way until sleep or reboot.

**Comment by juancruzcarrau** [comment] 2021-09-09 14:25
Hi! I was looking if this was a bug or feature, and I think it is great that you guys took this approach when the pc is in battery saver. However, I think it would be great that either:
 - The user can chose to keep the normal funcionality when in battery saver
 - The taskback goes back to the defaut accent color (light blue in my case for example).

Really looking forward to seeing this in a future release!

**Comment by TimmyP777** [comment] 2021-09-09 15:36
Its pointless. On my Surface Pro 1 I get 2:12 minutes of battery life with it on, and 2:14 minutes with it off.

I cant use the new versions because I keep battery saver on? Please revert these changes!

**Comment by juancruzcarrau** [comment] 2021-09-09 17:04
If the situation is as you say, then maybe it is pointless. I haven't really studied the situation in depth, I just know it's annoying.

**Comment by notavgkaren** [comment] 2021-09-10 17:30
The power saver feature only puts it completely black or completely white, instead of putting it as windows has it by default. I find it _so ugly_ and it doesn't really save much battery. There seems to be an option to disable it but it doesn't work. 
![image](https://user-images.githubusercontent.com/44011613/132893966-63a9bf48-8d89-4bfb-905a-068afcc7ac41.png)

**Comment by sylveon** [comment] 2021-09-10 17:31
This option is not for battery saver, it means that TranslucentTB won't save the changes you do to the config file.

**Comment by notavgkaren** [comment] 2021-09-10 17:55
Thanks for clarifying, I got a bit confused there :)
There should be an option to disable the battery saving feature, though.

**Comment by dariusz-goc** [comment] 2021-10-05 23:42
I also just updated to the new version and I don't like this change ;-/

**Comment by TimmyP777** [comment] 2021-10-06 00:08
Agreed. If we cared so much about battery we wouldnt run the program. Old
versions work well, even in Windows 11 fyi

**Comment by sylveon** [comment] 2021-10-06 00:21
I could flip the argument: if you don't care about battery, why are you running battery saver?

I plan on introducing a way to disable this soon.

**Comment by TimmyP777** [comment] 2021-10-06 00:49
For about 10 extra minutes of battery life (when its enabled). I dont know
where its coming from. This is on a Surface Pro 1st gen Windows 10 (11 for
now).

**Comment by sylveon** [comment] 2021-10-07 04:11
![image](https://user-images.githubusercontent.com/6440374/136318908-593a1faa-ca1a-468f-a94a-b87ae6f12867.png)

Soon<sup>TM</sup>

**Comment by sylveon** [comment] 2021-10-08 20:11
Has been fixed in 2021.5

**Closed as completed by sylveon** 2021-10-08 20:11 UTC

**Comment by tylvn** [comment] 2022-03-17 11:28
Taskbar still turns any of normal, opaque, clear, arcylic when battery saver of TranslucentTB is disable. This problem does not seem to have been solved until now.
