### ISSUE TITLE
Using TranslucentTB with windows 11

### ISSUE THREAD

**Issue by N4Ninja** [TranslucentTB/TranslucentTB#528] opened 2022-01-30 11:05 UTC
When using TranslucentTB with windows 11 there is a faint white line on the task when using it as tranlucent setting.
![Screenshot (1)](https://user-images.githubusercontent.com/98690551/151697023-619c8233-a2f3-480d-b571-5d1989f2cf3e.png)

**Comment by sylveon** [comment] 2022-01-30 21:22
Duplicate of #425

**Closed as completed by sylveon** 2022-01-30 21:22 UTC
