### ISSUE TITLE
[Bug]: it stop working after i updated windows 11 

### ISSUE THREAD

**Issue by Hermes927366** [TranslucentTB/TranslucentTB#824] opened 2023-04-10 12:18 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

it stop working after the latest update of windows 11

### Expected results

.

### Actual results

.

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

windows 11 22H2 (10.0.22621.1485)

**Comment by sylveon** [comment] 2023-04-10 18:08
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-10 18:08 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:30
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
