### ISSUE TITLE
[Bug] Line at the Top of Clear Tray

### ISSUE THREAD

**Issue by Elwood0** [TranslucentTB/TranslucentTB#425] opened 2021-09-02 22:36 UTC
Hello. I have been trying to use the clear mode for TranslucentTB with Windows 11, but I keep getting this line at the top of my tray.

![Screenshot 2021-09-02 183508](https://user-images.githubusercontent.com/30761759/131924748-fe1e1857-6412-4779-9f42-a71349781141.png)

Is there any way to remove this? 

Thank you!

**Comment by sylveon** [comment] 2021-09-02 22:37
This is something in Windows 11 itself, it shows even when TranslucentTB isn't running but is much more subtle.

**Comment by Elwood0** [comment] 2021-09-02 22:41
Thank you for the clarification!

I hope there will be a way to change it in the future.

**Comment by MikeWeiZhou** [comment] 2021-09-24 22:15
And I thought I was the only one that got this problem.

**Comment by FDK101** [comment] 2021-09-30 06:52
Hi All.

I installed RoundedTB and then used winget to install TranslucentTB, after that setup I was able to remove the line:
![image](https://user-images.githubusercontent.com/62417388/135402046-ae213759-a311-449a-88da-a2e113194601.png)

**Comment by maitrong2512** [comment] 2021-10-06 04:51
![image](https://user-images.githubusercontent.com/62295805/136142421-ec18c1f7-8d33-4040-8251-e7bee9d0d9be.png)
I really love the blur effect in old version, could anyone please show me how to enable it?

**Comment by vigo113** [comment] 2021-10-09 21:43
#425 it's a shadow of the taskbar, I don't know if this post will help developers, maybe they already know about it, look how the shadow changes under open start and remains "normal" on the right

https://user-images.githubusercontent.com/92170651/136674397-f62dcb21-fd34-4a29-b927-a1014c218689.mp4

**Comment by smolboii** [comment] 2021-11-01 23:42
yea like @FDK101 i just installed RoundedTB as well as TranslucentTB and that seems to have removed the line. both were installed from the microsoft store, RoundedTB being installed after TranslucentTB.

edit: it does create some empty space around task bar when a window is maximised (if u have acrylic / opaque task bar set for maximised window), but this can be minimised by setting margin to 1. radius can be 0 but margin has to be >= 1 for the line to disappear.

**Comment by torchgm** [comment] 2021-11-02 21:58
Whilst this will technically work, RoundedTB doesn't currently work properly with autohide, so if you autohide the taskbar then  the above solution isn't really ideal.

**Comment by tarynficklin** [comment] 2021-11-21 03:56
I ran a windows 11 sandbox, and it looks like the gray line exists on the vanilla taskbar. If you keep out a keen eye, you can see that the gray line ends right at the corner overflow. Fingers crossed that Microsoft notices this bug and fixes it. The troubling part is that it may be subtle enough that they don't get to it anytime soon. 😬

![image](https://user-images.githubusercontent.com/38847691/142748770-99f226ba-605a-44bf-80ca-344567687110.png)

**Comment by TheShark27** [comment] 2021-12-02 15:19
For anyone that's bugged by this, in the "advanced" section RoundedTB now has a "fill taskbar when maximised" option, that I've never seen before. This way you can effectively fixes the gray line issue, and have a normal Windows 11 taskbar with maximised windows.
As @smolboii pointed out, setting the top margin to 1 and everything else to 0 is enough to fix the issue.

**Comment by NiklasVoigt** [comment] 2021-12-25 13:47
RoundTB installed and set Margin to 1 helps!

**Comment by vishwakarmakrishna** [comment] 2022-03-13 16:54
Works fine with RoundedTB(1 Margin ) & TranslucentTB

**Comment by PsychoPops** [comment] 2022-05-06 21:51
I can confirm with the new windows update 22616.1 that TranslucentTB is working again. Also to get rid of the white line install RoundedTB and line disappears.

![Desktop](https://user-images.githubusercontent.com/102784408/167241279-d824981b-1e4e-4d6e-b616-30a0a487f3f1.png)

**Comment by joshthehappy** [comment] 2022-05-10 14:09
Thanks, this is a better solution than the sloppy one I was using.

**Comment by KrazyDeinos** [comment] 2022-05-10 16:19
> For anyone that's bugged by this, in the "advanced" section RoundedTB now has a "fill taskbar when maximised" option, that I've never seen before. This way you can effectively fixes the gray line issue, and have a normal Windows 11 taskbar with maximised windows. As @smolboii pointed out, setting the top margin to 1 and everything else to 0 is enough to fix the issue.

I hope for a better solution, because this hideous line is then visible when maximized, it's that or a 1 px gap. Neither is a good solution, there need to be a way to make the outline the same as the rest of the taskbar

**Comment by sylveon** [comment] 2022-05-10 18:34
I had a solution for build 22000 in the development branch, but build 22616 broke that solution, so I have to find another one.

**Comment by KrazyDeinos** [comment] 2022-05-10 20:12
Ah ok, well fingers crossed and keep up the excellent work!🏅

**Comment by sylveon** [comment] 2022-07-03 20:25
Fixed in https://github.com/TranslucentTB/TranslucentTB/commit/0de778dc41258add2238d4f4bf722a575babf06e

**Closed as completed by sylveon** 2022-07-03 20:25 UTC

**Comment by farzher** [comment] 2022-07-21 08:13
> Works fine with RoundedTB(1 Margin ) & TranslucentTB

it works to hide the line. but breaks the show desktop button .-.

**Comment by woadey** [comment] 2022-11-09 04:35
> Fixed in [0de778d](https://github.com/TranslucentTB/TranslucentTB/commit/0de778dc41258add2238d4f4bf722a575babf06e)

When will this be released to the Microsoft Store?

**Comment by PsychoPops** [comment] 2022-11-11 07:00
If your Translucent TB is not working right please let me know. There are a few fixes to make it workable. Its stupid microsoft updates and new taskbar features that make it seem to stop working.
