### ISSUE TITLE
[Bug]: can not work on win 11 Insider Preview dev 23466 with ViVeTool /enable /id:29785186

### ISSUE THREAD

**Issue by abcdehc** [TranslucentTB/TranslucentTB#863] opened 2023-06-13 03:10 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. using win 11 Insider Preview dev 23466 with ViVeTool /enable /id:29785186
2. install TranslucentTB from microsoft store
3. try to set to Clear or Acrylic

### Expected results

change to Clear or Acrylic

### Actual results

nothing changed

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

**Comment by sylveon** [comment] 2023-06-13 04:00
Duplicate of #537

**Closed as not planned by sylveon** 2023-06-13 04:00 UTC
Labels: bug
