### ISSUE TITLE
Taskbar is not fully clear in windows 11

### ISSUE THREAD

**Issue by maitrong2512** [TranslucentTB/TranslucentTB#448] opened 2021-10-05 08:33 UTC
![image](https://user-images.githubusercontent.com/62295805/135988973-c7aeb322-11de-4bb4-9cb1-bfc49cdd1cf2.png)

[] I have checked the issue tracker if my question or bug has
already been fixed or answered in another (possibly closed)
issue.

 - Version information: Box version 2.0

 - Steps to reproduce:
   1. Take the box.
   2. Put the box on the table.

 - Expected results: The box sits on the table.

 - Actual results: The box disappears spontaneously once
   put on the table.

 - Other: The box I ordered was damaged.

**Comment by sylveon** [comment] 2021-10-05 11:44
Duplicate of #425

**Closed as completed** 2021-10-05 11:44 UTC
