### ISSUE TITLE
Clear mode: white line shows

### ISSUE THREAD

**Issue by PurBlu** [TranslucentTB/TranslucentTB#608] opened 2022-05-18 06:26 UTC
![image](https://user-images.githubusercontent.com/74239692/168971334-13d2df5a-c3e5-4aa2-9c82-95b9722e4609.png)
Seems a new design change introduced by beta version of Windows. 
A 'white line' shows when choosing Clear mode which looks quite weird.
Currently running Windows version 22621.1

**Comment by sylveon** [comment] 2022-05-18 08:56
Duplicate of #425

**Closed as completed by sylveon** 2022-05-18 08:57 UTC
