### ISSUE TITLE
[Bug]: can't make taskbar transparent

### ISSUE THREAD

**Issue by ghost** [TranslucentTB/TranslucentTB#819] opened 2023-04-08 03:47 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

The app when downloaded didn't make my taskbar transparent while previous downloads made it transparent, but recently when I turned it on it didn't make the taskbar transparent even though it did. was allowed in the startup app and I gave it all kinds of permissions to run

### Expected results

Make taskbar transparent

### Actual results

Can't make taskbar transparent
![TASKBAR](https://user-images.githubusercontent.com/117145939/230701853-9b33605a-14b4-4640-ba18-07ed70600a08.png)

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

Version of Windows 11: 22H2 (OS build 22621.1485)

**Comment by sylveon** [comment] 2023-04-08 03:48
Duplicate of #537

**Closed as not planned by sylveon** 2023-04-08 03:48 UTC
Labels: bug

**Comment by WantedTab** [comment] 2023-05-03 09:32
If you still look for a fix, you can install ViveTool, run the exe, open cmd with administration rights, go to .exe folder and run the following commands: "vivetool /disable /id:26008830" and "vivetool /disable /id:38764045", and then restart the windows, the program will function as expected.
