### ISSUE TITLE
[Bug]: TranslucentTB does not work on Windows Build 22631.1972

### ISSUE THREAD

**Issue by ParaliyzedEvo** [TranslucentTB/TranslucentTB#871] opened 2023-07-02 21:23 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

1. Update to Windows Build 22631.1972 
2. Try to use the clear option on Windows Build 22631.1972

### Expected results

The clear option working on the taskbar

### Actual results

Every option in TranslucentTB does not work

### Windows version

Windows 11 Insider builds (builds 22623 and up). Please mention exact build.

### Other details

**Now before you redirect me to issue #537** I've already done everything that had to be done for TTB to work like using vivetool to disable STTest as shown in the screenshot.
![image](https://github.com/TranslucentTB/TranslucentTB/assets/107338855/e30d0c93-f1e7-4e90-8a9b-7b9fadc5c604)
I've restarted my pc and reinstalled the app already with the STTest disabled already. I've tried enabling and disabling the STTest already but TTB still does not work. Like I said I tried using some of the solutions that were shown on #537 but they don't work. Hope you can help me fix this!

**Comment by sylveon** [comment] 2023-07-02 21:36
Duplicate of #537

**Closed as not planned** 2023-07-02 21:37 UTC
Labels: bug
