### ISSUE TITLE
[issue]:The app 'TranslucentTB' does not work. When I first got the app it worked fine but recently the app does not make my task bat translucent.

### ISSUE THREAD

**Issue by someone1231243** [TranslucentTB/TranslucentTB#757] opened 2023-03-04 12:41 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

I do not know any method of fixing this issue.

### Expected results

I do not know what to write here.

### Actual results

I do not know what to write here.

### Windows version

Windows 11 SV2 (builds 22621-22622)

**Comment by abdelkaderfadil0** [comment] 2023-03-04 12:54
i have same problem TranslucentTB doesn't work after last windows 11 update  build 22621.1344

**Comment by Noicdi** [comment] 2023-03-04 12:55
I have same problem. When my PC installed update package [Windows 11 Version 22H2 (KB5022913)] and rebooted, TranslucentTB does not work.

Now my Windows version is **Windows 11 22H2 22621.1344**.

![2023-03-04_20-54-50](https://user-images.githubusercontent.com/56010105/222902832-d386f6a2-0be1-4f67-917d-3ee61a128f7e.png)

**Comment by sguming** [comment] 2023-03-04 12:59
same problem

**Comment by White-Clouds** [comment] 2023-03-04 14:24
KB5022913（OS 22621.1344） 更新更改了任务栏，所以很多类似的软件都失效了。
The KB5022913 update changed the taskbar, so many similar software did not work.

Duplicate of #756 and #537

**Comment by diefrtt** [comment] 2023-03-04 14:39
Same problem, doesn't work after last windows 11 update build 22621.1344

**Comment by hanabe1** [comment] 2023-03-04 14:44
Me too. In latest Windows 11 Update build 22621.1344, app didn't work properly.

![image](https://user-images.githubusercontent.com/107563363/222909481-f2cefd15-8a95-4469-883b-403698e162ea.png)

**Comment by HamzaYslmn** [comment] 2023-03-04 17:03
Same...

**Comment by DarkestFantasies** [comment] 2023-03-04 17:22
same

**Comment by pavelkos** [comment] 2023-03-04 17:28
Same problem after update to 22H2 22621.1344

**Comment by rvwt** [comment] 2023-03-04 19:12
same

**Comment by sylveon** [comment] 2023-03-04 19:31
Duplicate of #537

**Closed as not planned by sylveon** 2023-03-04 19:31 UTC
Labels: bug
