### ISSUE TITLE
[Bug]: 多任务分屏时任务栏无法设置不透明

### ISSUE THREAD

**Issue by KoopGeminimini** [TranslucentTB/TranslucentTB#966] opened 2023-12-29 02:14 UTC
### Please check for a duplicate first

- [X] I have checked the issue tracker if my bug has already been fixed or answered in another (possibly closed) issue.

### Steps to reproduce the issue

多任务分屏任务栏无法设置不透明

### Expected results

设置里面有   **“多任务分屏时占满除任务栏外的桌面”**的设置

### Actual results

没有有关设置

### Windows version

Windows 11 SV2 (builds 22621-22622)

### Other details

![image](https://github.com/TranslucentTB/TranslucentTB/assets/155123158/fb559daf-94fc-4872-950c-a3e25b381e30)

**Comment by sylveon** [comment] 2024-03-05 00:46
Duplicate of #116

**Closed as not planned by sylveon** 2024-03-05 00:46 UTC
Labels: bug
