### ISSUE TITLE
Translucent TB win11 taskbar with subtle black horizontal lines

### ISSUE THREAD

**Issue by ZFLUOSHENG** [TranslucentTB/TranslucentTB#470] opened 2021-10-20 01:28 UTC
Hello, beloved developer, I found a problem, it is not clear whether it is a problem with my settings or the program itself, I opened the software in the Win11 environment, I found that in the taskbar transparent at the same time can also vaguely see a black horizontal line
![image](https://user-images.githubusercontent.com/83005123/138012831-d218c8cf-299d-4161-b55f-a6de276b1416.png)

**Comment by sylveon** [comment] 2021-10-20 01:40
Duplicate of #425

**Closed as completed by sylveon** 2021-10-20 01:40 UTC
